#pragma once
// all headers in filtering:
#include "gaussFixed.h"
#include "highpass.h"
#include "laplace.h"
#include "lowpass.h"
#include "prewittHoriz.h"
#include "prewittVert.h"
#include "robertsDown.h"
#include "robertsUp.h"
#include "scharrHoriz.h"
#include "scharrVert.h"
#include "sharpen.h"
#include "sobelCross.h"
#include "sobelHoriz.h"
#include "sobelHorizSecond.h"
#include "sobelVert.h"
#include "sobelVertSecond.h"
