// Code automatically generated by nppCodeGenerator - do not modify manually
#include <common/moduleEnabler.h> //NOLINT(misc-include-cleaner)
#if MPP_ENABLE_NPP_BACKEND
#include <common/image/pixelTypeEnabler.h> //NOLINT(misc-include-cleaner)

#include "image32uC2View.h" //NOLINT
#include "imageView.h"  //NOLINT
#include <backends/cuda/devVarView.h> //NOLINT
#include <backends/npp/nppException.h>  //NOLINT
#include <common/defines.h> //NOLINT
#include <common/exception.h> //NOLINT
#include <common/image/affineTransformation.h> //NOLINT
#include <common/image/border.h> //NOLINT
#include <common/image/bound.h> //NOLINT
#include <common/image/matrix.h> //NOLINT
#include <common/image/pixelTypes.h> //NOLINT
#include <common/image/quad.h> //NOLINT
#include <common/image/roi.h> //NOLINT
#include <common/image/roiException.h>  //NOLINT
#include <common/image/size2D.h>  //NOLINT
#include <common/image/sizePitched.h>  //NOLINT
#include <common/safeCast.h>  //NOLINT
#include <cstddef> //NOLINT
#include <nppdefs.h>  //NOLINT
#include <nppi_data_exchange_and_initialization.h> //NOLINT
#include <nppi_statistics_functions.h> //NOLINT

namespace mpp::image::npp
{
Image32uC2View::Image32uC2View(const Size2D &aSize) : ImageView<Pixel32uC2>(aSize)
{
}

Image32uC2View::Image32uC2View(Pixel32uC2 *aBasePointer, const SizePitched &aSizeAlloc)
    : ImageView<Pixel32uC2>(aBasePointer, aSizeAlloc)
{
}
Image32uC2View::Image32uC2View(Pixel32uC2 *aBasePointer, const SizePitched &aSizeAlloc, const Roi &aRoi)
    : ImageView<Pixel32uC2>(aBasePointer, aSizeAlloc, aRoi)
{
}

Image32uC2View Image32uC2View::GetView(const Roi &aRoi)
{
    return {Pointer(), SizePitched(SizeAlloc(), Pitch()), aRoi};
}

Image32uC2View Image32uC2View::GetView(const Border &aBorder)
{
    const Roi newRoi = ROI() + aBorder;
    checkRoiIsInRoi(newRoi, Roi(0, 0, SizeAlloc()));
    return {Pointer(), SizePitched(SizeAlloc(), Pitch()), newRoi};
}

//NOLINTBEGIN(readability-identifier-naming,readability-avoid-const-params-in-decls, bugprone-easily-swappable-parameters, readability-convert-member-functions-to-static)
#if MPPi_ENABLE_UINT32_TYPE && MPPi_ENABLE_TWO_CHANNEL

Image32uC2View &Image32uC2View::Set(const Pixel32uC2 &aValue, const NppStreamContext &nppStreamCtx)
{
    nppSafeCallExt(nppiSet_32u_C2R_Ctx(aValue.data(), reinterpret_cast<Npp32u *>(PointerRoi()), to_int(Pitch()), NppiSizeRoi(), nppStreamCtx),
                   "ROI SrcDst: " << ROI());
    return *this;
}

void Image32uC2View::MaximumError(const Image32uC2View &pSrc2, mpp::cuda::DevVarView<double> &pError, mpp::cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const
{
    checkSameSize(ROI(), pSrc2.ROI());
    nppSafeCallExt(nppiMaximumError_32u_C2R_Ctx(reinterpret_cast<const Npp32u *>(PointerRoi()), to_int(Pitch()), reinterpret_cast<const Npp32u *>(pSrc2.PointerRoi()), to_int(pSrc2.Pitch()), NppiSizeRoi(), pError.Pointer(), pDeviceBuffer.Pointer(), nppStreamCtx),
                   "ROI Src1: " << ROI() << " ROI Src2: " << pSrc2.ROI());
}

size_t Image32uC2View::MaximumErrorGetBufferHostSize(const NppStreamContext &nppStreamCtx) const
{
    size_t retValue = 0;
    nppSafeCall(nppiMaximumErrorGetBufferHostSize_32u_C2R_Ctx(NppiSizeRoi(), &retValue, nppStreamCtx));
    return retValue;
}

void Image32uC2View::AverageError(const Image32uC2View &pSrc2, mpp::cuda::DevVarView<double> &pError, mpp::cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const
{
    checkSameSize(ROI(), pSrc2.ROI());
    nppSafeCallExt(nppiAverageError_32u_C2R_Ctx(reinterpret_cast<const Npp32u *>(PointerRoi()), to_int(Pitch()), reinterpret_cast<const Npp32u *>(pSrc2.PointerRoi()), to_int(pSrc2.Pitch()), NppiSizeRoi(), pError.Pointer(), pDeviceBuffer.Pointer(), nppStreamCtx),
                   "ROI Src1: " << ROI() << " ROI Src2: " << pSrc2.ROI());
}

size_t Image32uC2View::AverageErrorGetBufferHostSize(const NppStreamContext &nppStreamCtx) const
{
    size_t retValue = 0;
    nppSafeCall(nppiAverageErrorGetBufferHostSize_32u_C2R_Ctx(NppiSizeRoi(), &retValue, nppStreamCtx));
    return retValue;
}

void Image32uC2View::MaximumRelativeError(const Image32uC2View &pSrc2, mpp::cuda::DevVarView<double> &pError, mpp::cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const
{
    checkSameSize(ROI(), pSrc2.ROI());
    nppSafeCallExt(nppiMaximumRelativeError_32u_C2R_Ctx(reinterpret_cast<const Npp32u *>(PointerRoi()), to_int(Pitch()), reinterpret_cast<const Npp32u *>(pSrc2.PointerRoi()), to_int(pSrc2.Pitch()), NppiSizeRoi(), pError.Pointer(), pDeviceBuffer.Pointer(), nppStreamCtx),
                   "ROI Src1: " << ROI() << " ROI Src2: " << pSrc2.ROI());
}

size_t Image32uC2View::MaximumRelativeErrorGetBufferHostSize(const NppStreamContext &nppStreamCtx) const
{
    size_t retValue = 0;
    nppSafeCall(nppiMaximumRelativeErrorGetBufferHostSize_32u_C2R_Ctx(NppiSizeRoi(), &retValue, nppStreamCtx));
    return retValue;
}

void Image32uC2View::AverageRelativeError(const Image32uC2View &pSrc2, mpp::cuda::DevVarView<double> &pError, mpp::cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const
{
    checkSameSize(ROI(), pSrc2.ROI());
    nppSafeCallExt(nppiAverageRelativeError_32u_C2R_Ctx(reinterpret_cast<const Npp32u *>(PointerRoi()), to_int(Pitch()), reinterpret_cast<const Npp32u *>(pSrc2.PointerRoi()), to_int(pSrc2.Pitch()), NppiSizeRoi(), pError.Pointer(), pDeviceBuffer.Pointer(), nppStreamCtx),
                   "ROI Src1: " << ROI() << " ROI Src2: " << pSrc2.ROI());
}

size_t Image32uC2View::AverageRelativeErrorGetBufferHostSize(const NppStreamContext &nppStreamCtx) const
{
    size_t retValue = 0;
    nppSafeCall(nppiAverageRelativeErrorGetBufferHostSize_32u_C2R_Ctx(NppiSizeRoi(), &retValue, nppStreamCtx));
    return retValue;
}

#endif // MPPi_ENABLE_UINT32_TYPE && MPPi_ENABLE_TWO_CHANNEL
//NOLINTEND(readability-identifier-naming,readability-avoid-const-params-in-decls, bugprone-easily-swappable-parameters, readability-convert-member-functions-to-static)
} // namespace mpp::image::npp
#endif // MPP_ENABLE_NPP_BACKEND
