// Code automatically generated by nppCodeGenerator - do not modify manually
#include <common/moduleEnabler.h> //NOLINT(misc-include-cleaner)
#if OPP_ENABLE_NPP_BACKEND
#include <common/image/pixelTypeEnabler.h> //NOLINT(misc-include-cleaner)

#include "image32uC3View.h" //NOLINT
#include "imageView.h"  //NOLINT
#include <backends/cuda/devVarView.h> //NOLINT
#include <backends/npp/nppException.h>  //NOLINT
#include <common/defines.h> //NOLINT
#include <common/exception.h> //NOLINT
#include <common/image/affineTransformation.h> //NOLINT
#include <common/image/border.h> //NOLINT
#include <common/image/bound.h> //NOLINT
#include <common/image/matrix.h> //NOLINT
#include <common/image/pixelTypes.h> //NOLINT
#include <common/image/quad.h> //NOLINT
#include <common/image/roi.h> //NOLINT
#include <common/image/roiException.h>  //NOLINT
#include <common/image/size2D.h>  //NOLINT
#include <common/image/sizePitched.h>  //NOLINT
#include <common/safeCast.h>  //NOLINT
#include <cstddef> //NOLINT
#include <nppdefs.h>  //NOLINT
#include <nppi_data_exchange_and_initialization.h> //NOLINT
#include <nppi_filtering_functions.h> //NOLINT
#include <nppi_statistics_functions.h> //NOLINT

namespace opp::image::npp
{
Image32uC3View::Image32uC3View(const Size2D &aSize) : ImageView<Pixel32uC3>(aSize)
{
}

Image32uC3View::Image32uC3View(Pixel32uC3 *aBasePointer, const SizePitched &aSizeAlloc)
    : ImageView<Pixel32uC3>(aBasePointer, aSizeAlloc)
{
}
Image32uC3View::Image32uC3View(Pixel32uC3 *aBasePointer, const SizePitched &aSizeAlloc, const Roi &aRoi)
    : ImageView<Pixel32uC3>(aBasePointer, aSizeAlloc, aRoi)
{
}

Image32uC3View Image32uC3View::GetView(const Roi &aRoi)
{
    return {Pointer(), SizePitched(SizeAlloc(), Pitch()), aRoi};
}

Image32uC3View Image32uC3View::GetView(const Border &aBorder)
{
    const Roi newRoi = ROI() + aBorder;
    checkRoiIsInRoi(newRoi, Roi(0, 0, SizeAlloc()));
    return {Pointer(), SizePitched(SizeAlloc(), Pitch()), newRoi};
}

//NOLINTBEGIN(readability-identifier-naming,readability-avoid-const-params-in-decls, bugprone-easily-swappable-parameters, readability-convert-member-functions-to-static)
#if OPPi_ENABLE_UINT32_TYPE && OPPi_ENABLE_THREE_CHANNEL

Image32uC3View &Image32uC3View::Set(const Pixel32uC3 &aValue, const NppStreamContext &nppStreamCtx)
{
    nppSafeCallExt(nppiSet_32u_C3R_Ctx(aValue.data(), reinterpret_cast<Npp32u *>(PointerRoi()), to_int(Pitch()), NppiSizeRoi(), nppStreamCtx),
                   "ROI SrcDst: " << ROI());
    return *this;
}

Image32uC3View &Image32uC3View::FloodFill(NppiPoint oSeed, const Pixel32uC3 &aNewValues, NppiNorm eNorm, NppiConnectedRegion *pConnectedRegion, opp::cuda::DevVarView<byte> &pBuffer, const NppStreamContext &nppStreamCtx)
{
    nppSafeCallExt(nppiFloodFill_32u_C3IR_Ctx(reinterpret_cast<Npp32u *>(PointerRoi()), to_int(Pitch()), oSeed, aNewValues.data(), eNorm, NppiSizeRoi(), pConnectedRegion, pBuffer.Pointer(), nppStreamCtx),
                   "ROI SrcDst: " << ROI());
    return *this;
}

Image32uC3View &Image32uC3View::FloodFillBoundary(NppiPoint oSeed, const Pixel32uC3 &aNewValues, const Pixel32uC3 &aBoundaryValues, NppiNorm eNorm, NppiConnectedRegion *pConnectedRegion, opp::cuda::DevVarView<byte> &pBuffer, const NppStreamContext &nppStreamCtx)
{
    nppSafeCallExt(nppiFloodFillBoundary_32u_C3IR_Ctx(reinterpret_cast<Npp32u *>(PointerRoi()), to_int(Pitch()), oSeed, aNewValues.data(), aBoundaryValues.data(), eNorm, NppiSizeRoi(), pConnectedRegion, pBuffer.Pointer(), nppStreamCtx),
                   "ROI SrcDst: " << ROI());
    return *this;
}

Image32uC3View &Image32uC3View::FloodFillRange(NppiPoint oSeed, Pixel32uC3 &aMin, Pixel32uC3 &aMax, const Pixel32uC3 &aNewValues, NppiNorm eNorm, NppiConnectedRegion *pConnectedRegion, opp::cuda::DevVarView<byte> &pBuffer, const NppStreamContext &nppStreamCtx)
{
    nppSafeCallExt(nppiFloodFillRange_32u_C3IR_Ctx(reinterpret_cast<Npp32u *>(PointerRoi()), to_int(Pitch()), oSeed, aMin.data(), aMax.data(), aNewValues.data(), eNorm, NppiSizeRoi(), pConnectedRegion, pBuffer.Pointer(), nppStreamCtx),
                   "ROI SrcDst: " << ROI());
    return *this;
}

Image32uC3View &Image32uC3View::FloodFillRangeBoundary(NppiPoint oSeed, Pixel32uC3 &aMin, Pixel32uC3 &aMax, const Pixel32uC3 &aNewValues, const Pixel32uC3 &aBoundaryValues, NppiNorm eNorm, NppiConnectedRegion *pConnectedRegion, opp::cuda::DevVarView<byte> &pBuffer, const NppStreamContext &nppStreamCtx)
{
    nppSafeCallExt(nppiFloodFillRangeBoundary_32u_C3IR_Ctx(reinterpret_cast<Npp32u *>(PointerRoi()), to_int(Pitch()), oSeed, aMin.data(), aMax.data(), aNewValues.data(), aBoundaryValues.data(), eNorm, NppiSizeRoi(), pConnectedRegion, pBuffer.Pointer(), nppStreamCtx),
                   "ROI SrcDst: " << ROI());
    return *this;
}

Image32uC3View &Image32uC3View::FloodFillGradient(NppiPoint oSeed, Pixel32uC3 &aMin, Pixel32uC3 &aMax, const Pixel32uC3 &aNewValues, NppiNorm eNorm, NppiConnectedRegion *pConnectedRegion, opp::cuda::DevVarView<byte> &pBuffer, const NppStreamContext &nppStreamCtx)
{
    nppSafeCallExt(nppiFloodFillGradient_32u_C3IR_Ctx(reinterpret_cast<Npp32u *>(PointerRoi()), to_int(Pitch()), oSeed, aMin.data(), aMax.data(), aNewValues.data(), eNorm, NppiSizeRoi(), pConnectedRegion, pBuffer.Pointer(), nppStreamCtx),
                   "ROI SrcDst: " << ROI());
    return *this;
}

Image32uC3View &Image32uC3View::FloodFillGradientBoundary(NppiPoint oSeed, Pixel32uC3 &aMin, Pixel32uC3 &aMax, const Pixel32uC3 &aNewValues, const Pixel32uC3 &aBoundaryValues, NppiNorm eNorm, NppiConnectedRegion *pConnectedRegion, opp::cuda::DevVarView<byte> &pBuffer, const NppStreamContext &nppStreamCtx)
{
    nppSafeCallExt(nppiFloodFillGradientBoundary_32u_C3IR_Ctx(reinterpret_cast<Npp32u *>(PointerRoi()), to_int(Pitch()), oSeed, aMin.data(), aMax.data(), aNewValues.data(), aBoundaryValues.data(), eNorm, NppiSizeRoi(), pConnectedRegion, pBuffer.Pointer(), nppStreamCtx),
                   "ROI SrcDst: " << ROI());
    return *this;
}

void Image32uC3View::DotProd(const Image32uC3View &pSrc2, opp::cuda::DevVarView<double> &aDp, opp::cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const
{
    checkSameSize(ROI(), pSrc2.ROI());
    nppSafeCallExt(nppiDotProd_32u64f_C3R_Ctx(reinterpret_cast<const Npp32u *>(PointerRoi()), to_int(Pitch()), reinterpret_cast<const Npp32u *>(pSrc2.PointerRoi()), to_int(pSrc2.Pitch()), NppiSizeRoi(), aDp.Pointer(), pDeviceBuffer.Pointer(), nppStreamCtx),
                   "ROI Src1: " << ROI() << " ROI Src2: " << pSrc2.ROI());
}

size_t Image32uC3View::DotProdGetBufferHostSize(const NppStreamContext &nppStreamCtx) const
{
    size_t retValue = 0;
    nppSafeCall(nppiDotProdGetBufferHostSize_32u64f_C3R_Ctx(NppiSizeRoi(), &retValue, nppStreamCtx));
    return retValue;
}

void Image32uC3View::MaximumError(const Image32uC3View &pSrc2, opp::cuda::DevVarView<double> &pError, opp::cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const
{
    checkSameSize(ROI(), pSrc2.ROI());
    nppSafeCallExt(nppiMaximumError_32u_C3R_Ctx(reinterpret_cast<const Npp32u *>(PointerRoi()), to_int(Pitch()), reinterpret_cast<const Npp32u *>(pSrc2.PointerRoi()), to_int(pSrc2.Pitch()), NppiSizeRoi(), pError.Pointer(), pDeviceBuffer.Pointer(), nppStreamCtx),
                   "ROI Src1: " << ROI() << " ROI Src2: " << pSrc2.ROI());
}

size_t Image32uC3View::MaximumErrorGetBufferHostSize(const NppStreamContext &nppStreamCtx) const
{
    size_t retValue = 0;
    nppSafeCall(nppiMaximumErrorGetBufferHostSize_32u_C3R_Ctx(NppiSizeRoi(), &retValue, nppStreamCtx));
    return retValue;
}

void Image32uC3View::AverageError(const Image32uC3View &pSrc2, opp::cuda::DevVarView<double> &pError, opp::cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const
{
    checkSameSize(ROI(), pSrc2.ROI());
    nppSafeCallExt(nppiAverageError_32u_C3R_Ctx(reinterpret_cast<const Npp32u *>(PointerRoi()), to_int(Pitch()), reinterpret_cast<const Npp32u *>(pSrc2.PointerRoi()), to_int(pSrc2.Pitch()), NppiSizeRoi(), pError.Pointer(), pDeviceBuffer.Pointer(), nppStreamCtx),
                   "ROI Src1: " << ROI() << " ROI Src2: " << pSrc2.ROI());
}

size_t Image32uC3View::AverageErrorGetBufferHostSize(const NppStreamContext &nppStreamCtx) const
{
    size_t retValue = 0;
    nppSafeCall(nppiAverageErrorGetBufferHostSize_32u_C3R_Ctx(NppiSizeRoi(), &retValue, nppStreamCtx));
    return retValue;
}

void Image32uC3View::MaximumRelativeError(const Image32uC3View &pSrc2, opp::cuda::DevVarView<double> &pError, opp::cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const
{
    checkSameSize(ROI(), pSrc2.ROI());
    nppSafeCallExt(nppiMaximumRelativeError_32u_C3R_Ctx(reinterpret_cast<const Npp32u *>(PointerRoi()), to_int(Pitch()), reinterpret_cast<const Npp32u *>(pSrc2.PointerRoi()), to_int(pSrc2.Pitch()), NppiSizeRoi(), pError.Pointer(), pDeviceBuffer.Pointer(), nppStreamCtx),
                   "ROI Src1: " << ROI() << " ROI Src2: " << pSrc2.ROI());
}

size_t Image32uC3View::MaximumRelativeErrorGetBufferHostSize(const NppStreamContext &nppStreamCtx) const
{
    size_t retValue = 0;
    nppSafeCall(nppiMaximumRelativeErrorGetBufferHostSize_32u_C3R_Ctx(NppiSizeRoi(), &retValue, nppStreamCtx));
    return retValue;
}

void Image32uC3View::AverageRelativeError(const Image32uC3View &pSrc2, opp::cuda::DevVarView<double> &pError, opp::cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const
{
    checkSameSize(ROI(), pSrc2.ROI());
    nppSafeCallExt(nppiAverageRelativeError_32u_C3R_Ctx(reinterpret_cast<const Npp32u *>(PointerRoi()), to_int(Pitch()), reinterpret_cast<const Npp32u *>(pSrc2.PointerRoi()), to_int(pSrc2.Pitch()), NppiSizeRoi(), pError.Pointer(), pDeviceBuffer.Pointer(), nppStreamCtx),
                   "ROI Src1: " << ROI() << " ROI Src2: " << pSrc2.ROI());
}

size_t Image32uC3View::AverageRelativeErrorGetBufferHostSize(const NppStreamContext &nppStreamCtx) const
{
    size_t retValue = 0;
    nppSafeCall(nppiAverageRelativeErrorGetBufferHostSize_32u_C3R_Ctx(NppiSizeRoi(), &retValue, nppStreamCtx));
    return retValue;
}

#endif // OPPi_ENABLE_UINT32_TYPE && OPPi_ENABLE_THREE_CHANNEL
//NOLINTEND(readability-identifier-naming,readability-avoid-const-params-in-decls, bugprone-easily-swappable-parameters, readability-convert-member-functions-to-static)
} // namespace opp::image::npp
#endif // OPP_ENABLE_NPP_BACKEND
