// Code automatically generated by nppCodeGenerator - do not modify manually

#pragma once
#include <common/moduleEnabler.h>
#if OPP_ENABLE_NPP_BACKEND
#include <common/image/pixelTypeEnabler.h>

#include "imageView.h"
#include <backends/cuda/devVarView.h>
#include <backends/npp/nppException.h>
#include <common/image/pixelTypes.h>
#include <common/image/roi.h>
#include <common/image/roiException.h>
#include <common/image/size2D.h>
#include <common/image/sizePitched.h>

namespace opp::image::npp
{
// forward declaration:

class Image16scC1View : public ImageView<Pixel16scC1>
{
  protected:
    Image16scC1View() = default;
    explicit Image16scC1View(const Size2D &aSize);

  public:
    Image16scC1View(Pixel16scC1 *aBasePointer, const SizePitched &aSizeAlloc);
    Image16scC1View(Pixel16scC1 *aBasePointer, const SizePitched &aSizeAlloc, const Roi &aRoi);
    ~Image16scC1View() = default;

    Image16scC1View(const Image16scC1View &)     = default;
    Image16scC1View(Image16scC1View &&) noexcept = default;

    Image16scC1View &operator=(const Image16scC1View &)     = default;
    Image16scC1View &operator=(Image16scC1View &&) noexcept = default;

    /// <summary>
    /// Returns a new Image16scC1View with the new ROI
    /// </summary>
    [[nodiscard]] Image16scC1View GetView(const Roi &aRoi) const;

    /// <summary>
    /// Returns a new ImageView with the current ROI adapted by aBorder
    /// </summary>
    [[nodiscard]] Image16scC1View GetView(const Border &aBorder = Border()) const;

    //NOLINTBEGIN(readability-identifier-naming,readability-avoid-const-params-in-decls, bugprone-easily-swappable-parameters, readability-convert-member-functions-to-static)
#if OPPi_ENABLE_COMPLEX_INT16_TYPE && OPPi_ENABLE_ONE_CHANNEL

    // NppStatus nppiSet_16sc_C1R_Ctx(const Npp16sc oValue, Npp16sc * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16scC1View &Set(const Pixel16scC1 &oValue, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiCopy_16sc_C1R_Ctx(const Npp16sc * pSrc, int nSrcStep, Npp16sc * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16scC1View &Copy(Image16scC1View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiAddC_16sc_C1RSfs_Ctx(const Npp16sc * pSrc1, int nSrc1Step, const Npp16sc nConstant, Npp16sc * pDst, int nDstStep, NppiSize oSizeROI, int nScaleFactor, NppStreamContext nppStreamCtx)
    Image16scC1View &Add(const Pixel16scC1 &nConstant, Image16scC1View &pDst, int nScaleFactor, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiAddC_16sc_C1IRSfs_Ctx(const Npp16sc nConstant, Npp16sc * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, int nScaleFactor, NppStreamContext nppStreamCtx)
    Image16scC1View &Add(const Pixel16scC1 &nConstant, int nScaleFactor, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiMulC_16sc_C1RSfs_Ctx(const Npp16sc * pSrc1, int nSrc1Step, const Npp16sc nConstant, Npp16sc * pDst, int nDstStep, NppiSize oSizeROI, int nScaleFactor, NppStreamContext nppStreamCtx)
    Image16scC1View &Mul(const Pixel16scC1 &nConstant, Image16scC1View &pDst, int nScaleFactor, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiMulC_16sc_C1IRSfs_Ctx(const Npp16sc nConstant, Npp16sc * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, int nScaleFactor, NppStreamContext nppStreamCtx)
    Image16scC1View &Mul(const Pixel16scC1 &nConstant, int nScaleFactor, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiSubC_16sc_C1RSfs_Ctx(const Npp16sc * pSrc1, int nSrc1Step, const Npp16sc nConstant, Npp16sc * pDst, int nDstStep, NppiSize oSizeROI, int nScaleFactor, NppStreamContext nppStreamCtx)
    Image16scC1View &Sub(const Pixel16scC1 &nConstant, Image16scC1View &pDst, int nScaleFactor, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiSubC_16sc_C1IRSfs_Ctx(const Npp16sc nConstant, Npp16sc * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, int nScaleFactor, NppStreamContext nppStreamCtx)
    Image16scC1View &Sub(const Pixel16scC1 &nConstant, int nScaleFactor, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiDivC_16sc_C1RSfs_Ctx(const Npp16sc * pSrc1, int nSrc1Step, const Npp16sc nConstant, Npp16sc * pDst, int nDstStep, NppiSize oSizeROI, int nScaleFactor, NppStreamContext nppStreamCtx)
    Image16scC1View &Div(const Pixel16scC1 &nConstant, Image16scC1View &pDst, int nScaleFactor, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiDivC_16sc_C1IRSfs_Ctx(const Npp16sc nConstant, Npp16sc * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, int nScaleFactor, NppStreamContext nppStreamCtx)
    Image16scC1View &Div(const Pixel16scC1 &nConstant, int nScaleFactor, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiAdd_16sc_C1RSfs_Ctx(const Npp16sc * pSrc1, int nSrc1Step, const Npp16sc * pSrc2, int nSrc2Step, Npp16sc * pDst, int nDstStep, NppiSize oSizeROI, int nScaleFactor, NppStreamContext nppStreamCtx)
    Image16scC1View &Add(const Image16scC1View &pSrc2, Image16scC1View &pDst, int nScaleFactor, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiAdd_16sc_C1IRSfs_Ctx(const Npp16sc * pSrc, int nSrcStep, Npp16sc * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, int nScaleFactor, NppStreamContext nppStreamCtx)
    Image16scC1View &Add(const Image16scC1View &pSrc, int nScaleFactor, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiMul_16sc_C1RSfs_Ctx(const Npp16sc * pSrc1, int nSrc1Step, const Npp16sc * pSrc2, int nSrc2Step, Npp16sc * pDst, int nDstStep, NppiSize oSizeROI, int nScaleFactor, NppStreamContext nppStreamCtx)
    Image16scC1View &Mul(const Image16scC1View &pSrc2, Image16scC1View &pDst, int nScaleFactor, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiMul_16sc_C1IRSfs_Ctx(const Npp16sc * pSrc, int nSrcStep, Npp16sc * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, int nScaleFactor, NppStreamContext nppStreamCtx)
    Image16scC1View &Mul(const Image16scC1View &pSrc, int nScaleFactor, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiSub_16sc_C1RSfs_Ctx(const Npp16sc * pSrc1, int nSrc1Step, const Npp16sc * pSrc2, int nSrc2Step, Npp16sc * pDst, int nDstStep, NppiSize oSizeROI, int nScaleFactor, NppStreamContext nppStreamCtx)
    Image16scC1View &Sub(const Image16scC1View &pSrc2, Image16scC1View &pDst, int nScaleFactor, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiSub_16sc_C1IRSfs_Ctx(const Npp16sc * pSrc, int nSrcStep, Npp16sc * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, int nScaleFactor, NppStreamContext nppStreamCtx)
    Image16scC1View &Sub(const Image16scC1View &pSrc, int nScaleFactor, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiDiv_16sc_C1RSfs_Ctx(const Npp16sc * pSrc1, int nSrc1Step, const Npp16sc * pSrc2, int nSrc2Step, Npp16sc * pDst, int nDstStep, NppiSize oSizeROI, int nScaleFactor, NppStreamContext nppStreamCtx)
    Image16scC1View &Div(const Image16scC1View &pSrc2, Image16scC1View &pDst, int nScaleFactor, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiDiv_16sc_C1IRSfs_Ctx(const Npp16sc * pSrc, int nSrcStep, Npp16sc * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, int nScaleFactor, NppStreamContext nppStreamCtx)
    Image16scC1View &Div(const Image16scC1View &pSrc, int nScaleFactor, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiMaximumError_16sc_C1R_Ctx(const Npp16sc * pSrc1, int nSrc1Step, const Npp16sc * pSrc2, int nSrc2Step, NppiSize oSizeROI, Npp64f * pError, Npp8u * pDeviceBuffer, NppStreamContext nppStreamCtx)
    void MaximumError(const Image16scC1View &pSrc2, cuda::DevVarView<double> &pError, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiMaximumErrorGetBufferHostSize_16sc_C1R_Ctx(NppiSize oSizeROI, size_t * hpBufferSize, NppStreamContext nppStreamCtx)
    [[nodiscard]] size_t MaximumErrorGetBufferHostSize(const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiAverageError_16sc_C1R_Ctx(const Npp16sc * pSrc1, int nSrc1Step, const Npp16sc * pSrc2, int nSrc2Step, NppiSize oSizeROI, Npp64f * pError, Npp8u * pDeviceBuffer, NppStreamContext nppStreamCtx)
    void AverageError(const Image16scC1View &pSrc2, cuda::DevVarView<double> &pError, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiAverageErrorGetBufferHostSize_16sc_C1R_Ctx(NppiSize oSizeROI, size_t * hpBufferSize, NppStreamContext nppStreamCtx)
    [[nodiscard]] size_t AverageErrorGetBufferHostSize(const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiMaximumRelativeError_16sc_C1R_Ctx(const Npp16sc * pSrc1, int nSrc1Step, const Npp16sc * pSrc2, int nSrc2Step, NppiSize oSizeROI, Npp64f * pError, Npp8u * pDeviceBuffer, NppStreamContext nppStreamCtx)
    void MaximumRelativeError(const Image16scC1View &pSrc2, cuda::DevVarView<double> &pError, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiMaximumRelativeErrorGetBufferHostSize_16sc_C1R_Ctx(NppiSize oSizeROI, size_t * hpBufferSize, NppStreamContext nppStreamCtx)
    [[nodiscard]] size_t MaximumRelativeErrorGetBufferHostSize(const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiAverageRelativeError_16sc_C1R_Ctx(const Npp16sc * pSrc1, int nSrc1Step, const Npp16sc * pSrc2, int nSrc2Step, NppiSize oSizeROI, Npp64f * pError, Npp8u * pDeviceBuffer, NppStreamContext nppStreamCtx)
    void AverageRelativeError(const Image16scC1View &pSrc2, cuda::DevVarView<double> &pError, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiAverageRelativeErrorGetBufferHostSize_16sc_C1R_Ctx(NppiSize oSizeROI, size_t * hpBufferSize, NppStreamContext nppStreamCtx)
    [[nodiscard]] size_t AverageRelativeErrorGetBufferHostSize(const NppStreamContext &nppStreamCtx) const;

#endif // OPPi_ENABLE_COMPLEX_INT16_TYPE && OPPi_ENABLE_ONE_CHANNEL
    //NOLINTEND(readability-identifier-naming,readability-avoid-const-params-in-decls, bugprone-easily-swappable-parameters, readability-convert-member-functions-to-static)
};
} // namespace opp::image::npp
#endif // OPP_ENABLE_NPP_BACKEND
