// Code automatically generated by nppCodeGenerator - do not modify manually

#pragma once
#include <common/moduleEnabler.h>
#if OPP_ENABLE_NPP_BACKEND
#include <common/image/pixelTypeEnabler.h>

#include "imageView.h"
#include <backends/cuda/devVarView.h>
#include <backends/npp/nppException.h>
#include <common/image/pixelTypes.h>
#include <common/image/roi.h>
#include <common/image/roiException.h>
#include <common/image/size2D.h>
#include <common/image/sizePitched.h>

namespace opp::image::npp
{
// forward declaration:

class Image32uC3View : public ImageView<Pixel32uC3>
{
  protected:
    Image32uC3View() = default;
    explicit Image32uC3View(const Size2D &aSize);

  public:
    Image32uC3View(Pixel32uC3 *aBasePointer, const SizePitched &aSizeAlloc);
    Image32uC3View(Pixel32uC3 *aBasePointer, const SizePitched &aSizeAlloc, const Roi &aRoi);
    ~Image32uC3View() = default;

    Image32uC3View(const Image32uC3View &)     = default;
    Image32uC3View(Image32uC3View &&) noexcept = default;

    Image32uC3View &operator=(const Image32uC3View &)     = default;
    Image32uC3View &operator=(Image32uC3View &&) noexcept = default;

    /// <summary>
    /// Returns a new Image32uC3View with the new ROI
    /// </summary>
    [[nodiscard]] Image32uC3View GetView(const Roi &aRoi) const;

    /// <summary>
    /// Returns a new ImageView with the current ROI adapted by aBorder
    /// </summary>
    [[nodiscard]] Image32uC3View GetView(const Border &aBorder = Border()) const;

    //NOLINTBEGIN(readability-identifier-naming,readability-avoid-const-params-in-decls, bugprone-easily-swappable-parameters, readability-convert-member-functions-to-static)
#if OPPi_ENABLE_UINT32_TYPE && OPPi_ENABLE_THREE_CHANNEL

    // NppStatus nppiSet_32u_C3R_Ctx(const Npp32u[3] aValue, Npp32u * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image32uC3View &Set(const Pixel32uC3 &aValue, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiFloodFill_32u_C3IR_Ctx(Npp32u * pSrcDst, int nSrcDstStep, NppiPoint oSeed, const Npp32u[3] aNewValues, NppiNorm eNorm, NppiSize oSizeROI, NppiConnectedRegion * pConnectedRegion, Npp8u * pBuffer, NppStreamContext nppStreamCtx)
    Image32uC3View &FloodFill(NppiPoint oSeed, const Pixel32uC3 &aNewValues, NppiNorm eNorm, NppiConnectedRegion *pConnectedRegion, opp::cuda::DevVarView<byte> &pBuffer, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiFloodFillBoundary_32u_C3IR_Ctx(Npp32u * pSrcDst, int nSrcDstStep, NppiPoint oSeed, const Npp32u[3] aNewValues, const Npp32u[3] aBoundaryValues, NppiNorm eNorm, NppiSize oSizeROI, NppiConnectedRegion * pConnectedRegion, Npp8u * pBuffer, NppStreamContext nppStreamCtx)
    Image32uC3View &FloodFillBoundary(NppiPoint oSeed, const Pixel32uC3 &aNewValues, const Pixel32uC3 &aBoundaryValues, NppiNorm eNorm, NppiConnectedRegion *pConnectedRegion, opp::cuda::DevVarView<byte> &pBuffer, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiFloodFillRange_32u_C3IR_Ctx(Npp32u * pSrcDst, int nSrcDstStep, NppiPoint oSeed, Npp32u[3] aMin, Npp32u[3] aMax, const Npp32u[3] aNewValues, NppiNorm eNorm, NppiSize oSizeROI, NppiConnectedRegion * pConnectedRegion, Npp8u * pBuffer, NppStreamContext nppStreamCtx)
    Image32uC3View &FloodFillRange(NppiPoint oSeed, Pixel32uC3 &aMin, Pixel32uC3 &aMax, const Pixel32uC3 &aNewValues, NppiNorm eNorm, NppiConnectedRegion *pConnectedRegion, opp::cuda::DevVarView<byte> &pBuffer, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiFloodFillRangeBoundary_32u_C3IR_Ctx(Npp32u * pSrcDst, int nSrcDstStep, NppiPoint oSeed, Npp32u[3] aMin, Npp32u[3] aMax, const Npp32u[3] aNewValues, const Npp32u[3] aBoundaryValues, NppiNorm eNorm, NppiSize oSizeROI, NppiConnectedRegion * pConnectedRegion, Npp8u * pBuffer, NppStreamContext nppStreamCtx)
    Image32uC3View &FloodFillRangeBoundary(NppiPoint oSeed, Pixel32uC3 &aMin, Pixel32uC3 &aMax, const Pixel32uC3 &aNewValues, const Pixel32uC3 &aBoundaryValues, NppiNorm eNorm, NppiConnectedRegion *pConnectedRegion, opp::cuda::DevVarView<byte> &pBuffer, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiFloodFillGradient_32u_C3IR_Ctx(Npp32u * pSrcDst, int nSrcDstStep, NppiPoint oSeed, Npp32u[3] aMin, Npp32u[3] aMax, const Npp32u[3] aNewValues, NppiNorm eNorm, NppiSize oSizeROI, NppiConnectedRegion * pConnectedRegion, Npp8u * pBuffer, NppStreamContext nppStreamCtx)
    Image32uC3View &FloodFillGradient(NppiPoint oSeed, Pixel32uC3 &aMin, Pixel32uC3 &aMax, const Pixel32uC3 &aNewValues, NppiNorm eNorm, NppiConnectedRegion *pConnectedRegion, opp::cuda::DevVarView<byte> &pBuffer, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiFloodFillGradientBoundary_32u_C3IR_Ctx(Npp32u * pSrcDst, int nSrcDstStep, NppiPoint oSeed, Npp32u[3] aMin, Npp32u[3] aMax, const Npp32u[3] aNewValues, const Npp32u[3] aBoundaryValues, NppiNorm eNorm, NppiSize oSizeROI, NppiConnectedRegion * pConnectedRegion, Npp8u * pBuffer, NppStreamContext nppStreamCtx)
    Image32uC3View &FloodFillGradientBoundary(NppiPoint oSeed, Pixel32uC3 &aMin, Pixel32uC3 &aMax, const Pixel32uC3 &aNewValues, const Pixel32uC3 &aBoundaryValues, NppiNorm eNorm, NppiConnectedRegion *pConnectedRegion, opp::cuda::DevVarView<byte> &pBuffer, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiDotProd_32u64f_C3R_Ctx(const Npp32u * pSrc1, int nSrc1Step, const Npp32u * pSrc2, int nSrc2Step, NppiSize oSizeROI, Npp64f[3] aDp, Npp8u * pDeviceBuffer, NppStreamContext nppStreamCtx)
    void DotProd(const Image32uC3View &pSrc2, opp::cuda::DevVarView<double> &aDp, opp::cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiDotProdGetBufferHostSize_32u64f_C3R_Ctx(NppiSize oSizeROI, size_t * hpBufferSize, NppStreamContext nppStreamCtx)
    [[nodiscard]] size_t DotProdGetBufferHostSize(const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiMaximumError_32u_C3R_Ctx(const Npp32u * pSrc1, int nSrc1Step, const Npp32u * pSrc2, int nSrc2Step, NppiSize oSizeROI, Npp64f * pError, Npp8u * pDeviceBuffer, NppStreamContext nppStreamCtx)
    void MaximumError(const Image32uC3View &pSrc2, opp::cuda::DevVarView<double> &pError, opp::cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiMaximumErrorGetBufferHostSize_32u_C3R_Ctx(NppiSize oSizeROI, size_t * hpBufferSize, NppStreamContext nppStreamCtx)
    [[nodiscard]] size_t MaximumErrorGetBufferHostSize(const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiAverageError_32u_C3R_Ctx(const Npp32u * pSrc1, int nSrc1Step, const Npp32u * pSrc2, int nSrc2Step, NppiSize oSizeROI, Npp64f * pError, Npp8u * pDeviceBuffer, NppStreamContext nppStreamCtx)
    void AverageError(const Image32uC3View &pSrc2, opp::cuda::DevVarView<double> &pError, opp::cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiAverageErrorGetBufferHostSize_32u_C3R_Ctx(NppiSize oSizeROI, size_t * hpBufferSize, NppStreamContext nppStreamCtx)
    [[nodiscard]] size_t AverageErrorGetBufferHostSize(const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiMaximumRelativeError_32u_C3R_Ctx(const Npp32u * pSrc1, int nSrc1Step, const Npp32u * pSrc2, int nSrc2Step, NppiSize oSizeROI, Npp64f * pError, Npp8u * pDeviceBuffer, NppStreamContext nppStreamCtx)
    void MaximumRelativeError(const Image32uC3View &pSrc2, opp::cuda::DevVarView<double> &pError, opp::cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiMaximumRelativeErrorGetBufferHostSize_32u_C3R_Ctx(NppiSize oSizeROI, size_t * hpBufferSize, NppStreamContext nppStreamCtx)
    [[nodiscard]] size_t MaximumRelativeErrorGetBufferHostSize(const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiAverageRelativeError_32u_C3R_Ctx(const Npp32u * pSrc1, int nSrc1Step, const Npp32u * pSrc2, int nSrc2Step, NppiSize oSizeROI, Npp64f * pError, Npp8u * pDeviceBuffer, NppStreamContext nppStreamCtx)
    void AverageRelativeError(const Image32uC3View &pSrc2, opp::cuda::DevVarView<double> &pError, opp::cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiAverageRelativeErrorGetBufferHostSize_32u_C3R_Ctx(NppiSize oSizeROI, size_t * hpBufferSize, NppStreamContext nppStreamCtx)
    [[nodiscard]] size_t AverageRelativeErrorGetBufferHostSize(const NppStreamContext &nppStreamCtx) const;

#endif // OPPi_ENABLE_UINT32_TYPE && OPPi_ENABLE_THREE_CHANNEL
    //NOLINTEND(readability-identifier-naming,readability-avoid-const-params-in-decls, bugprone-easily-swappable-parameters, readability-convert-member-functions-to-static)
};
} // namespace opp::image::npp
#endif // OPP_ENABLE_NPP_BACKEND
