// Code automatically generated by nppCodeGenerator - do not modify manually

#pragma once
#include <common/moduleEnabler.h>
#if OPP_ENABLE_NPP_BACKEND
#include <common/image/pixelTypeEnabler.h>

#include "imageView.h"
#include <backends/cuda/devVarView.h>
#include <backends/npp/nppException.h>
#include <common/image/pixelTypes.h>
#include <common/image/roi.h>
#include <common/image/roiException.h>
#include <common/image/size2D.h>
#include <common/image/sizePitched.h>

namespace opp::image::npp
{
// forward declaration:
class Image32fC1View;

class Image16fC1View : public ImageView<Pixel16fC1>
{
  protected:
    Image16fC1View() = default;
    explicit Image16fC1View(const Size2D &aSize);

  public:
    Image16fC1View(Pixel16fC1 *aBasePointer, const SizePitched &aSizeAlloc);
    Image16fC1View(Pixel16fC1 *aBasePointer, const SizePitched &aSizeAlloc, const Roi &aRoi);
    ~Image16fC1View() = default;

    Image16fC1View(const Image16fC1View &)     = default;
    Image16fC1View(Image16fC1View &&) noexcept = default;

    Image16fC1View &operator=(const Image16fC1View &)     = default;
    Image16fC1View &operator=(Image16fC1View &&) noexcept = default;

    /// <summary>
    /// Returns a new Image16fC1View with the new ROI
    /// </summary>
    [[nodiscard]] Image16fC1View GetView(const Roi &aRoi);

    /// <summary>
    /// Returns a new ImageView with the current ROI adapted by aBorder
    /// </summary>
    [[nodiscard]] Image16fC1View GetView(const Border &aBorder = Border());

    //NOLINTBEGIN(readability-identifier-naming,readability-avoid-const-params-in-decls, bugprone-easily-swappable-parameters, readability-convert-member-functions-to-static)
#if OPPi_ENABLE_HALFFLOAT16_TYPE && OPPi_ENABLE_ONE_CHANNEL

    // NppStatus nppiSet_16f_C1R_Ctx(const Npp32f nValue, Npp16f * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC1View &Set(const Pixel32fC1 &nValue, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiCopy_16f_C1R_Ctx(const Npp16f * pSrc, int nSrcStep, Npp16f * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC1View &Copy(Image16fC1View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiConvert_16f32f_C1R_Ctx(const Npp16f * pSrc, int nSrcStep, Npp32f * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image32fC1View &Convert(Image32fC1View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiAddC_16f_C1R_Ctx(const Npp16f * pSrc1, int nSrc1Step, const Npp32f nConstant, Npp16f * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC1View &Add(const Pixel32fC1 &nConstant, Image16fC1View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiAddDeviceC_16f_C1R_Ctx(const Npp16f * pSrc1, int nSrc1Step, const Npp32f * pConstant, Npp16f * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC1View &Add(const opp::cuda::DevVarView<Pixel8uC1> &pConstant, Image16fC1View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiAddC_16f_C1IR_Ctx(const Npp32f nConstant, Npp16f * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC1View &Add(const Pixel32fC1 &nConstant, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiAddDeviceC_16f_C1IR_Ctx(const Npp32f * pConstant, Npp16f * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC1View &Add(const opp::cuda::DevVarView<Pixel8uC1> &pConstant, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiMulC_16f_C1R_Ctx(const Npp16f * pSrc1, int nSrc1Step, const Npp32f nConstant, Npp16f * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC1View &Mul(const Pixel32fC1 &nConstant, Image16fC1View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiMulDeviceC_16f_C1R_Ctx(const Npp16f * pSrc1, int nSrc1Step, const Npp32f * pConstant, Npp16f * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC1View &Mul(const opp::cuda::DevVarView<Pixel8uC1> &pConstant, Image16fC1View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiMulC_16f_C1IR_Ctx(const Npp32f nConstant, Npp16f * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC1View &Mul(const Pixel32fC1 &nConstant, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiMulDeviceC_16f_C1IR_Ctx(const Npp32f * pConstant, Npp16f * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC1View &Mul(const opp::cuda::DevVarView<Pixel8uC1> &pConstant, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiSubC_16f_C1R_Ctx(const Npp16f * pSrc1, int nSrc1Step, const Npp32f nConstant, Npp16f * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC1View &Sub(const Pixel32fC1 &nConstant, Image16fC1View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiSubDeviceC_16f_C1R_Ctx(const Npp16f * pSrc1, int nSrc1Step, const Npp32f * pConstant, Npp16f * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC1View &Sub(const opp::cuda::DevVarView<Pixel8uC1> &pConstant, Image16fC1View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiSubC_16f_C1IR_Ctx(const Npp32f nConstant, Npp16f * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC1View &Sub(const Pixel32fC1 &nConstant, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiSubDeviceC_16f_C1IR_Ctx(const Npp32f * pConstant, Npp16f * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC1View &Sub(const opp::cuda::DevVarView<Pixel8uC1> &pConstant, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiDivC_16f_C1R_Ctx(const Npp16f * pSrc1, int nSrc1Step, const Npp32f nConstant, Npp16f * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC1View &Div(const Pixel32fC1 &nConstant, Image16fC1View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiDivDeviceC_16f_C1R_Ctx(const Npp16f * pSrc1, int nSrc1Step, const Npp32f * pConstant, Npp16f * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC1View &Div(const opp::cuda::DevVarView<Pixel8uC1> &pConstant, Image16fC1View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiDivC_16f_C1IR_Ctx(const Npp32f nConstant, Npp16f * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC1View &Div(const Pixel32fC1 &nConstant, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiDivDeviceC_16f_C1IR_Ctx(const Npp32f * pConstant, Npp16f * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC1View &Div(const opp::cuda::DevVarView<Pixel8uC1> &pConstant, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiAdd_16f_C1R_Ctx(const Npp16f * pSrc1, int nSrc1Step, const Npp16f * pSrc2, int nSrc2Step, Npp16f * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC1View &Add(const Image16fC1View &pSrc2, Image16fC1View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiAdd_16f_C1IR_Ctx(const Npp16f * pSrc, int nSrcStep, Npp16f * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC1View &Add(const Image16fC1View &pSrc, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiAddProduct_16f_C1IR_Ctx(const Npp16f * pSrc1, int nSrc1Step, const Npp16f * pSrc2, int nSrc2Step, Npp16f * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC1View &AddProduct(const Image16fC1View &pSrc1, const Image16fC1View &pSrc2, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiMul_16f_C1R_Ctx(const Npp16f * pSrc1, int nSrc1Step, const Npp16f * pSrc2, int nSrc2Step, Npp16f * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC1View &Mul(const Image16fC1View &pSrc2, Image16fC1View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiMul_16f_C1IR_Ctx(const Npp16f * pSrc, int nSrcStep, Npp16f * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC1View &Mul(const Image16fC1View &pSrc, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiSub_16f_C1R_Ctx(const Npp16f * pSrc1, int nSrc1Step, const Npp16f * pSrc2, int nSrc2Step, Npp16f * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC1View &Sub(const Image16fC1View &pSrc2, Image16fC1View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiSub_16f_C1IR_Ctx(const Npp16f * pSrc, int nSrcStep, Npp16f * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC1View &Sub(const Image16fC1View &pSrc, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiDiv_16f_C1R_Ctx(const Npp16f * pSrc1, int nSrc1Step, const Npp16f * pSrc2, int nSrc2Step, Npp16f * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC1View &Div(const Image16fC1View &pSrc2, Image16fC1View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiDiv_16f_C1IR_Ctx(const Npp16f * pSrc, int nSrcStep, Npp16f * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC1View &Div(const Image16fC1View &pSrc, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiAbs_16f_C1R_Ctx(const Npp16f * pSrc, int nSrcStep, Npp16f * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC1View &Abs(Image16fC1View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiAbs_16f_C1IR_Ctx(Npp16f * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC1View &Abs(const NppStreamContext &nppStreamCtx);

    // NppStatus nppiAbsDiff_16f_C1R_Ctx(const Npp16f * pSrc1, int nSrc1Step, const Npp16f * pSrc2, int nSrc2Step, Npp16f * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC1View &AbsDiff(const Image16fC1View &pSrc2, Image16fC1View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiSqr_16f_C1R_Ctx(const Npp16f * pSrc, int nSrcStep, Npp16f * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC1View &Sqr(Image16fC1View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiSqr_16f_C1IR_Ctx(Npp16f * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC1View &Sqr(const NppStreamContext &nppStreamCtx);

    // NppStatus nppiSqrt_16f_C1R_Ctx(const Npp16f * pSrc, int nSrcStep, Npp16f * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC1View &Sqrt(Image16fC1View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiSqrt_16f_C1IR_Ctx(Npp16f * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC1View &Sqrt(const NppStreamContext &nppStreamCtx);

    // NppStatus nppiLn_16f_C1R_Ctx(const Npp16f * pSrc, int nSrcStep, Npp16f * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC1View &Ln(Image16fC1View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiLn_16f_C1IR_Ctx(Npp16f * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC1View &Ln(const NppStreamContext &nppStreamCtx);

    // NppStatus nppiColorTwist32f_16f_C1R_Ctx(const Npp16f * pSrc, int nSrcStep, Npp16f * pDst, int nDstStep, NppiSize oSizeROI, const Npp32f[3][4] aTwist, NppStreamContext nppStreamCtx)
    Image16fC1View &ColorTwist32f(Image16fC1View &pDst, const Npp32f aTwist[3][4], const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiColorTwist32f_16f_C1IR_Ctx(Npp16f * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, const Npp32f[3][4] aTwist, NppStreamContext nppStreamCtx)
    Image16fC1View &ColorTwist32f(const Npp32f aTwist[3][4], const NppStreamContext &nppStreamCtx);

    // NppStatus nppiFilter32f_16f_C1R_Ctx(const Npp16f * pSrc, int nSrcStep, Npp16f * pDst, int nDstStep, NppiSize oSizeROI, const Npp32f * pKernel, NppiSize oKernelSize, NppiPoint oAnchor, NppStreamContext nppStreamCtx)
    Image16fC1View &Filter32f(Image16fC1View &pDst, const opp::cuda::DevVarView<float> &pKernel, NppiSize oKernelSize, NppiPoint oAnchor, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiFilterBorder32f_16f_C1R_Ctx(const Npp16f * pSrc, int nSrcStep, NppiSize oSrcSize, NppiPoint oSrcOffset, Npp16f * pDst, int nDstStep, NppiSize oSizeROI, const Npp32f * pKernel, NppiSize oKernelSize, NppiPoint oAnchor, NppiBorderType eBorderType, NppStreamContext nppStreamCtx)
    Image16fC1View &FilterBorder32f(Image16fC1View &pDst, const opp::cuda::DevVarView<float> &pKernel, NppiSize oKernelSize, NppiPoint oAnchor, NppiBorderType eBorderType, const NppStreamContext &nppStreamCtx, const Roi &aFilterArea = Roi()) const;

    // NppStatus nppiResize_16f_C1R_Ctx(const Npp16f * pSrc, int nSrcStep, NppiSize oSrcSize, NppiRect oSrcRectROI, Npp16f * pDst, int nDstStep, NppiSize oDstSize, NppiRect oDstRectROI, int eInterpolation, NppStreamContext nppStreamCtx)
    Image16fC1View &Resize(Image16fC1View &pDst, int eInterpolation, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiWarpAffine_16f_C1R_Ctx(const Npp16f * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, Npp16f * pDst, int nDstStep, NppiRect oDstROI, const double[2][3] aCoeffs, int eInterpolation, NppStreamContext nppStreamCtx)
    Image16fC1View &WarpAffine(Image16fC1View &pDst, const AffineTransformation<double> &aCoeffs, int eInterpolation, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiWarpPerspective_16f_C1R_Ctx(const Npp16f * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, Npp16f * pDst, int nDstStep, NppiRect oDstROI, const double[3][3] aCoeffs, int eInterpolation, NppStreamContext nppStreamCtx)
    Image16fC1View &WarpPerspective(Image16fC1View &pDst, const PerspectiveTransformation<double> &aCoeffs, int eInterpolation, const NppStreamContext &nppStreamCtx) const;

#endif // OPPi_ENABLE_HALFFLOAT16_TYPE && OPPi_ENABLE_ONE_CHANNEL
    //NOLINTEND(readability-identifier-naming,readability-avoid-const-params-in-decls, bugprone-easily-swappable-parameters, readability-convert-member-functions-to-static)
};
} // namespace opp::image::npp
#endif // OPP_ENABLE_NPP_BACKEND
