// Code automatically generated by nppCodeGenerator - do not modify manually

#include "image16fC2View.h" //NOLINT
#ifdef _MSC_VER
#include "../dllexport_npp.h"
#endif
#include "imageView.h"  //NOLINT
#include <backends/cuda/devVarView.h> //NOLINT
#include <backends/npp/nppException.h>  //NOLINT
#include <common/defines.h> //NOLINT
#include <common/exception.h> //NOLINT
#include <common/image/affineTransformation.h> //NOLINT
#include <common/image/border.h> //NOLINT
#include <common/image/bound.h> //NOLINT
#include <common/image/matrix.h> //NOLINT
#include <common/image/pixelTypes.h> //NOLINT
#include <common/image/quad.h> //NOLINT
#include <common/image/roi.h> //NOLINT
#include <common/image/roiException.h>  //NOLINT
#include <common/image/size2D.h>  //NOLINT
#include <common/image/sizePitched.h>  //NOLINT
#include <common/safeCast.h>  //NOLINT
#include <cstddef> //NOLINT
#include <nppdefs.h>  //NOLINT
#include <nppi_color_conversion.h> //NOLINT
#include <nppi_data_exchange_and_initialization.h> //NOLINT

namespace mpp::image::npp
{
#ifdef _MSC_VER
template class MPPEXPORT_NPP ImageView<Pixel16fC2>;
#endif

Image16fC2View::Image16fC2View(const Size2D &aSize) : ImageView<Pixel16fC2>(aSize)
{
}

Image16fC2View::Image16fC2View(Pixel16fC2 *aBasePointer, const SizePitched &aSizeAlloc)
    : ImageView<Pixel16fC2>(aBasePointer, aSizeAlloc)
{
}
Image16fC2View::Image16fC2View(Pixel16fC2 *aBasePointer, const SizePitched &aSizeAlloc, const Roi &aRoi)
    : ImageView<Pixel16fC2>(aBasePointer, aSizeAlloc, aRoi)
{
}

Image16fC2View Image16fC2View::GetView(const Roi &aRoi)
{
    return {Pointer(), SizePitched(SizeAlloc(), Pitch()), aRoi};
}

Image16fC2View Image16fC2View::GetView(const Border &aBorder)
{
    const Roi newRoi = ROI() + aBorder;
    checkRoiIsInRoi(newRoi, Roi(0, 0, SizeAlloc()));
    return {Pointer(), SizePitched(SizeAlloc(), Pitch()), newRoi};
}

//NOLINTBEGIN(readability-identifier-naming,readability-avoid-const-params-in-decls, bugprone-easily-swappable-parameters, readability-convert-member-functions-to-static)

Image16fC2View &Image16fC2View::Set(const Pixel32fC2 &aValues, const NppStreamContext &nppStreamCtx)
{
    nppSafeCallExt(nppiSet_16f_C2R_Ctx(aValues.data(), reinterpret_cast<Npp16f *>(PointerRoi()), to_int(Pitch()), NppiSizeRoi(), nppStreamCtx),
                   "ROI SrcDst: " << ROI());
    return *this;
}

Image16fC2View &Image16fC2View::ColorTwist32f(Image16fC2View &pDst, const Npp32f aTwist[3][4], const NppStreamContext &nppStreamCtx) const
{
    checkSameSize(ROI(), pDst.ROI());
    nppSafeCallExt(nppiColorTwist32f_16f_C2R_Ctx(reinterpret_cast<const Npp16f *>(PointerRoi()), to_int(Pitch()), reinterpret_cast<Npp16f *>(pDst.PointerRoi()), to_int(pDst.Pitch()), NppiSizeRoi(), aTwist, nppStreamCtx),
                   "ROI Src: " << ROI() << "ROI Dst: " << pDst.ROI());
    return pDst;
}

Image16fC2View &Image16fC2View::ColorTwist32f(const Npp32f aTwist[3][4], const NppStreamContext &nppStreamCtx)
{
    nppSafeCallExt(nppiColorTwist32f_16f_C2IR_Ctx(reinterpret_cast<Npp16f *>(PointerRoi()), to_int(Pitch()), NppiSizeRoi(), aTwist, nppStreamCtx),
                   "ROI SrcDst: " << ROI());
    return *this;
}

//NOLINTEND(readability-identifier-naming,readability-avoid-const-params-in-decls, bugprone-easily-swappable-parameters, readability-convert-member-functions-to-static)
} // namespace mpp::image::npp
