// Code automatically generated by nppCodeGenerator - do not modify manually

#pragma once

#include "imageView.h"
#include <backends/cuda/devVarView.h>
#include <backends/npp/nppException.h>
#include <common/image/pixelTypes.h>
#include <common/image/roi.h>
#include <common/image/roiException.h>
#include <common/image/size2D.h>
#include <common/image/sizePitched.h>

namespace opp::image::npp
{
// forward declaration:
class Image32sC1View;
class Image32sC3View;
class Image8sC4View;
class Image8uC1View;
class Image8uC4View;

class Image32sC4View : public ImageView<Pixel32sC4>
{
  protected:
    Image32sC4View() = default;
    explicit Image32sC4View(const Size2D &aSize);

  public:
    Image32sC4View(Pixel32sC4 *aBasePointer, const SizePitched &aSizeAlloc);
    Image32sC4View(Pixel32sC4 *aBasePointer, const SizePitched &aSizeAlloc, const Roi &aRoi);
    ~Image32sC4View() = default;

    Image32sC4View(const Image32sC4View &)     = default;
    Image32sC4View(Image32sC4View &&) noexcept = default;

    Image32sC4View &operator=(const Image32sC4View &)     = default;
    Image32sC4View &operator=(Image32sC4View &&) noexcept = default;

    /// <summary>
    /// Returns a new Image32sC4View with the new ROI
    /// </summary>
    [[nodiscard]] Image32sC4View GetView(const Roi &aRoi) const;

    /// <summary>
    /// Returns a new ImageView with the current ROI adapted by aBorder
    /// </summary>
    [[nodiscard]] Image32sC4View GetView(const Border &aBorder = Border()) const;

    //NOLINTBEGIN(readability-identifier-naming,readability-avoid-const-params-in-decls, bugprone-easily-swappable-parameters, readability-convert-member-functions-to-static)


    // NppStatus nppiSet_32s_C4R_Ctx(const Npp32s[4] aValue, Npp32s * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    void Set(const Pixel32sC4 &aValue, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiSet_32s_AC4R_Ctx(const Npp32s[3] aValue, Npp32s * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    void SetA(const Pixel32sC3 &aValue, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiSet_32s_C4MR_Ctx(const Npp32s[4] aValue, Npp32s * pDst, int nDstStep, NppiSize oSizeROI, const Npp8u * pMask, int nMaskStep, NppStreamContext nppStreamCtx)
    void Set(const Pixel32sC4 &aValue, const Image8uC1View &pMask, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiSet_32s_AC4MR_Ctx(const Npp32s[3] aValue, Npp32s * pDst, int nDstStep, NppiSize oSizeROI, const Npp8u * pMask, int nMaskStep, NppStreamContext nppStreamCtx)
    void SetA(const Pixel32sC3 &aValue, const Image8uC1View &pMask, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiSet_32s_C4CR_Ctx(Npp32s nValue, Npp32s * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    void Set(size_t aDstChannel, const Pixel32sC1 &nValue, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiCopy_32s_C4R_Ctx(const Npp32s * pSrc, int nSrcStep, Npp32s * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    void Copy(Image32sC4View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiCopy_32s_AC4R_Ctx(const Npp32s * pSrc, int nSrcStep, Npp32s * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    void CopyA(Image32sC4View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiCopy_32s_C4MR_Ctx(const Npp32s * pSrc, int nSrcStep, Npp32s * pDst, int nDstStep, NppiSize oSizeROI, const Npp8u * pMask, int nMaskStep, NppStreamContext nppStreamCtx)
    void Copy(Image32sC4View &pDst, const Image8uC1View &pMask, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiCopy_32s_AC4MR_Ctx(const Npp32s * pSrc, int nSrcStep, Npp32s * pDst, int nDstStep, NppiSize oSizeROI, const Npp8u * pMask, int nMaskStep, NppStreamContext nppStreamCtx)
    void CopyA(Image32sC4View &pDst, const Image8uC1View &pMask, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiCopy_32s_C4CR_Ctx(const Npp32s * pSrc, int nSrcStep, Npp32s * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    void Copy(size_t aSrcChannel, size_t aDstChannel, Image32sC4View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiCopy_32s_C4C1R_Ctx(const Npp32s * pSrc, int nSrcStep, Npp32s * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    void Copy(size_t aSrcChannel, Image32sC1View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiCopy_32s_C4P4R_Ctx(const Npp32s * pSrc, int nSrcStep, Npp32s *const[4] aDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    void Copy(Image32sC1View &aDstChannel0, Image32sC1View &aDstChannel1, Image32sC1View &aDstChannel2, Image32sC1View &aDstChannel3, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiCopy_32s_P4C4R_Ctx(const Npp32s *const[4] aSrc, int nSrcStep, Npp32s * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    static void Copy(const Image32sC1View &aSrcChannel0, const Image32sC1View &aSrcChannel1, const Image32sC1View &aSrcChannel2, const Image32sC1View &aSrcChannel3, Image32sC4View &pDst, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiCopyConstBorder_32s_C4R_Ctx(const Npp32s * pSrc, int nSrcStep, NppiSize oSrcSizeROI, Npp32s * pDst, int nDstStep, NppiSize oDstSizeROI, int nTopBorderHeight, int nLeftBorderWidth, const Npp32s[4] aValue, NppStreamContext nppStreamCtx)
    void CopyConstBorder(Image32sC4View &pDst, int nTopBorderHeight, int nLeftBorderWidth, const Pixel32sC4 &aValue, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiCopyConstBorder_32s_AC4R_Ctx(const Npp32s * pSrc, int nSrcStep, NppiSize oSrcSizeROI, Npp32s * pDst, int nDstStep, NppiSize oDstSizeROI, int nTopBorderHeight, int nLeftBorderWidth, const Npp32s[3] aValue, NppStreamContext nppStreamCtx)
    void CopyConstBorderA(Image32sC4View &pDst, int nTopBorderHeight, int nLeftBorderWidth, const Pixel32sC3 &aValue, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiCopyReplicateBorder_32s_C4R_Ctx(const Npp32s * pSrc, int nSrcStep, NppiSize oSrcSizeROI, Npp32s * pDst, int nDstStep, NppiSize oDstSizeROI, int nTopBorderHeight, int nLeftBorderWidth, NppStreamContext nppStreamCtx)
    void CopyReplicateBorder(Image32sC4View &pDst, int nTopBorderHeight, int nLeftBorderWidth, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiCopyReplicateBorder_32s_AC4R_Ctx(const Npp32s * pSrc, int nSrcStep, NppiSize oSrcSizeROI, Npp32s * pDst, int nDstStep, NppiSize oDstSizeROI, int nTopBorderHeight, int nLeftBorderWidth, NppStreamContext nppStreamCtx)
    void CopyReplicateBorderA(Image32sC4View &pDst, int nTopBorderHeight, int nLeftBorderWidth, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiCopyWrapBorder_32s_C4R_Ctx(const Npp32s * pSrc, int nSrcStep, NppiSize oSrcSizeROI, Npp32s * pDst, int nDstStep, NppiSize oDstSizeROI, int nTopBorderHeight, int nLeftBorderWidth, NppStreamContext nppStreamCtx)
    void CopyWrapBorder(Image32sC4View &pDst, int nTopBorderHeight, int nLeftBorderWidth, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiCopyWrapBorder_32s_AC4R_Ctx(const Npp32s * pSrc, int nSrcStep, NppiSize oSrcSizeROI, Npp32s * pDst, int nDstStep, NppiSize oDstSizeROI, int nTopBorderHeight, int nLeftBorderWidth, NppStreamContext nppStreamCtx)
    void CopyWrapBorderA(Image32sC4View &pDst, int nTopBorderHeight, int nLeftBorderWidth, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiCopySubpix_32s_C4R_Ctx(const Npp32s * pSrc, int nSrcStep, Npp32s * pDst, int nDstStep, NppiSize oDstSizeROI, Npp32f nDx, Npp32f nDy, NppStreamContext nppStreamCtx)
    void CopySubpix(Image32sC4View &pDst, const Pixel32fC1 &nDx, const Pixel32fC1 &nDy, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiCopySubpix_32s_AC4R_Ctx(const Npp32s * pSrc, int nSrcStep, Npp32s * pDst, int nDstStep, NppiSize oDstSizeROI, Npp32f nDx, Npp32f nDy, NppStreamContext nppStreamCtx)
    void CopySubpixA(Image32sC4View &pDst, const Pixel32fC1 &nDx, const Pixel32fC1 &nDy, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiConvert_32s8u_C4R_Ctx(const Npp32s * pSrc, int nSrcStep, Npp8u * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    void Convert(Image8uC4View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiConvert_32s8u_AC4R_Ctx(const Npp32s * pSrc, int nSrcStep, Npp8u * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    void ConvertA(Image8uC4View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiConvert_32s8s_C4R_Ctx(const Npp32s * pSrc, int nSrcStep, Npp8s * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    void Convert(Image8sC4View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiConvert_32s8s_AC4R_Ctx(const Npp32s * pSrc, int nSrcStep, Npp8s * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    void ConvertA(Image8sC4View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiScale_32s8u_C4R_Ctx(const Npp32s * pSrc, int nSrcStep, Npp8u * pDst, int nDstStep, NppiSize oSizeROI, NppHintAlgorithm hint, NppStreamContext nppStreamCtx)
    void Scale(Image8uC4View &pDst, NppHintAlgorithm hint, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiScale_32s8u_AC4R_Ctx(const Npp32s * pSrc, int nSrcStep, Npp8u * pDst, int nDstStep, NppiSize oSizeROI, NppHintAlgorithm hint, NppStreamContext nppStreamCtx)
    void ScaleA(Image8uC4View &pDst, NppHintAlgorithm hint, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiTranspose_32s_C4R_Ctx(const Npp32s * pSrc, int nSrcStep, Npp32s * pDst, int nDstStep, NppiSize oSrcROI, NppStreamContext nppStreamCtx)
    void Transpose(Image32sC4View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiSwapChannels_32s_C4C3R_Ctx(const Npp32s * pSrc, int nSrcStep, Npp32s * pDst, int nDstStep, NppiSize oSizeROI, const int[3] aDstOrder, NppStreamContext nppStreamCtx)
    void SwapChannels(Image32sC3View &pDst, const int aDstOrder[3], const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiSwapChannels_32s_C4R_Ctx(const Npp32s * pSrc, int nSrcStep, Npp32s * pDst, int nDstStep, NppiSize oSizeROI, const int[4] aDstOrder, NppStreamContext nppStreamCtx)
    void SwapChannels(Image32sC4View &pDst, const int aDstOrder[4], const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiSwapChannels_32s_C4IR_Ctx(Npp32s * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, const int[4] aDstOrder, NppStreamContext nppStreamCtx)
    void SwapChannels(const int aDstOrder[4], const NppStreamContext &nppStreamCtx);

    // NppStatus nppiSwapChannels_32s_AC4R_Ctx(const Npp32s * pSrc, int nSrcStep, Npp32s * pDst, int nDstStep, NppiSize oSizeROI, const int[3] aDstOrder, NppStreamContext nppStreamCtx)
    void SwapChannelsA(Image32sC4View &pDst, const int aDstOrder[3], const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiSub_32s_C4RSfs_Ctx(const Npp32s * pSrc1, int nSrc1Step, const Npp32s * pSrc2, int nSrc2Step, Npp32s * pDst, int nDstStep, NppiSize oSizeROI, int nScaleFactor, NppStreamContext nppStreamCtx)
    void Sub(const Image32sC4View &pSrc2, Image32sC4View &pDst, int nScaleFactor, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiSub_32s_C4IRSfs_Ctx(const Npp32s * pSrc, int nSrcStep, Npp32s * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, int nScaleFactor, NppStreamContext nppStreamCtx)
    void Sub(const Image32sC4View &pSrc, int nScaleFactor, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiAndC_32s_AC4R_Ctx(const Npp32s * pSrc1, int nSrc1Step, const Npp32s[3] aConstants, Npp32s * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    void AndA(const Pixel32sC3 &aConstants, Image32sC4View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiAndC_32s_AC4IR_Ctx(const Npp32s[3] aConstants, Npp32s * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    void AndA(const Pixel32sC3 &aConstants, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiAndC_32s_C4R_Ctx(const Npp32s * pSrc1, int nSrc1Step, const Npp32s[4] aConstants, Npp32s * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    void And(const Pixel32sC4 &aConstants, Image32sC4View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiAndC_32s_C4IR_Ctx(const Npp32s[4] aConstants, Npp32s * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    void And(const Pixel32sC4 &aConstants, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiOrC_32s_AC4R_Ctx(const Npp32s * pSrc1, int nSrc1Step, const Npp32s[3] aConstants, Npp32s * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    void OrA(const Pixel32sC3 &aConstants, Image32sC4View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiOrC_32s_AC4IR_Ctx(const Npp32s[3] aConstants, Npp32s * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    void OrA(const Pixel32sC3 &aConstants, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiOrC_32s_C4R_Ctx(const Npp32s * pSrc1, int nSrc1Step, const Npp32s[4] aConstants, Npp32s * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    void Or(const Pixel32sC4 &aConstants, Image32sC4View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiOrC_32s_C4IR_Ctx(const Npp32s[4] aConstants, Npp32s * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    void Or(const Pixel32sC4 &aConstants, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiXorC_32s_AC4R_Ctx(const Npp32s * pSrc1, int nSrc1Step, const Npp32s[3] aConstants, Npp32s * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    void XorA(const Pixel32sC3 &aConstants, Image32sC4View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiXorC_32s_AC4IR_Ctx(const Npp32s[3] aConstants, Npp32s * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    void XorA(const Pixel32sC3 &aConstants, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiXorC_32s_C4R_Ctx(const Npp32s * pSrc1, int nSrc1Step, const Npp32s[4] aConstants, Npp32s * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    void Xor(const Pixel32sC4 &aConstants, Image32sC4View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiXorC_32s_C4IR_Ctx(const Npp32s[4] aConstants, Npp32s * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    void Xor(const Pixel32sC4 &aConstants, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiRShiftC_32s_AC4R_Ctx(const Npp32s * pSrc1, int nSrc1Step, const Npp32u[3] aConstants, Npp32s * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    void RShiftA(const Pixel32uC3 &aConstants, Image32sC4View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiRShiftC_32s_AC4IR_Ctx(const Npp32u[3] aConstants, Npp32s * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    void RShiftA(const Pixel32uC3 &aConstants, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiRShiftC_32s_C4R_Ctx(const Npp32s * pSrc1, int nSrc1Step, const Npp32u[4] aConstants, Npp32s * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    void RShift(const Pixel32uC4 &aConstants, Image32sC4View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiRShiftC_32s_C4IR_Ctx(const Npp32u[4] aConstants, Npp32s * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    void RShift(const Pixel32uC4 &aConstants, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiLShiftC_32s_AC4R_Ctx(const Npp32s * pSrc1, int nSrc1Step, const Npp32u[3] aConstants, Npp32s * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    void LShiftA(const Pixel32uC3 &aConstants, Image32sC4View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiLShiftC_32s_AC4IR_Ctx(const Npp32u[3] aConstants, Npp32s * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    void LShiftA(const Pixel32uC3 &aConstants, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiLShiftC_32s_C4R_Ctx(const Npp32s * pSrc1, int nSrc1Step, const Npp32u[4] aConstants, Npp32s * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    void LShift(const Pixel32uC4 &aConstants, Image32sC4View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiLShiftC_32s_C4IR_Ctx(const Npp32u[4] aConstants, Npp32s * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    void LShift(const Pixel32uC4 &aConstants, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiAnd_32s_AC4R_Ctx(const Npp32s * pSrc1, int nSrc1Step, const Npp32s * pSrc2, int nSrc2Step, Npp32s * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    void AndA(const Image32sC4View &pSrc2, Image32sC4View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiAnd_32s_AC4IR_Ctx(const Npp32s * pSrc, int nSrcStep, Npp32s * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    void AndA(const Image32sC4View &pSrc, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiAnd_32s_C4R_Ctx(const Npp32s * pSrc1, int nSrc1Step, const Npp32s * pSrc2, int nSrc2Step, Npp32s * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    void And(const Image32sC4View &pSrc2, Image32sC4View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiAnd_32s_C4IR_Ctx(const Npp32s * pSrc, int nSrcStep, Npp32s * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    void And(const Image32sC4View &pSrc, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiOr_32s_AC4R_Ctx(const Npp32s * pSrc1, int nSrc1Step, const Npp32s * pSrc2, int nSrc2Step, Npp32s * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    void OrA(const Image32sC4View &pSrc2, Image32sC4View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiOr_32s_AC4IR_Ctx(const Npp32s * pSrc, int nSrcStep, Npp32s * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    void OrA(const Image32sC4View &pSrc, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiOr_32s_C4R_Ctx(const Npp32s * pSrc1, int nSrc1Step, const Npp32s * pSrc2, int nSrc2Step, Npp32s * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    void Or(const Image32sC4View &pSrc2, Image32sC4View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiOr_32s_C4IR_Ctx(const Npp32s * pSrc, int nSrcStep, Npp32s * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    void Or(const Image32sC4View &pSrc, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiXor_32s_AC4R_Ctx(const Npp32s * pSrc1, int nSrc1Step, const Npp32s * pSrc2, int nSrc2Step, Npp32s * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    void XorA(const Image32sC4View &pSrc2, Image32sC4View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiXor_32s_AC4IR_Ctx(const Npp32s * pSrc, int nSrcStep, Npp32s * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    void XorA(const Image32sC4View &pSrc, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiXor_32s_C4R_Ctx(const Npp32s * pSrc1, int nSrc1Step, const Npp32s * pSrc2, int nSrc2Step, Npp32s * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    void Xor(const Image32sC4View &pSrc2, Image32sC4View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiXor_32s_C4IR_Ctx(const Npp32s * pSrc, int nSrcStep, Npp32s * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    void Xor(const Image32sC4View &pSrc, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiAlphaComp_32s_AC4R_Ctx(const Npp32s * pSrc1, int nSrc1Step, const Npp32s * pSrc2, int nSrc2Step, Npp32s * pDst, int nDstStep, NppiSize oSizeROI, NppiAlphaOp eAlphaOp, NppStreamContext nppStreamCtx)
    void AlphaCompA(const Image32sC4View &pSrc2, Image32sC4View &pDst, NppiAlphaOp eAlphaOp, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiFilter32f_32s_C4R_Ctx(const Npp32s * pSrc, int nSrcStep, Npp32s * pDst, int nDstStep, NppiSize oSizeROI, const Npp32f * pKernel, NppiSize oKernelSize, NppiPoint oAnchor, NppStreamContext nppStreamCtx)
    void Filter32f(Image32sC4View &pDst, const cuda::DevVarView<float> &pKernel, NppiSize oKernelSize, NppiPoint oAnchor, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiFilter32f_32s_AC4R_Ctx(const Npp32s * pSrc, int nSrcStep, Npp32s * pDst, int nDstStep, NppiSize oSizeROI, const Npp32f * pKernel, NppiSize oKernelSize, NppiPoint oAnchor, NppStreamContext nppStreamCtx)
    void Filter32fA(Image32sC4View &pDst, const cuda::DevVarView<float> &pKernel, NppiSize oKernelSize, NppiPoint oAnchor, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiFilterBorder32f_32s_C4R_Ctx(const Npp32s * pSrc, int nSrcStep, NppiSize oSrcSize, NppiPoint oSrcOffset, Npp32s * pDst, int nDstStep, NppiSize oSizeROI, const Npp32f * pKernel, NppiSize oKernelSize, NppiPoint oAnchor, NppiBorderType eBorderType, NppStreamContext nppStreamCtx)
    void FilterBorder32f(Image32sC4View &pDst, const cuda::DevVarView<float> &pKernel, NppiSize oKernelSize, NppiPoint oAnchor, NppiBorderType eBorderType, const NppStreamContext &nppStreamCtx, const Roi &aFilterArea = Roi()) const;

    // NppStatus nppiFilterBorder32f_32s_AC4R_Ctx(const Npp32s * pSrc, int nSrcStep, NppiSize oSrcSize, NppiPoint oSrcOffset, Npp32s * pDst, int nDstStep, NppiSize oSizeROI, const Npp32f * pKernel, NppiSize oKernelSize, NppiPoint oAnchor, NppiBorderType eBorderType, NppStreamContext nppStreamCtx)
    void FilterBorder32fA(Image32sC4View &pDst, const cuda::DevVarView<float> &pKernel, NppiSize oKernelSize, NppiPoint oAnchor, NppiBorderType eBorderType, const NppStreamContext &nppStreamCtx, const Roi &aFilterArea = Roi()) const;

    // NppStatus nppiDotProd_32s64f_C4R_Ctx(const Npp32s * pSrc1, int nSrc1Step, const Npp32s * pSrc2, int nSrc2Step, NppiSize oSizeROI, Npp64f[4] aDp, Npp8u * pDeviceBuffer, NppStreamContext nppStreamCtx)
    void DotProd(const Image32sC4View &pSrc2, cuda::DevVarView<double> &aDp, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiDotProd_32s64f_AC4R_Ctx(const Npp32s * pSrc1, int nSrc1Step, const Npp32s * pSrc2, int nSrc2Step, NppiSize oSizeROI, Npp64f[3] aDp, Npp8u * pDeviceBuffer, NppStreamContext nppStreamCtx)
    void DotProdA(const Image32sC4View &pSrc2, cuda::DevVarView<double> &aDp, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiDotProdGetBufferHostSize_32s64f_C4R_Ctx(NppiSize oSizeROI, size_t * hpBufferSize, NppStreamContext nppStreamCtx)
    [[nodiscard]] size_t DotProdGetBufferHostSize(const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiDotProdGetBufferHostSize_32s64f_AC4R_Ctx(NppiSize oSizeROI, size_t * hpBufferSize, NppStreamContext nppStreamCtx)
    [[nodiscard]] size_t DotProdGetBufferHostSizeA(const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiMaximumError_32s_C4R_Ctx(const Npp32s * pSrc1, int nSrc1Step, const Npp32s * pSrc2, int nSrc2Step, NppiSize oSizeROI, Npp64f * pError, Npp8u * pDeviceBuffer, NppStreamContext nppStreamCtx)
    void MaximumError(const Image32sC4View &pSrc2, cuda::DevVarView<double> &pError, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiMaximumErrorGetBufferHostSize_32s_C4R_Ctx(NppiSize oSizeROI, size_t * hpBufferSize, NppStreamContext nppStreamCtx)
    [[nodiscard]] size_t MaximumErrorGetBufferHostSize(const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiAverageError_32s_C4R_Ctx(const Npp32s * pSrc1, int nSrc1Step, const Npp32s * pSrc2, int nSrc2Step, NppiSize oSizeROI, Npp64f * pError, Npp8u * pDeviceBuffer, NppStreamContext nppStreamCtx)
    void AverageError(const Image32sC4View &pSrc2, cuda::DevVarView<double> &pError, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiAverageErrorGetBufferHostSize_32s_C4R_Ctx(NppiSize oSizeROI, size_t * hpBufferSize, NppStreamContext nppStreamCtx)
    [[nodiscard]] size_t AverageErrorGetBufferHostSize(const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiMaximumRelativeError_32s_C4R_Ctx(const Npp32s * pSrc1, int nSrc1Step, const Npp32s * pSrc2, int nSrc2Step, NppiSize oSizeROI, Npp64f * pError, Npp8u * pDeviceBuffer, NppStreamContext nppStreamCtx)
    void MaximumRelativeError(const Image32sC4View &pSrc2, cuda::DevVarView<double> &pError, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiMaximumRelativeErrorGetBufferHostSize_32s_C4R_Ctx(NppiSize oSizeROI, size_t * hpBufferSize, NppStreamContext nppStreamCtx)
    [[nodiscard]] size_t MaximumRelativeErrorGetBufferHostSize(const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiAverageRelativeError_32s_C4R_Ctx(const Npp32s * pSrc1, int nSrc1Step, const Npp32s * pSrc2, int nSrc2Step, NppiSize oSizeROI, Npp64f * pError, Npp8u * pDeviceBuffer, NppStreamContext nppStreamCtx)
    void AverageRelativeError(const Image32sC4View &pSrc2, cuda::DevVarView<double> &pError, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiAverageRelativeErrorGetBufferHostSize_32s_C4R_Ctx(NppiSize oSizeROI, size_t * hpBufferSize, NppStreamContext nppStreamCtx)
    [[nodiscard]] size_t AverageRelativeErrorGetBufferHostSize(const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiMirror_32s_C4R_Ctx(const Npp32s * pSrc, int nSrcStep, Npp32s * pDst, int nDstStep, NppiSize oROI, NppiAxis flip, NppStreamContext nppStreamCtx)
    void Mirror(Image32sC4View &pDst, NppiAxis flip, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiMirror_32s_C4IR_Ctx(Npp32s * pSrcDst, int nSrcDstStep, NppiSize oROI, NppiAxis flip, NppStreamContext nppStreamCtx)
    void Mirror(NppiAxis flip, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiMirror_32s_AC4R_Ctx(const Npp32s * pSrc, int nSrcStep, Npp32s * pDst, int nDstStep, NppiSize oROI, NppiAxis flip, NppStreamContext nppStreamCtx)
    void MirrorA(Image32sC4View &pDst, NppiAxis flip, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiMirror_32s_AC4IR_Ctx(Npp32s * pSrcDst, int nSrcDstStep, NppiSize oROI, NppiAxis flip, NppStreamContext nppStreamCtx)
    void MirrorA(NppiAxis flip, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiWarpAffine_32s_C4R_Ctx(const Npp32s * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, Npp32s * pDst, int nDstStep, NppiRect oDstROI, const double[2][3] aCoeffs, int eInterpolation, NppStreamContext nppStreamCtx)
    void WarpAffine(Image32sC4View &pDst, const double aCoeffs[2][3], int eInterpolation, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiWarpAffine_32s_AC4R_Ctx(const Npp32s * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, Npp32s * pDst, int nDstStep, NppiRect oDstROI, const double[2][3] aCoeffs, int eInterpolation, NppStreamContext nppStreamCtx)
    void WarpAffineA(Image32sC4View &pDst, const double aCoeffs[2][3], int eInterpolation, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiWarpAffine_32s_P4R_Ctx(const Npp32s *[4] pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, Npp32s *[4] pDst, int nDstStep, NppiRect oDstROI, const double[2][3] aCoeffs, int eInterpolation, NppStreamContext nppStreamCtx)
    static void WarpAffine(const Image32sC1View &aSrcChannel0, const Image32sC1View &aSrcChannel1, const Image32sC1View &aSrcChannel2, const Image32sC1View &aSrcChannel3, Image32sC1View &aDstChannel0, Image32sC1View &aDstChannel1, Image32sC1View &aDstChannel2, Image32sC1View &aDstChannel3, const double aCoeffs[2][3], int eInterpolation, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiWarpAffineBack_32s_C4R_Ctx(const Npp32s * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, Npp32s * pDst, int nDstStep, NppiRect oDstROI, const double[2][3] aCoeffs, int eInterpolation, NppStreamContext nppStreamCtx)
    void WarpAffineBack(Image32sC4View &pDst, const double aCoeffs[2][3], int eInterpolation, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiWarpAffineBack_32s_AC4R_Ctx(const Npp32s * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, Npp32s * pDst, int nDstStep, NppiRect oDstROI, const double[2][3] aCoeffs, int eInterpolation, NppStreamContext nppStreamCtx)
    void WarpAffineBackA(Image32sC4View &pDst, const double aCoeffs[2][3], int eInterpolation, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiWarpAffineBack_32s_P4R_Ctx(const Npp32s *[4] pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, Npp32s *[4] pDst, int nDstStep, NppiRect oDstROI, const double[2][3] aCoeffs, int eInterpolation, NppStreamContext nppStreamCtx)
    static void WarpAffineBack(const Image32sC1View &aSrcChannel0, const Image32sC1View &aSrcChannel1, const Image32sC1View &aSrcChannel2, const Image32sC1View &aSrcChannel3, Image32sC1View &aDstChannel0, Image32sC1View &aDstChannel1, Image32sC1View &aDstChannel2, Image32sC1View &aDstChannel3, const double aCoeffs[2][3], int eInterpolation, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiWarpAffineQuad_32s_C4R_Ctx(const Npp32s * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const double[4][2] aSrcQuad, Npp32s * pDst, int nDstStep, NppiRect oDstROI, const double[4][2] aDstQuad, int eInterpolation, NppStreamContext nppStreamCtx)
    void WarpAffineQuad(const double aSrcQuad[4][2], Image32sC4View &pDst, const double aDstQuad[4][2], int eInterpolation, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiWarpAffineQuad_32s_AC4R_Ctx(const Npp32s * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const double[4][2] aSrcQuad, Npp32s * pDst, int nDstStep, NppiRect oDstROI, const double[4][2] aDstQuad, int eInterpolation, NppStreamContext nppStreamCtx)
    void WarpAffineQuadA(const double aSrcQuad[4][2], Image32sC4View &pDst, const double aDstQuad[4][2], int eInterpolation, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiWarpAffineQuad_32s_P4R_Ctx(const Npp32s *[4] pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const double[4][2] aSrcQuad, Npp32s *[4] pDst, int nDstStep, NppiRect oDstROI, const double[4][2] aDstQuad, int eInterpolation, NppStreamContext nppStreamCtx)
    static void WarpAffineQuad(const Image32sC1View &aSrcChannel0, const Image32sC1View &aSrcChannel1, const Image32sC1View &aSrcChannel2, const Image32sC1View &aSrcChannel3, Image32sC1View &aDstChannel0, Image32sC1View &aDstChannel1, Image32sC1View &aDstChannel2, Image32sC1View &aDstChannel3, const double aSrcQuad[4][2], const double aDstQuad[4][2], int eInterpolation, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiWarpPerspective_32s_C4R_Ctx(const Npp32s * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, Npp32s * pDst, int nDstStep, NppiRect oDstROI, const double[3][3] aCoeffs, int eInterpolation, NppStreamContext nppStreamCtx)
    void WarpPerspective(Image32sC4View &pDst, const double aCoeffs[3][3], int eInterpolation, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiWarpPerspective_32s_AC4R_Ctx(const Npp32s * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, Npp32s * pDst, int nDstStep, NppiRect oDstROI, const double[3][3] aCoeffs, int eInterpolation, NppStreamContext nppStreamCtx)
    void WarpPerspectiveA(Image32sC4View &pDst, const double aCoeffs[3][3], int eInterpolation, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiWarpPerspective_32s_P4R_Ctx(const Npp32s *[4] pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, Npp32s *[4] pDst, int nDstStep, NppiRect oDstROI, const double[3][3] aCoeffs, int eInterpolation, NppStreamContext nppStreamCtx)
    static void WarpPerspective(const Image32sC1View &aSrcChannel0, const Image32sC1View &aSrcChannel1, const Image32sC1View &aSrcChannel2, const Image32sC1View &aSrcChannel3, Image32sC1View &aDstChannel0, Image32sC1View &aDstChannel1, Image32sC1View &aDstChannel2, Image32sC1View &aDstChannel3, const double aCoeffs[3][3], int eInterpolation, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiWarpPerspectiveBack_32s_C4R_Ctx(const Npp32s * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, Npp32s * pDst, int nDstStep, NppiRect oDstROI, const double[3][3] aCoeffs, int eInterpolation, NppStreamContext nppStreamCtx)
    void WarpPerspectiveBack(Image32sC4View &pDst, const double aCoeffs[3][3], int eInterpolation, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiWarpPerspectiveBack_32s_AC4R_Ctx(const Npp32s * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, Npp32s * pDst, int nDstStep, NppiRect oDstROI, const double[3][3] aCoeffs, int eInterpolation, NppStreamContext nppStreamCtx)
    void WarpPerspectiveBackA(Image32sC4View &pDst, const double aCoeffs[3][3], int eInterpolation, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiWarpPerspectiveBack_32s_P4R_Ctx(const Npp32s *[4] pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, Npp32s *[4] pDst, int nDstStep, NppiRect oDstROI, const double[3][3] aCoeffs, int eInterpolation, NppStreamContext nppStreamCtx)
    static void WarpPerspectiveBack(const Image32sC1View &aSrcChannel0, const Image32sC1View &aSrcChannel1, const Image32sC1View &aSrcChannel2, const Image32sC1View &aSrcChannel3, Image32sC1View &aDstChannel0, Image32sC1View &aDstChannel1, Image32sC1View &aDstChannel2, Image32sC1View &aDstChannel3, const double aCoeffs[3][3], int eInterpolation, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiWarpPerspectiveQuad_32s_C4R_Ctx(const Npp32s * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const double[4][2] aSrcQuad, Npp32s * pDst, int nDstStep, NppiRect oDstROI, const double[4][2] aDstQuad, int eInterpolation, NppStreamContext nppStreamCtx)
    void WarpPerspectiveQuad(const double aSrcQuad[4][2], Image32sC4View &pDst, const double aDstQuad[4][2], int eInterpolation, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiWarpPerspectiveQuad_32s_AC4R_Ctx(const Npp32s * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const double[4][2] aSrcQuad, Npp32s * pDst, int nDstStep, NppiRect oDstROI, const double[4][2] aDstQuad, int eInterpolation, NppStreamContext nppStreamCtx)
    void WarpPerspectiveQuadA(const double aSrcQuad[4][2], Image32sC4View &pDst, const double aDstQuad[4][2], int eInterpolation, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiWarpPerspectiveQuad_32s_P4R_Ctx(const Npp32s *[4] pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const double[4][2] aSrcQuad, Npp32s *[4] pDst, int nDstStep, NppiRect oDstROI, const double[4][2] aDstQuad, int eInterpolation, NppStreamContext nppStreamCtx)
    static void WarpPerspectiveQuad(const Image32sC1View &aSrcChannel0, const Image32sC1View &aSrcChannel1, const Image32sC1View &aSrcChannel2, const Image32sC1View &aSrcChannel3, Image32sC1View &aDstChannel0, Image32sC1View &aDstChannel1, Image32sC1View &aDstChannel2, Image32sC1View &aDstChannel3, const double aSrcQuad[4][2], const double aDstQuad[4][2], int eInterpolation, const NppStreamContext &nppStreamCtx);

    //NOLINTEND(readability-identifier-naming,readability-avoid-const-params-in-decls, bugprone-easily-swappable-parameters, readability-convert-member-functions-to-static)
};
} // namespace opp::image::npp
