#pragma once

#include "imageView.h"
#include <backends/cuda/devVarView.h>
#include <backends/npp/nppException.h>
#include <common/image/pixelTypes.h>
#include <common/image/roi.h>
#include <common/image/roiException.h>
#include <common/image/size2D.h>
#include <common/image/sizePitched.h>

namespace opp::image::npp
{
// forward declaration:
class Image16sC1View;
class Image16uC1View;
class Image32fC1View;
class Image32sC1View;
class Image32uC1View;
class Image64fC1View;
class Image8sC1View;
class Image8uC3View;
class Image8uC4View;

class Image####View : public ImageView<Pixel####>
{
  protected:
    Image####View() = default;
    explicit Image####View(const Size2D &aSize);

  public:
    Image####View(Pixel#### *aBasePointer, const SizePitched &aSizeAlloc);
    Image####View(Pixel#### *aBasePointer, const SizePitched &aSizeAlloc, const Roi &aRoi);
    ~Image####View() = default;

    Image####View(const Image####View &)     = default;
    Image####View(Image####View &&) noexcept = default;

    Image####View &operator=(const Image####View &)     = default;
    Image####View &operator=(Image####View &&) noexcept = default;

    /// <summary>
    /// Returns a new Image####View with the new ROI
    /// </summary>
    [[nodiscard]] Image####View GetView(const Roi &aRoi) const;

    /// <summary>
    /// Returns a new ImageView with the current ROI adapted by aBorder
    /// </summary>
    [[nodiscard]] Image####View GetView(const Border &aBorder = Border()) const;

    //NOLINTBEGIN(readability-identifier-naming,readability-avoid-const-params-in-decls)

    void Set(const Pixel8uC1 &nValue, const NppStreamContext &nppStreamCtx);
    void Set(const Pixel8uC1 &nValue, const Image8uC1View &pMask, const NppStreamContext &nppStreamCtx);
    void Copy(Image8uC1View &pDst, const NppStreamContext &nppStreamCtx) const;
    void Copy(Image8uC1View &pDst, const Image8uC1View &pMask, const NppStreamContext &nppStreamCtx) const;
    void Copy(size_t aDstChannel, Image8uC3View &pDst, const NppStreamContext &nppStreamCtx) const;
    void Copy(size_t aDstChannel, Image8uC4View &pDst, const NppStreamContext &nppStreamCtx) const;
    void CopyConstBorder(Image8uC1View &pDst, int nTopBorderHeight, int nLeftBorderWidth, const Pixel8uC1 &nValue, const NppStreamContext &nppStreamCtx) const;
    void CopyReplicateBorder(Image8uC1View &pDst, int nTopBorderHeight, int nLeftBorderWidth, const NppStreamContext &nppStreamCtx) const;
    void CopyWrapBorder(Image8uC1View &pDst, int nTopBorderHeight, int nLeftBorderWidth, const NppStreamContext &nppStreamCtx) const;
    void CopySubpix(Image8uC1View &pDst, Npp32f nDx, Npp32f nDy, const NppStreamContext &nppStreamCtx) const;
    void Convert(Image16uC1View &pDst, const NppStreamContext &nppStreamCtx) const;
    void Convert(Image16sC1View &pDst, const NppStreamContext &nppStreamCtx) const;
    void Convert(Image32sC1View &pDst, const NppStreamContext &nppStreamCtx) const;
    void Convert(Image32fC1View &pDst, const NppStreamContext &nppStreamCtx) const;
    void Convert(Image8sC1View &pDst, NppRoundMode eRoundMode, int nScaleFactor, const NppStreamContext &nppStreamCtx) const;
    void Scale(Image16uC1View &pDst, const NppStreamContext &nppStreamCtx) const;
    void Scale(Image16sC1View &pDst, const NppStreamContext &nppStreamCtx) const;
    void Scale(Image32sC1View &pDst, const NppStreamContext &nppStreamCtx) const;
    void Scale(Image32fC1View &pDst, Npp32f nMin, Npp32f nMax, const NppStreamContext &nppStreamCtx) const;
    void Dup(Image8uC3View &pDst, const NppStreamContext &nppStreamCtx) const;
    void Dup(Image8uC4View &pDst, const NppStreamContext &nppStreamCtx) const;
    void DupA(Image8uC4View &pDst, const NppStreamContext &nppStreamCtx) const;
    void Transpose(Image8uC1View &pDst, const NppStreamContext &nppStreamCtx) const;
    void Add(const Pixel8uC1 &nConstant, Image8uC1View &pDst, int nScaleFactor, const NppStreamContext &nppStreamCtx) const;
    void Add(const cuda::DevVarView<Pixel8uC1> &pConstant, Image8uC1View &pDst, int nScaleFactor, const NppStreamContext &nppStreamCtx) const;
    void Add(const Pixel8uC1 &nConstant, int nScaleFactor, const NppStreamContext &nppStreamCtx);
    void Add(const cuda::DevVarView<Pixel8uC1> &pConstant, int nScaleFactor, const NppStreamContext &nppStreamCtx);
    void Mul(const Pixel8uC1 &nConstant, Image8uC1View &pDst, int nScaleFactor, const NppStreamContext &nppStreamCtx) const;
    void Mul(const cuda::DevVarView<Pixel8uC1> &pConstant, Image8uC1View &pDst, int nScaleFactor, const NppStreamContext &nppStreamCtx) const;
    void Mul(const Pixel8uC1 &nConstant, int nScaleFactor, const NppStreamContext &nppStreamCtx);
    void Mul(const cuda::DevVarView<Pixel8uC1> &pConstant, int nScaleFactor, const NppStreamContext &nppStreamCtx);
    void MulScale(const Pixel8uC1 &nConstant, Image8uC1View &pDst, const NppStreamContext &nppStreamCtx) const;
    void MulScale(const cuda::DevVarView<Pixel8uC1> &pConstant, Image8uC1View &pDst, const NppStreamContext &nppStreamCtx) const;
    void MulScale(const Pixel8uC1 &nConstant, const NppStreamContext &nppStreamCtx);
    void MulScale(const cuda::DevVarView<Pixel8uC1> &pConstant, const NppStreamContext &nppStreamCtx);
    void Sub(const Pixel8uC1 &nConstant, Image8uC1View &pDst, int nScaleFactor, const NppStreamContext &nppStreamCtx) const;
    void Sub(const cuda::DevVarView<Pixel8uC1> &pConstant, Image8uC1View &pDst, int nScaleFactor, const NppStreamContext &nppStreamCtx) const;
    void Sub(const Pixel8uC1 &nConstant, int nScaleFactor, const NppStreamContext &nppStreamCtx);
    void Sub(const cuda::DevVarView<Pixel8uC1> &pConstant, int nScaleFactor, const NppStreamContext &nppStreamCtx);
    void Div(const Pixel8uC1 &nConstant, Image8uC1View &pDst, int nScaleFactor, const NppStreamContext &nppStreamCtx) const;
    void Div(const cuda::DevVarView<Pixel8uC1> &pConstant, Image8uC1View &pDst, int nScaleFactor, const NppStreamContext &nppStreamCtx) const;
    void Div(const Pixel8uC1 &nConstant, int nScaleFactor, const NppStreamContext &nppStreamCtx);
    void Div(const cuda::DevVarView<Pixel8uC1> &pConstant, int nScaleFactor, const NppStreamContext &nppStreamCtx);
    void AbsDiff(Image8uC1View &pDst, const Pixel8uC1 &nConstant, const NppStreamContext &nppStreamCtx) const;
    void AbsDiff(Image8uC1View &pDst, cuda::DevVarView<Pixel8uC1> &pConstant, const NppStreamContext &nppStreamCtx) const;
    void Add(const Image8uC1View &pSrc2, Image8uC1View &pDst, int nScaleFactor, const NppStreamContext &nppStreamCtx) const;
    void Add(const Image8uC1View &pSrc, int nScaleFactor, const NppStreamContext &nppStreamCtx);
    void Mul(const Image8uC1View &pSrc2, Image8uC1View &pDst, int nScaleFactor, const NppStreamContext &nppStreamCtx) const;
    void Mul(const Image8uC1View &pSrc, int nScaleFactor, const NppStreamContext &nppStreamCtx);
    void MulScale(const Image8uC1View &pSrc2, Image8uC1View &pDst, const NppStreamContext &nppStreamCtx) const;
    void MulScale(const Image8uC1View &pSrc, const NppStreamContext &nppStreamCtx);
    void Sub(const Image8uC1View &pSrc2, Image8uC1View &pDst, int nScaleFactor, const NppStreamContext &nppStreamCtx) const;
    void Sub(const Image8uC1View &pSrc, int nScaleFactor, const NppStreamContext &nppStreamCtx);
    void Div(const Image8uC1View &pSrc2, Image8uC1View &pDst, int nScaleFactor, const NppStreamContext &nppStreamCtx) const;
    void Div(const Image8uC1View &pSrc, int nScaleFactor, const NppStreamContext &nppStreamCtx);
    void Div_Round(const Image8uC1View &pSrc2, Image8uC1View &pDst, NppRoundMode rndMode, int nScaleFactor, const NppStreamContext &nppStreamCtx) const;
    void Div_Round(const Image8uC1View &pSrc, NppRoundMode rndMode, int nScaleFactor, const NppStreamContext &nppStreamCtx);
    void AbsDiff(const Image8uC1View &pSrc2, Image8uC1View &pDst, const NppStreamContext &nppStreamCtx) const;
    void Sqr(Image8uC1View &pDst, int nScaleFactor, const NppStreamContext &nppStreamCtx) const;
    void Sqr(int nScaleFactor, const NppStreamContext &nppStreamCtx);
    void Sqrt(Image8uC1View &pDst, int nScaleFactor, const NppStreamContext &nppStreamCtx) const;
    void Sqrt(int nScaleFactor, const NppStreamContext &nppStreamCtx);
    void Ln(Image8uC1View &pDst, int nScaleFactor, const NppStreamContext &nppStreamCtx) const;
    void Ln(int nScaleFactor, const NppStreamContext &nppStreamCtx);
    void Exp(Image8uC1View &pDst, int nScaleFactor, const NppStreamContext &nppStreamCtx) const;
    void Exp(int nScaleFactor, const NppStreamContext &nppStreamCtx);
    void And(const Pixel8uC1 &nConstant, Image8uC1View &pDst, const NppStreamContext &nppStreamCtx) const;
    void And(const Pixel8uC1 &nConstant, const NppStreamContext &nppStreamCtx);
    void Or(const Pixel8uC1 &nConstant, Image8uC1View &pDst, const NppStreamContext &nppStreamCtx) const;
    void Or(const Pixel8uC1 &nConstant, const NppStreamContext &nppStreamCtx);
    void Xor(const Pixel8uC1 &nConstant, Image8uC1View &pDst, const NppStreamContext &nppStreamCtx) const;
    void Xor(const Pixel8uC1 &nConstant, const NppStreamContext &nppStreamCtx);
    void RShift(Npp32u nConstant, Image8uC1View &pDst, const NppStreamContext &nppStreamCtx) const;
    void RShift(Npp32u nConstant, const NppStreamContext &nppStreamCtx);
    void LShift(Npp32u nConstant, Image8uC1View &pDst, const NppStreamContext &nppStreamCtx) const;
    void LShift(Npp32u nConstant, const NppStreamContext &nppStreamCtx);
    void And(const Image8uC1View &pSrc2, Image8uC1View &pDst, const NppStreamContext &nppStreamCtx) const;
    void And(const Image8uC1View &pSrc, const NppStreamContext &nppStreamCtx);
    void Or(const Image8uC1View &pSrc2, Image8uC1View &pDst, const NppStreamContext &nppStreamCtx) const;
    void Or(const Image8uC1View &pSrc, const NppStreamContext &nppStreamCtx);
    void Xor(const Image8uC1View &pSrc2, Image8uC1View &pDst, const NppStreamContext &nppStreamCtx) const;
    void Xor(const Image8uC1View &pSrc, const NppStreamContext &nppStreamCtx);
    void Not(Image8uC1View &pDst, const NppStreamContext &nppStreamCtx) const;
    void Not(const NppStreamContext &nppStreamCtx);
    void AlphaComp(const Pixel8uC1 &nAlpha1, const Image8uC1View &pSrc2, const Pixel8uC1 &nAlpha2, Image8uC1View &pDst, NppiAlphaOp eAlphaOp, const NppStreamContext &nppStreamCtx) const;
    void AlphaPremul(const Pixel8uC1 &nAlpha1, Image8uC1View &pDst, const NppStreamContext &nppStreamCtx) const;
    void AlphaPremul(const Pixel8uC1 &nAlpha1, const NppStreamContext &nppStreamCtx);
    void AlphaComp(const Image8uC1View &pSrc2, Image8uC1View &pDst, NppiAlphaOp eAlphaOp, const NppStreamContext &nppStreamCtx) const;
    void CFAToRGB(Image8uC3View &pDst, NppiBayerGridPosition eGrid, NppiInterpolationMode eInterpolation, const NppStreamContext &nppStreamCtx) const;
    void CFAToRGBA(Image8uC4View &pDst, NppiBayerGridPosition eGrid, NppiInterpolationMode eInterpolation, const Pixel8uC1 &nAlpha, const NppStreamContext &nppStreamCtx) const;
    void CompColorKey(const Image8uC1View &pSrc2, Image8uC1View &pDst, const Pixel8uC1 &nColorKeyConst, const NppStreamContext &nppStreamCtx) const;
    void ColorTwist32f(Image8uC1View &pDst, const Npp32f aTwist[3][4], const NppStreamContext &nppStreamCtx) const;
    void ColorTwist32f(const Npp32f aTwist[3][4], const NppStreamContext &nppStreamCtx);
    void LUT(Image8uC1View &pDst, const cuda::DevVarView<int> &pValues, const cuda::DevVarView<int> &pLevels, int nLevels, const NppStreamContext &nppStreamCtx) const;
    void LUT(const cuda::DevVarView<int> &pValues, const cuda::DevVarView<int> &pLevels, int nLevels, const NppStreamContext &nppStreamCtx);
    void LUT_Linear(Image8uC1View &pDst, const cuda::DevVarView<int> &pValues, const cuda::DevVarView<int> &pLevels, int nLevels, const NppStreamContext &nppStreamCtx) const;
    void LUT_Linear(const cuda::DevVarView<int> &pValues, const cuda::DevVarView<int> &pLevels, int nLevels, const NppStreamContext &nppStreamCtx);
    void LUT_Cubic(Image8uC1View &pDst, const cuda::DevVarView<int> &pValues, const cuda::DevVarView<int> &pLevels, int nLevels, const NppStreamContext &nppStreamCtx) const;
    void LUT_Cubic(const cuda::DevVarView<int> &pValues, const cuda::DevVarView<int> &pLevels, int nLevels, const NppStreamContext &nppStreamCtx);
    void LUTPalette(Image8uC1View &pDst, const cuda::DevVarView<Pixel8uC1> &pTable, int nBitSize, const NppStreamContext &nppStreamCtx) const;
    void LUTPalette(Image8uC3View &pDst, const cuda::DevVarView<Pixel8uC3> &pTable, int nBitSize, const NppStreamContext &nppStreamCtx) const;
    void LUTPalette(Image8uC4View &pDst, const cuda::DevVarView<Pixel8uC4> &pTable, int nBitSize, const NppStreamContext &nppStreamCtx) const;
    void Threshold(Image8uC1View &pDst, const Pixel8uC1 &nThreshold, NppCmpOp eComparisonOperation, const NppStreamContext &nppStreamCtx) const;
    void Threshold(const Pixel8uC1 &nThreshold, NppCmpOp eComparisonOperation, const NppStreamContext &nppStreamCtx);
    void Threshold_GT(Image8uC1View &pDst, const Pixel8uC1 &nThreshold, const NppStreamContext &nppStreamCtx) const;
    void Threshold_GT(const Pixel8uC1 &nThreshold, const NppStreamContext &nppStreamCtx);
    void Threshold_LT(Image8uC1View &pDst, const Pixel8uC1 &nThreshold, const NppStreamContext &nppStreamCtx) const;
    void Threshold_LT(const Pixel8uC1 &nThreshold, const NppStreamContext &nppStreamCtx);
    void Threshold_Val(Image8uC1View &pDst, const Pixel8uC1 &nThreshold, const Pixel8uC1 &nValue, NppCmpOp eComparisonOperation, const NppStreamContext &nppStreamCtx) const;
    void Threshold_Val(const Pixel8uC1 &nThreshold, const Pixel8uC1 &nValue, NppCmpOp eComparisonOperation, const NppStreamContext &nppStreamCtx);
    void Threshold_GTVal(Image8uC1View &pDst, const Pixel8uC1 &nThreshold, const Pixel8uC1 &nValue, const NppStreamContext &nppStreamCtx) const;
    void Threshold_GTVal(const Pixel8uC1 &nThreshold, const Pixel8uC1 &nValue, const NppStreamContext &nppStreamCtx);
    void Threshold_LTVal(Image8uC1View &pDst, const Pixel8uC1 &nThreshold, const Pixel8uC1 &nValue, const NppStreamContext &nppStreamCtx) const;
    void Threshold_LTVal(const Pixel8uC1 &nThreshold, const Pixel8uC1 &nValue, const NppStreamContext &nppStreamCtx);
    void Threshold_LTValGTVal(Image8uC1View &pDst, const Pixel8uC1 &nThresholdLT, const Pixel8uC1 &nValueLT, const Pixel8uC1 &nThresholdGT, const Pixel8uC1 &nValueGT, const NppStreamContext &nppStreamCtx) const;
    void Threshold_LTValGTVal(const Pixel8uC1 &nThresholdLT, const Pixel8uC1 &nValueLT, const Pixel8uC1 &nThresholdGT, const Pixel8uC1 &nValueGT, const NppStreamContext &nppStreamCtx);
    void Compare(const Image8uC1View &pSrc2, Image8uC1View &pDst, NppCmpOp eComparisonOperation, const NppStreamContext &nppStreamCtx) const;
    void Compare(const Pixel8uC1 &nConstant, Image8uC1View &pDst, NppCmpOp eComparisonOperation, const NppStreamContext &nppStreamCtx) const;
    void Dilate(Image8uC1View &pDst, const cuda::DevVarView<byte> &pMask, NppiSize oMaskSize, NppiPoint oAnchor, const NppStreamContext &nppStreamCtx) const;
    void DilateBorder(Image8uC1View &pDst, const cuda::DevVarView<byte> &pMask, NppiSize oMaskSize, NppiPoint oAnchor, NppiBorderType eBorderType, const NppStreamContext &nppStreamCtx, const Roi&aFilterArea = Roi()) const;
    void GrayDilateBorder(Image8uC1View &pDst, const cuda::DevVarView<int> &pMask, NppiSize oMaskSize, NppiPoint oAnchor, NppiBorderType eBorderType, const NppStreamContext &nppStreamCtx, const Roi&aFilterArea = Roi()) const;
    void Dilate3x3(Image8uC1View &pDst, const NppStreamContext &nppStreamCtx) const;
    void Dilate3x3Border(Image8uC1View &pDst, NppiBorderType eBorderType, const NppStreamContext &nppStreamCtx, const Roi&aFilterArea = Roi()) const;
    void Erode(Image8uC1View &pDst, const cuda::DevVarView<byte> &pMask, NppiSize oMaskSize, NppiPoint oAnchor, const NppStreamContext &nppStreamCtx) const;
    void ErodeBorder(Image8uC1View &pDst, const cuda::DevVarView<byte> &pMask, NppiSize oMaskSize, NppiPoint oAnchor, NppiBorderType eBorderType, const NppStreamContext &nppStreamCtx, const Roi&aFilterArea = Roi()) const;
    void GrayErodeBorder(Image8uC1View &pDst, const cuda::DevVarView<int> &pMask, NppiSize oMaskSize, NppiPoint oAnchor, NppiBorderType eBorderType, const NppStreamContext &nppStreamCtx, const Roi&aFilterArea = Roi()) const;
    void Erode3x3(Image8uC1View &pDst, const NppStreamContext &nppStreamCtx) const;
    void Erode3x3Border(Image8uC1View &pDst, NppiBorderType eBorderType, const NppStreamContext &nppStreamCtx, const Roi&aFilterArea = Roi()) const;
    [[nodiscard]] size_t MorphGetBufferSize() const;
    void MorphCloseBorder(Image8uC1View &pDst, const cuda::DevVarView<byte> &pMask, NppiSize oMaskSize, NppiPoint oAnchor, cuda::DevVarView<byte> &pBuffer, NppiBorderType eBorderType, const NppStreamContext &nppStreamCtx, const Roi&aFilterArea = Roi()) const;
    void MorphOpenBorder(Image8uC1View &pDst, const cuda::DevVarView<byte> &pMask, NppiSize oMaskSize, NppiPoint oAnchor, cuda::DevVarView<byte> &pBuffer, NppiBorderType eBorderType, const NppStreamContext &nppStreamCtx, const Roi&aFilterArea = Roi()) const;
    void MorphTopHatBorder(Image8uC1View &pDst, const cuda::DevVarView<byte> &pMask, NppiSize oMaskSize, NppiPoint oAnchor, cuda::DevVarView<byte> &pBuffer, NppiBorderType eBorderType, const NppStreamContext &nppStreamCtx, const Roi&aFilterArea = Roi()) const;
    void MorphBlackHatBorder(Image8uC1View &pDst, const cuda::DevVarView<byte> &pMask, NppiSize oMaskSize, NppiPoint oAnchor, cuda::DevVarView<byte> &pBuffer, NppiBorderType eBorderType, const NppStreamContext &nppStreamCtx, const Roi&aFilterArea = Roi()) const;
    void MorphGradientBorder(Image8uC1View &pDst, const cuda::DevVarView<byte> &pMask, NppiSize oMaskSize, NppiPoint oAnchor, cuda::DevVarView<byte> &pBuffer, NppiBorderType eBorderType, const NppStreamContext &nppStreamCtx, const Roi&aFilterArea = Roi()) const;
    void FilterColumn(Image8uC1View &pDst, const cuda::DevVarView<int> &pKernel, Npp32s nMaskSize, Npp32s nAnchor, Npp32s nDivisor, const NppStreamContext &nppStreamCtx) const;
    void FilterColumnBorder(Image8uC1View &pDst, const cuda::DevVarView<int> &pKernel, Npp32s nMaskSize, Npp32s nAnchor, Npp32s nDivisor, NppiBorderType eBorderType, const NppStreamContext &nppStreamCtx, const Roi&aFilterArea = Roi()) const;
    void FilterColumn32f(Image8uC1View &pDst, const cuda::DevVarView<float> &pKernel, Npp32s nMaskSize, Npp32s nAnchor, const NppStreamContext &nppStreamCtx) const;
    void FilterColumnBorder32f(Image8uC1View &pDst, const cuda::DevVarView<float> &pKernel, Npp32s nMaskSize, Npp32s nAnchor, NppiBorderType eBorderType, const NppStreamContext &nppStreamCtx, const Roi&aFilterArea = Roi()) const;
    void FilterRow(Image8uC1View &pDst, const cuda::DevVarView<int> &pKernel, Npp32s nMaskSize, Npp32s nAnchor, Npp32s nDivisor, const NppStreamContext &nppStreamCtx) const;
    void FilterRowBorder(Image8uC1View &pDst, const cuda::DevVarView<int> &pKernel, Npp32s nMaskSize, Npp32s nAnchor, Npp32s nDivisor, NppiBorderType eBorderType, const NppStreamContext &nppStreamCtx, const Roi&aFilterArea = Roi()) const;
    void FilterRow32f(Image8uC1View &pDst, const cuda::DevVarView<float> &pKernel, Npp32s nMaskSize, Npp32s nAnchor, const NppStreamContext &nppStreamCtx) const;
    void FilterRowBorder32f(Image8uC1View &pDst, const cuda::DevVarView<float> &pKernel, Npp32s nMaskSize, Npp32s nAnchor, NppiBorderType eBorderType, const NppStreamContext &nppStreamCtx, const Roi&aFilterArea = Roi()) const;
    void SumWindowColumn(Image32fC1View &pDst, Npp32s nMaskSize, Npp32s nAnchor, const NppStreamContext &nppStreamCtx) const;
    void SumWindowRow(Image32fC1View &pDst, Npp32s nMaskSize, Npp32s nAnchor, const NppStreamContext &nppStreamCtx) const;
    void SumWindowColumnBorder(Image32fC1View &pDst, Npp32s nMaskSize, Npp32s nAnchor, NppiBorderType eBorderType, const NppStreamContext &nppStreamCtx, const Roi&aFilterArea = Roi()) const;
    void SumWindowRowBorder(Image32fC1View &pDst, Npp32s nMaskSize, Npp32s nAnchor, NppiBorderType eBorderType, const NppStreamContext &nppStreamCtx, const Roi&aFilterArea = Roi()) const;
    void Filter(Image8uC1View &pDst, const cuda::DevVarView<int> &pKernel, NppiSize oKernelSize, NppiPoint oAnchor, Npp32s nDivisor, const NppStreamContext &nppStreamCtx) const;
    void Filter32f(Image8uC1View &pDst, const cuda::DevVarView<float> &pKernel, NppiSize oKernelSize, NppiPoint oAnchor, const NppStreamContext &nppStreamCtx) const;
    void Filter32f(Image16sC1View &pDst, const cuda::DevVarView<float> &pKernel, NppiSize oKernelSize, NppiPoint oAnchor, const NppStreamContext &nppStreamCtx) const;
    void FilterBorder(Image8uC1View &pDst, const cuda::DevVarView<int> &pKernel, NppiSize oKernelSize, NppiPoint oAnchor, Npp32s nDivisor, NppiBorderType eBorderType, const NppStreamContext &nppStreamCtx, const Roi&aFilterArea = Roi()) const;
    void FilterBorder32f(Image8uC1View &pDst, const cuda::DevVarView<float> &pKernel, NppiSize oKernelSize, NppiPoint oAnchor, NppiBorderType eBorderType, const NppStreamContext &nppStreamCtx, const Roi&aFilterArea = Roi()) const;
    void FilterBorder32f(Image16sC1View &pDst, const cuda::DevVarView<float> &pKernel, NppiSize oKernelSize, NppiPoint oAnchor, NppiBorderType eBorderType, const NppStreamContext &nppStreamCtx, const Roi&aFilterArea = Roi()) const;
    void FilterBox(Image8uC1View &pDst, NppiSize oMaskSize, NppiPoint oAnchor, const NppStreamContext &nppStreamCtx) const;
    void FilterBoxBorder(Image8uC1View &pDst, NppiSize oMaskSize, NppiPoint oAnchor, NppiBorderType eBorderType, const NppStreamContext &nppStreamCtx, const Roi&aFilterArea = Roi()) const;
    void FilterBoxBorderAdvanced(Image8uC1View &pDst, NppiSize oMaskSize, NppiPoint oAnchor, NppiBorderType eBorderType, cuda::DevVarView<byte> &pBuffer, const NppStreamContext &nppStreamCtx, const Roi&aFilterArea = Roi()) const;
    void FilterThresholdAdaptiveBoxBorder(Image8uC1View &pDst, NppiSize oMaskSize, Npp32f nDelta, const Pixel8uC1 &nValGT, const Pixel8uC1 &nValLE, NppiBorderType eBorderType, const NppStreamContext &nppStreamCtx, const Roi&aFilterArea = Roi()) const;
    void FilterMax(Image8uC1View &pDst, NppiSize oMaskSize, NppiPoint oAnchor, const NppStreamContext &nppStreamCtx) const;
    void FilterMaxBorder(Image8uC1View &pDst, NppiSize oMaskSize, NppiPoint oAnchor, NppiBorderType eBorderType, const NppStreamContext &nppStreamCtx, const Roi&aFilterArea = Roi()) const;
    void FilterMin(Image8uC1View &pDst, NppiSize oMaskSize, NppiPoint oAnchor, const NppStreamContext &nppStreamCtx) const;
    void FilterMinBorder(Image8uC1View &pDst, NppiSize oMaskSize, NppiPoint oAnchor, NppiBorderType eBorderType, const NppStreamContext &nppStreamCtx, const Roi&aFilterArea = Roi()) const;
    void FilterMedian(Image8uC1View &pDst, NppiSize oMaskSize, NppiPoint oAnchor, cuda::DevVarView<byte> &pBuffer, const NppStreamContext &nppStreamCtx) const;
    [[nodiscard]] size_t FilterMedianGetBufferSize(NppiSize oMaskSize, const NppStreamContext &nppStreamCtx) const;
    void FilterMedianBorder(Image8uC1View &pDst, NppiSize oMaskSize, NppiPoint oAnchor, cuda::DevVarView<byte> &pBuffer, NppiBorderType eBorderType, const NppStreamContext &nppStreamCtx, const Roi&aFilterArea = Roi()) const;
    [[nodiscard]] size_t FilterMedianBorderGetBufferSize(NppiSize oMaskSize, NppiBorderType eBorderType, const NppStreamContext &nppStreamCtx) const;
    void FilterPrewittHoriz(Image8uC1View &pDst, const NppStreamContext &nppStreamCtx) const;
    void FilterPrewittVert(Image8uC1View &pDst, const NppStreamContext &nppStreamCtx) const;
    void FilterPrewittHorizBorder(Image8uC1View &pDst, NppiBorderType eBorderType, const NppStreamContext &nppStreamCtx, const Roi&aFilterArea = Roi()) const;
    void FilterPrewittVertBorder(Image8uC1View &pDst, NppiBorderType eBorderType, const NppStreamContext &nppStreamCtx, const Roi&aFilterArea = Roi()) const;
    void FilterScharrHoriz(Image16sC1View &pDst, const NppStreamContext &nppStreamCtx) const;
    void FilterScharrVert(Image16sC1View &pDst, const NppStreamContext &nppStreamCtx) const;
    void FilterScharrHorizBorder(Image16sC1View &pDst, NppiBorderType eBorderType, const NppStreamContext &nppStreamCtx, const Roi&aFilterArea = Roi()) const;
    void FilterScharrVertBorder(Image16sC1View &pDst, NppiBorderType eBorderType, const NppStreamContext &nppStreamCtx, const Roi&aFilterArea = Roi()) const;
    void FilterSobelHoriz(Image8uC1View &pDst, const NppStreamContext &nppStreamCtx) const;
    void FilterSobelHoriz(Image16sC1View &pDst, NppiMaskSize eMaskSize, const NppStreamContext &nppStreamCtx) const;
    void FilterSobelVert(Image8uC1View &pDst, const NppStreamContext &nppStreamCtx) const;
    void FilterSobelVert(Image16sC1View &pDst, NppiMaskSize eMaskSize, const NppStreamContext &nppStreamCtx) const;
    void FilterSobelHorizSecond(Image16sC1View &pDst, NppiMaskSize eMaskSize, const NppStreamContext &nppStreamCtx) const;
    void FilterSobelVertSecond(Image16sC1View &pDst, NppiMaskSize eMaskSize, const NppStreamContext &nppStreamCtx) const;
    void FilterSobelCross(Image16sC1View &pDst, NppiMaskSize eMaskSize, const NppStreamContext &nppStreamCtx) const;
    void FilterSobelHorizBorder(Image8uC1View &pDst, NppiBorderType eBorderType, const NppStreamContext &nppStreamCtx, const Roi&aFilterArea = Roi()) const;
    void FilterSobelHorizBorder(Image16sC1View &pDst, NppiMaskSize eMaskSize, NppiBorderType eBorderType, const NppStreamContext &nppStreamCtx, const Roi&aFilterArea = Roi()) const;
    void FilterSobelVertBorder(Image8uC1View &pDst, NppiBorderType eBorderType, const NppStreamContext &nppStreamCtx, const Roi&aFilterArea = Roi()) const;
    void FilterSobelVertBorder(Image16sC1View &pDst, NppiMaskSize eMaskSize, NppiBorderType eBorderType, const NppStreamContext &nppStreamCtx, const Roi&aFilterArea = Roi()) const;
    void FilterSobelHorizSecondBorder(Image16sC1View &pDst, NppiMaskSize eMaskSize, NppiBorderType eBorderType, const NppStreamContext &nppStreamCtx, const Roi&aFilterArea = Roi()) const;
    void FilterSobelVertSecondBorder(Image16sC1View &pDst, NppiMaskSize eMaskSize, NppiBorderType eBorderType, const NppStreamContext &nppStreamCtx, const Roi&aFilterArea = Roi()) const;
    void FilterSobelCrossBorder(Image16sC1View &pDst, NppiMaskSize eMaskSize, NppiBorderType eBorderType, const NppStreamContext &nppStreamCtx, const Roi&aFilterArea = Roi()) const;
    void FilterRobertsDown(Image8uC1View &pDst, const NppStreamContext &nppStreamCtx) const;
    void FilterRobertsUp(Image8uC1View &pDst, const NppStreamContext &nppStreamCtx) const;
    void FilterRobertsDownBorder(Image8uC1View &pDst, NppiBorderType eBorderType, const NppStreamContext &nppStreamCtx, const Roi&aFilterArea = Roi()) const;
    void FilterRobertsUpBorder(Image8uC1View &pDst, NppiBorderType eBorderType, const NppStreamContext &nppStreamCtx, const Roi&aFilterArea = Roi()) const;
    void FilterLaplace(Image8uC1View &pDst, NppiMaskSize eMaskSize, const NppStreamContext &nppStreamCtx) const;
    void FilterLaplace(Image16sC1View &pDst, NppiMaskSize eMaskSize, const NppStreamContext &nppStreamCtx) const;
    void FilterLaplaceBorder(Image8uC1View &pDst, NppiMaskSize eMaskSize, NppiBorderType eBorderType, const NppStreamContext &nppStreamCtx, const Roi&aFilterArea = Roi()) const;
    void FilterLaplaceBorder(Image16sC1View &pDst, NppiMaskSize eMaskSize, NppiBorderType eBorderType, const NppStreamContext &nppStreamCtx, const Roi&aFilterArea = Roi()) const;
    void FilterGauss(Image8uC1View &pDst, NppiMaskSize eMaskSize, const NppStreamContext &nppStreamCtx) const;
    void FilterGaussAdvanced(Image8uC1View &pDst, const int nFilterTaps, const cuda::DevVarView<float> &pKernel, const NppStreamContext &nppStreamCtx) const;
    void FilterGaussBorder(Image8uC1View &pDst, NppiMaskSize eMaskSize, NppiBorderType eBorderType, const NppStreamContext &nppStreamCtx, const Roi&aFilterArea = Roi()) const;
    void FilterGaussAdvancedBorder(Image8uC1View &pDst, const int nFilterTaps, const cuda::DevVarView<float> &pKernel, NppiBorderType eBorderType, const NppStreamContext &nppStreamCtx, const Roi&aFilterArea = Roi()) const;
    void FilterGaussPyramidLayerDownBorder(Image8uC1View &pDst, Npp32f nRate, const int nFilterTaps, const cuda::DevVarView<float> &pKernel, NppiBorderType eBorderType, const NppStreamContext &nppStreamCtx, const Roi&aFilterArea = Roi()) const;
    void FilterGaussPyramidLayerUpBorder(Image8uC1View &pDst, Npp32f nRate, const int nFilterTaps, const cuda::DevVarView<float> &pKernel, NppiBorderType eBorderType, const NppStreamContext &nppStreamCtx, const Roi&aFilterArea = Roi()) const;
    void FilterBilateralGaussBorder(Image8uC1View &pDst, const int nRadius, const int nStepBetweenSrcPixels, const Npp32f nValSquareSigma, const Npp32f nPosSquareSigma, NppiBorderType eBorderType, const NppStreamContext &nppStreamCtx, const Roi&aFilterArea = Roi()) const;
    void FilterHighPass(Image8uC1View &pDst, NppiMaskSize eMaskSize, const NppStreamContext &nppStreamCtx) const;
    void FilterHighPassBorder(Image8uC1View &pDst, NppiMaskSize eMaskSize, NppiBorderType eBorderType, const NppStreamContext &nppStreamCtx, const Roi&aFilterArea = Roi()) const;
    void FilterLowPass(Image8uC1View &pDst, NppiMaskSize eMaskSize, const NppStreamContext &nppStreamCtx) const;
    void FilterLowPassBorder(Image8uC1View &pDst, NppiMaskSize eMaskSize, NppiBorderType eBorderType, const NppStreamContext &nppStreamCtx, const Roi&aFilterArea = Roi()) const;
    void FilterSharpen(Image8uC1View &pDst, const NppStreamContext &nppStreamCtx) const;
    void FilterSharpenBorder(Image8uC1View &pDst, NppiBorderType eBorderType, const NppStreamContext &nppStreamCtx, const Roi&aFilterArea = Roi()) const;
    void FilterUnsharpBorder(Image8uC1View &pDst, Npp32f nRadius, Npp32f nSigma, Npp32f nWeight, Npp32f nThreshold, NppiBorderType eBorderType, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;
    [[nodiscard]] size_t FilterUnsharpGetBufferSize(const Npp32f nRadius, const Npp32f nSigma) const;
    void FilterWienerBorder(Image8uC1View &pDst, NppiSize oMaskSize, NppiPoint oAnchor, Npp32f aNoise[1], NppiBorderType eBorderType, const NppStreamContext &nppStreamCtx, const Roi&aFilterArea = Roi()) const;
    void GradientVectorPrewittBorder(Image16sC1View &pDstX, Image16sC1View &pDstY, Image16sC1View &pDstMag, Image32fC1View &pDstAngle, NppiMaskSize eMaskSize, NppiNorm eNorm, NppiBorderType eBorderType, const NppStreamContext &nppStreamCtx, const Roi&aFilterArea = Roi()) const;
    void GradientVectorScharrBorder(Image16sC1View &pDstX, Image16sC1View &pDstY, Image16sC1View &pDstMag, Image32fC1View &pDstAngle, NppiMaskSize eMaskSize, NppiNorm eNorm, NppiBorderType eBorderType, const NppStreamContext &nppStreamCtx, const Roi&aFilterArea = Roi()) const;
    void GradientVectorSobelBorder(Image16sC1View &pDstX, Image16sC1View &pDstY, Image16sC1View &pDstMag, Image32fC1View &pDstAngle, NppiMaskSize eMaskSize, NppiNorm eNorm, NppiBorderType eBorderType, const NppStreamContext &nppStreamCtx, const Roi&aFilterArea = Roi()) const;
    void DistanceTransformPBA(const Pixel8uC1 &nMinSiteValue, const Pixel8uC1 &nMaxSiteValue, Image16sC1View &pDstVoronoi, Image16sC1View &pDstVoronoiIndices, Image16sC1View &pDstVoronoiRelativeManhattanDistances, Image16uC1View &pDstTransform, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx);
    void DistanceTransformAbsPBA(const Pixel8uC1 &nMinSiteValue, const Pixel8uC1 &nMaxSiteValue, Image16sC1View &pDstVoronoi, Image16sC1View &pDstVoronoiIndices, Image16uC1View &pDstVoronoiAbsoluteManhattanDistances, Image16uC1View &pDstTransform, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx);
    void DistanceTransformPBA(const Pixel8uC1 &nMinSiteValue, const Pixel8uC1 &nMaxSiteValue, Image16sC1View &pDstVoronoi, Image16sC1View &pDstVoronoiIndices, Image16sC1View &pDstVoronoiRelativeManhattanDistances, Image32fC1View &pDstTransform, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx);
    void DistanceTransformAbsPBA(const Pixel8uC1 &nMinSiteValue, const Pixel8uC1 &nMaxSiteValue, Image16sC1View &pDstVoronoi, Image16sC1View &pDstVoronoiIndices, Image16uC1View &pDstVoronoiAbsoluteManhattanDistances, Image32fC1View &pDstTransform, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx);
    void DistanceTransformPBA(const Pixel8uC1 &nMinSiteValue, const Pixel8uC1 &nMaxSiteValue, Image16sC1View &pDstVoronoi, Image16sC1View &pDstVoronoiIndices, Image16sC1View &pDstVoronoiRelativeManhattanDistances, Image64fC1View &pDstTransform, cuda::DevVarView<byte> &pDeviceBuffer, cuda::DevVarView<byte> &pAntialiasingDeviceBuffer, const NppStreamContext &nppStreamCtx);
    void DistanceTransformAbsPBA(const Pixel8uC1 &nMinSiteValue, const Pixel8uC1 &nMaxSiteValue, Image16sC1View &pDstVoronoi, Image16sC1View &pDstVoronoiIndices, Image16uC1View &pDstVoronoiAbsoluteManhattanDistances, Image64fC1View &pDstTransform, cuda::DevVarView<byte> &pDeviceBuffer, cuda::DevVarView<byte> &pAntialiasingDeviceBuffer, const NppStreamContext &nppStreamCtx);
    void FilterCannyBorder(Image8uC1View &pDst, NppiDifferentialKernel eFilterType, NppiMaskSize eMaskSize, Npp16s nLowThreshold, Npp16s nHighThreshold, NppiNorm eNorm, NppiBorderType eBorderType, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx, const Roi&aFilterArea = Roi()) const;
    void FilterHarrisCornersBorder(Image32fC1View &pDst, NppiDifferentialKernel eFilterType, NppiMaskSize eMaskSize, NppiMaskSize eAvgWindowSize, Npp32f nK, Npp32f nScale, NppiBorderType eBorderType, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx, const Roi&aFilterArea = Roi()) const;
    void FilterHoughLine(NppPointPolar nDelta, int nThreshold, NppPointPolar *pDeviceLines, int nMaxLineCount, int *pDeviceLineCount, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;
    void FilterHoughLineRegion(NppPointPolar nDelta, int nThreshold, NppPointPolar *pDeviceLines, NppPointPolar oDstROI[2], int nMaxLineCount, int *pDeviceLineCount, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;
    void HistogramOfGradientsBorder(const NppiPoint *hpLocations, int nLocations, Npp32f *pDstWindowDescriptorBuffer, const NppiHOGConfig oHOGConfig, cuda::DevVarView<byte> &pScratchBuffer, NppiBorderType eBorderType, const NppStreamContext &nppStreamCtx, const Roi&aFilterArea = Roi()) const;
    void FloodFill(NppiPoint oSeed, const Pixel8uC1 &nNewValue, NppiNorm eNorm, NppiConnectedRegion *pConnectedRegion, cuda::DevVarView<byte> &pBuffer, const NppStreamContext &nppStreamCtx);
    void FloodFillBoundary(NppiPoint oSeed, const Pixel8uC1 &nNewValue, const Pixel8uC1 &nBoundaryValue, NppiNorm eNorm, NppiConnectedRegion *pConnectedRegion, cuda::DevVarView<byte> &pBuffer, const NppStreamContext &nppStreamCtx);
    void FloodFillRange(NppiPoint oSeed, const Pixel8uC1 &nMin, const Pixel8uC1 &nMax, const Pixel8uC1 &nNewValue, NppiNorm eNorm, NppiConnectedRegion *pConnectedRegion, cuda::DevVarView<byte> &pBuffer, const NppStreamContext &nppStreamCtx);
    void FloodFillRangeBoundary(NppiPoint oSeed, const Pixel8uC1 &nMin, const Pixel8uC1 &nMax, const Pixel8uC1 &nNewValue, const Pixel8uC1 &nBoundaryValue, NppiNorm eNorm, NppiConnectedRegion *pConnectedRegion, cuda::DevVarView<byte> &pBuffer, const NppStreamContext &nppStreamCtx);
    void FloodFillGradient(NppiPoint oSeed, const Pixel8uC1 &nMin, const Pixel8uC1 &nMax, const Pixel8uC1 &nNewValue, NppiNorm eNorm, NppiConnectedRegion *pConnectedRegion, cuda::DevVarView<byte> &pBuffer, const NppStreamContext &nppStreamCtx);
    void FloodFillGradientBoundary(NppiPoint oSeed, const Pixel8uC1 &nMin, const Pixel8uC1 &nMax, const Pixel8uC1 &nNewValue, const Pixel8uC1 &nBoundaryValue, NppiNorm eNorm, NppiConnectedRegion *pConnectedRegion, cuda::DevVarView<byte> &pBuffer, const NppStreamContext &nppStreamCtx);
    void LabelMarkersUF(Image32uC1View &pDst, NppiNorm eNorm, cuda::DevVarView<byte> &pBuffer, const NppStreamContext &nppStreamCtx);
    [[nodiscard]] size_t SegmentWatershedGetBufferSize() const;
    void SegmentWatershed(const Image32uC1View &pMarkerLabels, NppiNorm eNorm, NppiWatershedSegmentBoundaryType eSegmentBoundaryType, cuda::DevVarView<byte> &pDeviceMemoryBuffer, const NppStreamContext &nppStreamCtx);
    void Sum(cuda::DevVarView<byte> &pDeviceBuffer, cuda::DevVarView<double> &pSum, const NppStreamContext &nppStreamCtx) const;
    void Sum(cuda::DevVarView<byte> &pDeviceBuffer, cuda::DevVarView<long64> &pSum, const NppStreamContext &nppStreamCtx) const;
    [[nodiscard]] size_t SumGetBufferHostSize(const NppStreamContext &nppStreamCtx) const;
    [[nodiscard]] size_t SumGetBufferHostSize64(const NppStreamContext &nppStreamCtx) const;
    void Min(cuda::DevVarView<byte> &pDeviceBuffer, cuda::DevVarView<byte> &pMin, const NppStreamContext &nppStreamCtx) const;
    [[nodiscard]] size_t MinGetBufferHostSize(const NppStreamContext &nppStreamCtx) const;
    void MinIndx(cuda::DevVarView<byte> &pDeviceBuffer, cuda::DevVarView<byte> &pMin, cuda::DevVarView<int> &pIndexX, cuda::DevVarView<int> &pIndexY, const NppStreamContext &nppStreamCtx) const;
    [[nodiscard]] size_t MinIndxGetBufferHostSize(const NppStreamContext &nppStreamCtx) const;
    void Max(cuda::DevVarView<byte> &pDeviceBuffer, cuda::DevVarView<byte> &pMax, const NppStreamContext &nppStreamCtx) const;
    [[nodiscard]] size_t MaxGetBufferHostSize(const NppStreamContext &nppStreamCtx) const;
    void MaxIndx(cuda::DevVarView<byte> &pDeviceBuffer, cuda::DevVarView<byte> &pMax, cuda::DevVarView<int> &pIndexX, cuda::DevVarView<int> &pIndexY, const NppStreamContext &nppStreamCtx) const;
    [[nodiscard]] size_t MaxIndxGetBufferHostSize(const NppStreamContext &nppStreamCtx) const;
    void MinMax(cuda::DevVarView<byte> &pMin, cuda::DevVarView<byte> &pMax, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;
    [[nodiscard]] size_t MinMaxGetBufferHostSize(const NppStreamContext &nppStreamCtx) const;
    void MinMaxIndx(cuda::DevVarView<byte> &pMinValue, cuda::DevVarView<byte> &pMaxValue, cuda::DevVarView<NppiPoint> &pMinIndex, cuda::DevVarView<NppiPoint> &pMaxIndex, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;
    void MinMaxIndx(const Image8uC1View &pMask, cuda::DevVarView<byte> &pMinValue, cuda::DevVarView<byte> &pMaxValue, cuda::DevVarView<NppiPoint> &pMinIndex, cuda::DevVarView<NppiPoint> &pMaxIndex, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;
    [[nodiscard]] size_t MinMaxIndxGetBufferHostSize(const NppStreamContext &nppStreamCtx) const;
    [[nodiscard]] size_t MinMaxIndxGetBufferHostSizeMasked(const NppStreamContext &nppStreamCtx) const;
    void Mean(cuda::DevVarView<byte> &pDeviceBuffer, cuda::DevVarView<double> &pMean, const NppStreamContext &nppStreamCtx) const;
    void Mean(const Image8uC1View &pMask, cuda::DevVarView<byte> &pDeviceBuffer, cuda::DevVarView<double> &pMean, const NppStreamContext &nppStreamCtx) const;
    [[nodiscard]] size_t MeanGetBufferHostSize(const NppStreamContext &nppStreamCtx) const;
    [[nodiscard]] size_t MeanGetBufferHostSizeMasked(const NppStreamContext &nppStreamCtx) const;
    void Mean_StdDev(cuda::DevVarView<byte> &pDeviceBuffer, cuda::DevVarView<double> &pMean, cuda::DevVarView<double> &pStdDev, const NppStreamContext &nppStreamCtx) const;
    void Mean_StdDev(const Image8uC1View &pMask, cuda::DevVarView<byte> &pDeviceBuffer, cuda::DevVarView<double> &pMean, cuda::DevVarView<double> &pStdDev, const NppStreamContext &nppStreamCtx) const;
    [[nodiscard]] size_t MeanStdDevGetBufferHostSize(const NppStreamContext &nppStreamCtx) const;
    [[nodiscard]] size_t MeanStdDevGetBufferHostSizeMasked(const NppStreamContext &nppStreamCtx) const;
    void Norm_Inf(cuda::DevVarView<double> &pNorm, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;
    void Norm_Inf(const Image8uC1View &pMask, cuda::DevVarView<double> &pNorm, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;
    [[nodiscard]] size_t NormInfGetBufferHostSize(const NppStreamContext &nppStreamCtx) const;
    [[nodiscard]] size_t NormInfGetBufferHostSizeMasked(const NppStreamContext &nppStreamCtx) const;
    void Norm_L1(cuda::DevVarView<double> &pNorm, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;
    void Norm_L1(const Image8uC1View &pMask, cuda::DevVarView<double> &pNorm, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;
    [[nodiscard]] size_t NormL1GetBufferHostSize(const NppStreamContext &nppStreamCtx) const;
    [[nodiscard]] size_t NormL1GetBufferHostSizeMasked(const NppStreamContext &nppStreamCtx) const;
    void Norm_L2(cuda::DevVarView<double> &pNorm, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;
    void Norm_L2(const Image8uC1View &pMask, cuda::DevVarView<double> &pNorm, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;
    [[nodiscard]] size_t NormL2GetBufferHostSize(const NppStreamContext &nppStreamCtx) const;
    [[nodiscard]] size_t NormL2GetBufferHostSizeMasked(const NppStreamContext &nppStreamCtx) const;
    void NormDiff_Inf(const Image8uC1View &pSrc2, cuda::DevVarView<double> &pNormDiff, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;
    void NormDiff_Inf(const Image8uC1View &pSrc2, const Image8uC1View &pMask, cuda::DevVarView<double> &pNormDiff, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;
    [[nodiscard]] size_t NormDiffInfGetBufferHostSize(const NppStreamContext &nppStreamCtx) const;
    [[nodiscard]] size_t NormDiffInfGetBufferHostSizeMasked(const NppStreamContext &nppStreamCtx) const;
    void NormDiff_L1(const Image8uC1View &pSrc2, cuda::DevVarView<double> &pNormDiff, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;
    void NormDiff_L1(const Image8uC1View &pSrc2, const Image8uC1View &pMask, cuda::DevVarView<double> &pNormDiff, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;
    [[nodiscard]] size_t NormDiffL1GetBufferHostSize(const NppStreamContext &nppStreamCtx) const;
    [[nodiscard]] size_t NormDiffL1GetBufferHostSizeMasked(const NppStreamContext &nppStreamCtx) const;
    void NormDiff_L2(const Image8uC1View &pSrc2, cuda::DevVarView<double> &pNormDiff, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;
    void NormDiff_L2(const Image8uC1View &pSrc2, const Image8uC1View &pMask, cuda::DevVarView<double> &pNormDiff, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;
    [[nodiscard]] size_t NormDiffL2GetBufferHostSize(const NppStreamContext &nppStreamCtx) const;
    [[nodiscard]] size_t NormDiffL2GetBufferHostSizeMasked(const NppStreamContext &nppStreamCtx) const;
    void NormRel_Inf(const Image8uC1View &pSrc2, cuda::DevVarView<double> &pNormRel, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;
    void NormRel_Inf(const Image8uC1View &pSrc2, const Image8uC1View &pMask, cuda::DevVarView<double> &pNormRel, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;
    [[nodiscard]] size_t NormRelInfGetBufferHostSize(const NppStreamContext &nppStreamCtx) const;
    [[nodiscard]] size_t NormRelInfGetBufferHostSizeMasked(const NppStreamContext &nppStreamCtx) const;
    void NormRel_L1(const Image8uC1View &pSrc2, cuda::DevVarView<double> &pNormRel, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;
    void NormRel_L1(const Image8uC1View &pSrc2, const Image8uC1View &pMask, cuda::DevVarView<double> &pNormRel, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;
    [[nodiscard]] size_t NormRelL1GetBufferHostSize(const NppStreamContext &nppStreamCtx) const;
    [[nodiscard]] size_t NormRelL1GetBufferHostSizeMasked(const NppStreamContext &nppStreamCtx) const;
    void NormRel_L2(const Image8uC1View &pSrc2, cuda::DevVarView<double> &pNormRel, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;
    void NormRel_L2(const Image8uC1View &pSrc2, const Image8uC1View &pMask, cuda::DevVarView<double> &pNormRel, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;
    [[nodiscard]] size_t NormRelL2GetBufferHostSize(const NppStreamContext &nppStreamCtx) const;
    [[nodiscard]] size_t NormRelL2GetBufferHostSizeMasked(const NppStreamContext &nppStreamCtx) const;
    void DotProd(const Image8uC1View &pSrc2, Npp64f *pDp, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;
    [[nodiscard]] size_t DotProdGetBufferHostSize(const NppStreamContext &nppStreamCtx) const;
    void CountInRange(cuda::DevVarView<int> &pCounts, const Pixel8uC1 &nLowerBound, const Pixel8uC1 &nUpperBound, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;
    [[nodiscard]] size_t CountInRangeGetBufferHostSize(const NppStreamContext &nppStreamCtx) const;
    void MaxEvery(const Image8uC1View &pSrc, const NppStreamContext &nppStreamCtx);
    void MinEvery(const Image8uC1View &pSrc, const NppStreamContext &nppStreamCtx);
    void Integral(Image32sC1View &pDst, Npp32s nVal, const NppStreamContext &nppStreamCtx) const;
    void Integral(Image32fC1View &pDst, Npp32f nVal, const NppStreamContext &nppStreamCtx) const;
    void SqrIntegral(Image32sC1View &pDst, const Image32sC1View &pSqr, Npp32s nVal, Npp32s nValSqr, const NppStreamContext &nppStreamCtx) const;
    void SqrIntegral(Image32sC1View &pDst, const Image64fC1View &pSqr, Npp32s nVal, Npp64f nValSqr, const NppStreamContext &nppStreamCtx) const;
    void SqrIntegral(Image32fC1View &pDst, const Image64fC1View &pSqr, Npp32f nVal, Npp64f nValSqr, const NppStreamContext &nppStreamCtx) const;
    void HistogramEven(cuda::DevVarView<int> &pHist, int nLevels, Npp32s nLowerLevel, Npp32s nUpperLevel, cuda::DevVarView<byte> &pBuffer, const NppStreamContext &nppStreamCtx) const;
    [[nodiscard]] size_t HistogramEvenGetBufferSize(int nLevels, const NppStreamContext &nppStreamCtx) const;
    void HistogramRange(cuda::DevVarView<int> &pHist, const cuda::DevVarView<int> &pLevels, int nLevels, cuda::DevVarView<byte> &pBuffer, const NppStreamContext &nppStreamCtx) const;
    [[nodiscard]] size_t HistogramRangeGetBufferSize(int nLevels, const NppStreamContext &nppStreamCtx) const;
    void SqrDistanceFull_Norm(const Image8uC1View &pTpl, Image8uC1View &pDst, int nScaleFactor, const NppStreamContext &nppStreamCtx) const;
    void SqrDistanceFull_Norm(const Image8uC1View &pTpl, Image32fC1View &pDst, const NppStreamContext &nppStreamCtx) const;
    void SqrDistanceSame_Norm(const Image8uC1View &pTpl, Image8uC1View &pDst, int nScaleFactor, const NppStreamContext &nppStreamCtx) const;
    void SqrDistanceSame_Norm(const Image8uC1View &pTpl, Image32fC1View &pDst, const NppStreamContext &nppStreamCtx) const;
    void SqrDistanceValid_Norm(const Image8uC1View &pTpl, Image8uC1View &pDst, int nScaleFactor, const NppStreamContext &nppStreamCtx) const;
    void SqrDistanceValid_Norm(const Image8uC1View &pTpl, Image32fC1View &pDst, const NppStreamContext &nppStreamCtx) const;
    void CrossCorrFull_Norm(const Image8uC1View &pTpl, Image8uC1View &pDst, int nScaleFactor, const NppStreamContext &nppStreamCtx) const;
    void CrossCorrFull_Norm(const Image8uC1View &pTpl, Image32fC1View &pDst, const NppStreamContext &nppStreamCtx) const;
    void CrossCorrSame_Norm(const Image8uC1View &pTpl, Image8uC1View &pDst, int nScaleFactor, const NppStreamContext &nppStreamCtx) const;
    void CrossCorrSame_Norm(const Image8uC1View &pTpl, Image32fC1View &pDst, const NppStreamContext &nppStreamCtx) const;
    void CrossCorrValid_Norm(const Image8uC1View &pTpl, Image8uC1View &pDst, int nScaleFactor, const NppStreamContext &nppStreamCtx) const;
    void CrossCorrValid_Norm(const Image8uC1View &pTpl, Image32fC1View &pDst, const NppStreamContext &nppStreamCtx) const;
    void CrossCorrValid(const Image8uC1View &pTpl, Image32fC1View &pDst, const NppStreamContext &nppStreamCtx) const;
    void CrossCorrFull_NormLevel(const Image8uC1View &pTpl, Image8uC1View &pDst, int nScaleFactor, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;
    void CrossCorrFull_NormLevel(const Image8uC1View &pTpl, Image32fC1View &pDst, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;
    [[nodiscard]] size_t FullNormLevelGetBufferHostSize(const NppStreamContext &nppStreamCtx) const;
    [[nodiscard]] size_t FullNormLevelGetBufferHostSize32f(const NppStreamContext &nppStreamCtx) const;
    void CrossCorrSame_NormLevel(const Image8uC1View &pTpl, Image8uC1View &pDst, int nScaleFactor, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;
    void CrossCorrSame_NormLevel(const Image8uC1View &pTpl, Image32fC1View &pDst, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;
    [[nodiscard]] size_t SameNormLevelGetBufferHostSize(const NppStreamContext &nppStreamCtx) const;
    [[nodiscard]] size_t SameNormLevelGetBufferHostSize32f(const NppStreamContext &nppStreamCtx) const;
    void CrossCorrValid_NormLevel(const Image8uC1View &pTpl, Image8uC1View &pDst, int nScaleFactor, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;
    void CrossCorrValid_NormLevel(const Image8uC1View &pTpl, Image32fC1View &pDst, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;
    [[nodiscard]] size_t ValidNormLevelGetBufferHostSize(const NppStreamContext &nppStreamCtx) const;
    [[nodiscard]] size_t ValidNormLevelGetBufferHostSize32f(const NppStreamContext &nppStreamCtx) const;
    void CrossCorrFull_NormLevelAdvanced(const Image8uC1View &pTpl, Image32fC1View &pDst, cuda::DevVarView<byte> &pDeviceBuffer, cuda::DevVarView<byte> &pAdvancedScratchBuffer, const NppStreamContext &nppStreamCtx) const;
    void CrossCorrSame_NormLevelAdvanced(const Image8uC1View &pTpl, Image32fC1View &pDst, cuda::DevVarView<byte> &pDeviceBuffer, cuda::DevVarView<byte> &pAdvancedScratchBuffer, const NppStreamContext &nppStreamCtx) const;
    void CrossCorrValid_NormLevelAdvanced(const Image8uC1View &pTpl, Image32fC1View &pDst, cuda::DevVarView<byte> &pDeviceBuffer, cuda::DevVarView<byte> &pAdvancedScratchBuffer, const NppStreamContext &nppStreamCtx) const;
    void QualityIndex(const Image8uC1View &pSrc2, NppiSize oRoiSize, cuda::DevVarView<float> &pDst, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;
    [[nodiscard]] size_t QualityIndexGetBufferHostSize(const NppStreamContext &nppStreamCtx) const;
    void MaximumError(const Image8uC1View &pSrc2, cuda::DevVarView<double> &pError, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;
    [[nodiscard]] size_t MaximumErrorGetBufferHostSize(const NppStreamContext &nppStreamCtx) const;
    void AverageError(const Image8uC1View &pSrc2, cuda::DevVarView<double> &pError, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;
    [[nodiscard]] size_t AverageErrorGetBufferHostSize(const NppStreamContext &nppStreamCtx) const;
    void MaximumRelativeError(const Image8uC1View &pSrc2, cuda::DevVarView<double> &pError, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;
    [[nodiscard]] size_t MaximumRelativeErrorGetBufferHostSize(const NppStreamContext &nppStreamCtx) const;
    void AverageRelativeError(const Image8uC1View &pSrc2, cuda::DevVarView<double> &pError, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;
    [[nodiscard]] size_t AverageRelativeErrorGetBufferHostSize(const NppStreamContext &nppStreamCtx) const;
    void MSE(const Image8uC1View &pSrc2, cuda::DevVarView<float> &pMSE, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;
    void PSNR(const Image8uC1View &pSrc2, cuda::DevVarView<float> &pPSNR, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;
    void SSIM(const Image8uC1View &pSrc2, cuda::DevVarView<float> &pSSIM, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;
    void MSSSIM(const Image8uC1View &pSrc2, cuda::DevVarView<float> &pMSSSIM, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;
    void WMSSSIM(const Image8uC1View &pSrc2, cuda::DevVarView<float> &pMSSSIM, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;
    [[nodiscard]] size_t MSEGetBufferHostSize(const NppStreamContext &nppStreamCtx) const;
    [[nodiscard]] size_t PSNRGetBufferHostSize(const NppStreamContext &nppStreamCtx) const;
    [[nodiscard]] size_t SSIMGetBufferHostSize(const NppStreamContext &nppStreamCtx) const;
    [[nodiscard]] size_t MSSSIMGetBufferHostSize(const NppStreamContext &nppStreamCtx) const;
    [[nodiscard]] size_t WMSSSIMGetBufferHostSize(const NppStreamContext &nppStreamCtx) const;
    void ResizeSqrPixel(Image8uC1View &pDst, double nXFactor, double nYFactor, double nXShift, double nYShift, int eInterpolation, const NppStreamContext &nppStreamCtx) const;
    [[nodiscard]] size_t ResizeAdvancedGetBufferHostSize(const Image8uC1View &oDstROI, int eInterpolationMode) const;
    void ResizeSqrPixel(Image8uC1View &pDst, double nXFactor, double nYFactor, cuda::DevVarView<byte> &pBuffer, int eInterpolationMode, const NppStreamContext &nppStreamCtx) const;
    void Resize(Image8uC1View &pDst, int eInterpolation, const NppStreamContext &nppStreamCtx) const;
    void Remap(const Image32fC1View &pXMap, const Image32fC1View &pYMap, Image8uC1View &pDst, int eInterpolation, const NppStreamContext &nppStreamCtx) const;
    void Rotate(Image8uC1View &pDst, double nAngle, double nShiftX, double nShiftY, int eInterpolation, const NppStreamContext &nppStreamCtx) const;
    void Mirror(Image8uC1View &pDst, NppiAxis flip, const NppStreamContext &nppStreamCtx) const;
    void Mirror(NppiAxis flip, const NppStreamContext &nppStreamCtx);
    void WarpAffine(Image8uC1View &pDst, const double aCoeffs[2][3], int eInterpolation, const NppStreamContext &nppStreamCtx) const;
    void WarpAffineBack(Image8uC1View &pDst, const double aCoeffs[2][3], int eInterpolation, const NppStreamContext &nppStreamCtx) const;
    void WarpAffineQuad(const double aSrcQuad[4][2], Image8uC1View &pDst, const double aDstQuad[4][2], int eInterpolation, const NppStreamContext &nppStreamCtx) const;
    void WarpPerspective(Image8uC1View &pDst, const double aCoeffs[3][3], int eInterpolation, const NppStreamContext &nppStreamCtx) const;
    void WarpPerspectiveBack(Image8uC1View &pDst, const double aCoeffs[3][3], int eInterpolation, const NppStreamContext &nppStreamCtx) const;
    void WarpPerspectiveQuad(const double aSrcQuad[4][2], Image8uC1View &pDst, const double aDstQuad[4][2], int eInterpolation, const NppStreamContext &nppStreamCtx) const;

    //NOLINTEND(readability-identifier-naming,readability-avoid-const-params-in-decls)
};
} // namespace opp::image::npp
