// Code automatically generated by nppCodeGenerator - do not modify manually

#pragma once
#include "../dllexport_npp.h"
#include "imageView.h"
#include <backends/cuda/devVarView.h>
#include <backends/npp/nppException.h>
#include <common/image/pixelTypes.h>
#include <common/image/roi.h>
#include <common/image/roiException.h>
#include <common/image/size2D.h>
#include <common/image/sizePitched.h>

namespace mpp::image::npp
{
// forward declaration:

class MPPEXPORT_NPP Image16fC2View : public ImageView<Pixel16fC2>
{
  protected:
    Image16fC2View() = default;
    explicit Image16fC2View(const Size2D &aSize);

  public:
    Image16fC2View(Pixel16fC2 *aBasePointer, const SizePitched &aSizeAlloc);
    Image16fC2View(Pixel16fC2 *aBasePointer, const SizePitched &aSizeAlloc, const Roi &aRoi);
    ~Image16fC2View() override = default;

    Image16fC2View(const Image16fC2View &)     = default;
    Image16fC2View(Image16fC2View &&) noexcept = default;

    Image16fC2View &operator=(const Image16fC2View &)     = default;
    Image16fC2View &operator=(Image16fC2View &&) noexcept = default;

    /// <summary>
    /// Returns a new Image16fC2View with the new ROI
    /// </summary>
    [[nodiscard]] Image16fC2View GetView(const Roi &aRoi);

    /// <summary>
    /// Returns a new ImageView with the current ROI adapted by aBorder
    /// </summary>
    [[nodiscard]] Image16fC2View GetView(const Border &aBorder = Border());

    //NOLINTBEGIN(readability-identifier-naming,readability-avoid-const-params-in-decls, bugprone-easily-swappable-parameters, readability-convert-member-functions-to-static)

    // NppStatus nppiSet_16f_C2R_Ctx(const Npp32f[2] aValues, Npp16f * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC2View &Set(const Pixel32fC2 &aValues, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiColorTwist32f_16f_C2R_Ctx(const Npp16f * pSrc, int nSrcStep, Npp16f * pDst, int nDstStep, NppiSize oSizeROI, const Npp32f[3][4] aTwist, NppStreamContext nppStreamCtx)
    Image16fC2View &ColorTwist32f(Image16fC2View &pDst, const Npp32f aTwist[3][4], const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiColorTwist32f_16f_C2IR_Ctx(Npp16f * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, const Npp32f[3][4] aTwist, NppStreamContext nppStreamCtx)
    Image16fC2View &ColorTwist32f(const Npp32f aTwist[3][4], const NppStreamContext &nppStreamCtx);

    //NOLINTEND(readability-identifier-naming,readability-avoid-const-params-in-decls, bugprone-easily-swappable-parameters, readability-convert-member-functions-to-static)
};
} // namespace mpp::image::npp
