// Code automatically generated by nppCodeGenerator - do not modify manually

#pragma once
#include <common/moduleEnabler.h>
#if OPP_ENABLE_NPP_BACKEND
#include <common/image/pixelTypeEnabler.h>

#include "imageView.h"
#include <backends/cuda/devVarView.h>
#include <backends/npp/nppException.h>
#include <common/image/pixelTypes.h>
#include <common/image/roi.h>
#include <common/image/roiException.h>
#include <common/image/size2D.h>
#include <common/image/sizePitched.h>

namespace opp::image::npp
{
// forward declaration:
class Image32fC4View;

class Image16fC4View : public ImageView<Pixel16fC4>
{
  protected:
    Image16fC4View() = default;
    explicit Image16fC4View(const Size2D &aSize);

  public:
    Image16fC4View(Pixel16fC4 *aBasePointer, const SizePitched &aSizeAlloc);
    Image16fC4View(Pixel16fC4 *aBasePointer, const SizePitched &aSizeAlloc, const Roi &aRoi);
    ~Image16fC4View() = default;

    Image16fC4View(const Image16fC4View &)     = default;
    Image16fC4View(Image16fC4View &&) noexcept = default;

    Image16fC4View &operator=(const Image16fC4View &)     = default;
    Image16fC4View &operator=(Image16fC4View &&) noexcept = default;

    /// <summary>
    /// Returns a new Image16fC4View with the new ROI
    /// </summary>
    [[nodiscard]] Image16fC4View GetView(const Roi &aRoi) const;

    /// <summary>
    /// Returns a new ImageView with the current ROI adapted by aBorder
    /// </summary>
    [[nodiscard]] Image16fC4View GetView(const Border &aBorder = Border()) const;

    //NOLINTBEGIN(readability-identifier-naming,readability-avoid-const-params-in-decls, bugprone-easily-swappable-parameters, readability-convert-member-functions-to-static)
#if OPPi_ENABLE_HALFFLOAT16_TYPE && OPPi_ENABLE_FOUR_CHANNEL

    // NppStatus nppiSet_16f_C4R_Ctx(const Npp32f[4] aValues, Npp16f * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC4View &Set(const Pixel32fC4 &aValues, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiCopy_16f_C4R_Ctx(const Npp16f * pSrc, int nSrcStep, Npp16f * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC4View &Copy(Image16fC4View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiConvert_16f32f_C4R_Ctx(const Npp16f * pSrc, int nSrcStep, Npp32f * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image32fC4View &Convert(Image32fC4View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiAddC_16f_C4R_Ctx(const Npp16f * pSrc1, int nSrc1Step, const Npp32f[4] aConstants, Npp16f * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC4View &Add(const Pixel32fC4 &aConstants, Image16fC4View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiAddDeviceC_16f_C4R_Ctx(const Npp16f * pSrc1, int nSrc1Step, const Npp32f * pConstants, Npp16f * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC4View &Add(const cuda::DevVarView<Pixel16fC4> &pConstants, Image16fC4View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiAddC_16f_C4IR_Ctx(const Npp32f[4] aConstants, Npp16f * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC4View &Add(const Pixel32fC4 &aConstants, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiAddDeviceC_16f_C4IR_Ctx(const Npp32f * pConstants, Npp16f * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC4View &Add(const cuda::DevVarView<Pixel16fC4> &pConstants, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiMulC_16f_C4R_Ctx(const Npp16f * pSrc1, int nSrc1Step, const Npp32f[4] aConstants, Npp16f * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC4View &Mul(const Pixel32fC4 &aConstants, Image16fC4View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiMulDeviceC_16f_C4R_Ctx(const Npp16f * pSrc1, int nSrc1Step, const Npp32f * pConstants, Npp16f * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC4View &Mul(const cuda::DevVarView<Pixel16fC4> &pConstants, Image16fC4View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiMulC_16f_C4IR_Ctx(const Npp32f[4] aConstants, Npp16f * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC4View &Mul(const Pixel32fC4 &aConstants, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiMulDeviceC_16f_C4IR_Ctx(const Npp32f * pConstants, Npp16f * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC4View &Mul(const cuda::DevVarView<Pixel16fC4> &pConstants, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiSubC_16f_C4R_Ctx(const Npp16f * pSrc1, int nSrc1Step, const Npp32f[4] aConstants, Npp16f * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC4View &Sub(const Pixel32fC4 &aConstants, Image16fC4View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiSubDeviceC_16f_C4R_Ctx(const Npp16f * pSrc1, int nSrc1Step, const Npp32f * pConstants, Npp16f * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC4View &Sub(const cuda::DevVarView<Pixel16fC4> &pConstants, Image16fC4View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiSubC_16f_C4IR_Ctx(const Npp32f[4] aConstants, Npp16f * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC4View &Sub(const Pixel32fC4 &aConstants, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiSubDeviceC_16f_C4IR_Ctx(const Npp32f * pConstants, Npp16f * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC4View &Sub(const cuda::DevVarView<Pixel16fC4> &pConstants, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiDivC_16f_C4R_Ctx(const Npp16f * pSrc1, int nSrc1Step, const Npp32f[4] aConstants, Npp16f * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC4View &Div(const Pixel32fC4 &aConstants, Image16fC4View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiDivDeviceC_16f_C4R_Ctx(const Npp16f * pSrc1, int nSrc1Step, const Npp32f * pConstants, Npp16f * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC4View &Div(const cuda::DevVarView<Pixel16fC4> &pConstants, Image16fC4View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiDivC_16f_C4IR_Ctx(const Npp32f[4] aConstants, Npp16f * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC4View &Div(const Pixel32fC4 &aConstants, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiDivDeviceC_16f_C4IR_Ctx(const Npp32f * pConstants, Npp16f * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC4View &Div(const cuda::DevVarView<Pixel16fC4> &pConstants, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiAdd_16f_C4R_Ctx(const Npp16f * pSrc1, int nSrc1Step, const Npp16f * pSrc2, int nSrc2Step, Npp16f * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC4View &Add(const Image16fC4View &pSrc2, Image16fC4View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiAdd_16f_C4IR_Ctx(const Npp16f * pSrc, int nSrcStep, Npp16f * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC4View &Add(const Image16fC4View &pSrc, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiMul_16f_C4R_Ctx(const Npp16f * pSrc1, int nSrc1Step, const Npp16f * pSrc2, int nSrc2Step, Npp16f * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC4View &Mul(const Image16fC4View &pSrc2, Image16fC4View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiMul_16f_C4IR_Ctx(const Npp16f * pSrc, int nSrcStep, Npp16f * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC4View &Mul(const Image16fC4View &pSrc, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiSub_16f_C4R_Ctx(const Npp16f * pSrc1, int nSrc1Step, const Npp16f * pSrc2, int nSrc2Step, Npp16f * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC4View &Sub(const Image16fC4View &pSrc2, Image16fC4View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiSub_16f_C4IR_Ctx(const Npp16f * pSrc, int nSrcStep, Npp16f * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC4View &Sub(const Image16fC4View &pSrc, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiDiv_16f_C4R_Ctx(const Npp16f * pSrc1, int nSrc1Step, const Npp16f * pSrc2, int nSrc2Step, Npp16f * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC4View &Div(const Image16fC4View &pSrc2, Image16fC4View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiDiv_16f_C4IR_Ctx(const Npp16f * pSrc, int nSrcStep, Npp16f * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC4View &Div(const Image16fC4View &pSrc, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiAbs_16f_C4R_Ctx(const Npp16f * pSrc, int nSrcStep, Npp16f * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC4View &Abs(Image16fC4View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiAbs_16f_C4IR_Ctx(Npp16f * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC4View &Abs(const NppStreamContext &nppStreamCtx);

    // NppStatus nppiSqr_16f_C4R_Ctx(const Npp16f * pSrc, int nSrcStep, Npp16f * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC4View &Sqr(Image16fC4View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiSqr_16f_C4IR_Ctx(Npp16f * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC4View &Sqr(const NppStreamContext &nppStreamCtx);

    // NppStatus nppiSqrt_16f_C4R_Ctx(const Npp16f * pSrc, int nSrcStep, Npp16f * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC4View &Sqrt(Image16fC4View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiSqrt_16f_C4IR_Ctx(Npp16f * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image16fC4View &Sqrt(const NppStreamContext &nppStreamCtx);

    // NppStatus nppiColorTwist32f_16f_C4R_Ctx(const Npp16f * pSrc, int nSrcStep, Npp16f * pDst, int nDstStep, NppiSize oSizeROI, const Npp32f[3][4] aTwist, NppStreamContext nppStreamCtx)
    Image16fC4View &ColorTwist32f(Image16fC4View &pDst, const Npp32f aTwist[3][4], const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiColorTwist32f_16f_C4IR_Ctx(Npp16f * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, const Npp32f[3][4] aTwist, NppStreamContext nppStreamCtx)
    Image16fC4View &ColorTwist32f(const Npp32f aTwist[3][4], const NppStreamContext &nppStreamCtx);

    // NppStatus nppiColorTwist32fC_16f_C4R_Ctx(const Npp16f * pSrc, int nSrcStep, Npp16f * pDst, int nDstStep, NppiSize oSizeROI, const Npp32f[4][4] aTwist, const Npp32f[4] aConstants, NppStreamContext nppStreamCtx)
    Image16fC4View &ColorTwist32f(Image16fC4View &pDst, const Npp32f aTwist[4][4], const Pixel32fC4 &aConstants, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiColorTwist32fC_16f_C4IR_Ctx(Npp16f * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, const Npp32f[4][4] aTwist, const Npp32f[4] aConstants, NppStreamContext nppStreamCtx)
    Image16fC4View &ColorTwist32f(const Npp32f aTwist[4][4], const Pixel32fC4 &aConstants, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiFilter32f_16f_C4R_Ctx(const Npp16f * pSrc, int nSrcStep, Npp16f * pDst, int nDstStep, NppiSize oSizeROI, const Npp32f * pKernel, NppiSize oKernelSize, NppiPoint oAnchor, NppStreamContext nppStreamCtx)
    Image16fC4View &Filter32f(Image16fC4View &pDst, const cuda::DevVarView<float> &pKernel, NppiSize oKernelSize, NppiPoint oAnchor, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiFilterBorder32f_16f_C4R_Ctx(const Npp16f * pSrc, int nSrcStep, NppiSize oSrcSize, NppiPoint oSrcOffset, Npp16f * pDst, int nDstStep, NppiSize oSizeROI, const Npp32f * pKernel, NppiSize oKernelSize, NppiPoint oAnchor, NppiBorderType eBorderType, NppStreamContext nppStreamCtx)
    Image16fC4View &FilterBorder32f(Image16fC4View &pDst, const cuda::DevVarView<float> &pKernel, NppiSize oKernelSize, NppiPoint oAnchor, NppiBorderType eBorderType, const NppStreamContext &nppStreamCtx, const Roi &aFilterArea = Roi()) const;

    // NppStatus nppiResize_16f_C4R_Ctx(const Npp16f * pSrc, int nSrcStep, NppiSize oSrcSize, NppiRect oSrcRectROI, Npp16f * pDst, int nDstStep, NppiSize oDstSize, NppiRect oDstRectROI, int eInterpolation, NppStreamContext nppStreamCtx)
    Image16fC4View &Resize(Image16fC4View &pDst, int eInterpolation, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiWarpAffine_16f_C4R_Ctx(const Npp16f * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, Npp16f * pDst, int nDstStep, NppiRect oDstROI, const double[2][3] aCoeffs, int eInterpolation, NppStreamContext nppStreamCtx)
    Image16fC4View &WarpAffine(Image16fC4View &pDst, const double aCoeffs[2][3], int eInterpolation, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiWarpPerspective_16f_C4R_Ctx(const Npp16f * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, Npp16f * pDst, int nDstStep, NppiRect oDstROI, const double[3][3] aCoeffs, int eInterpolation, NppStreamContext nppStreamCtx)
    Image16fC4View &WarpPerspective(Image16fC4View &pDst, const double aCoeffs[3][3], int eInterpolation, const NppStreamContext &nppStreamCtx) const;

#endif // OPPi_ENABLE_HALFFLOAT16_TYPE && OPPi_ENABLE_FOUR_CHANNEL
    //NOLINTEND(readability-identifier-naming,readability-avoid-const-params-in-decls, bugprone-easily-swappable-parameters, readability-convert-member-functions-to-static)
};
} // namespace opp::image::npp
#endif // OPP_ENABLE_NPP_BACKEND
