// Code automatically generated by nppCodeGenerator - do not modify manually

#include "image16scC1View.h" //NOLINT
#include "imageView.h"  //NOLINT
#include <backends/cuda/devVarView.h> //NOLINT
#include <backends/npp/nppException.h>  //NOLINT
#include <common/defines.h> //NOLINT
#include <common/exception.h> //NOLINT
#include <common/image/affineTransformation.h> //NOLINT
#include <common/image/border.h> //NOLINT
#include <common/image/bound.h> //NOLINT
#include <common/image/matrix.h> //NOLINT
#include <common/image/pixelTypes.h> //NOLINT
#include <common/image/quad.h> //NOLINT
#include <common/image/roi.h> //NOLINT
#include <common/image/roiException.h>  //NOLINT
#include <common/image/size2D.h>  //NOLINT
#include <common/image/sizePitched.h>  //NOLINT
#include <common/safeCast.h>  //NOLINT
#include <cstddef> //NOLINT
#include <nppdefs.h>  //NOLINT
#include <nppi_arithmetic_and_logical_operations.h> //NOLINT
#include <nppi_data_exchange_and_initialization.h> //NOLINT
#include <nppi_statistics_functions.h> //NOLINT

namespace mpp::image::npp
{
Image16scC1View::Image16scC1View(const Size2D &aSize) : ImageView<Pixel16scC1>(aSize)
{
}

Image16scC1View::Image16scC1View(Pixel16scC1 *aBasePointer, const SizePitched &aSizeAlloc)
    : ImageView<Pixel16scC1>(aBasePointer, aSizeAlloc)
{
}
Image16scC1View::Image16scC1View(Pixel16scC1 *aBasePointer, const SizePitched &aSizeAlloc, const Roi &aRoi)
    : ImageView<Pixel16scC1>(aBasePointer, aSizeAlloc, aRoi)
{
}

Image16scC1View Image16scC1View::GetView(const Roi &aRoi)
{
    return {Pointer(), SizePitched(SizeAlloc(), Pitch()), aRoi};
}

Image16scC1View Image16scC1View::GetView(const Border &aBorder)
{
    const Roi newRoi = ROI() + aBorder;
    checkRoiIsInRoi(newRoi, Roi(0, 0, SizeAlloc()));
    return {Pointer(), SizePitched(SizeAlloc(), Pitch()), newRoi};
}

//NOLINTBEGIN(readability-identifier-naming,readability-avoid-const-params-in-decls, bugprone-easily-swappable-parameters, readability-convert-member-functions-to-static)

Image16scC1View &Image16scC1View::Set(const Pixel16scC1 &oValue, const NppStreamContext &nppStreamCtx)
{
    nppSafeCallExt(nppiSet_16sc_C1R_Ctx(*reinterpret_cast<const Npp16sc *>(&oValue), reinterpret_cast<Npp16sc *>(PointerRoi()), to_int(Pitch()), NppiSizeRoi(), nppStreamCtx),
                   "ROI SrcDst: " << ROI());
    return *this;
}

Image16scC1View &Image16scC1View::Copy(Image16scC1View &pDst, const NppStreamContext &nppStreamCtx) const
{
    checkSameSize(ROI(), pDst.ROI());
    nppSafeCallExt(nppiCopy_16sc_C1R_Ctx(reinterpret_cast<const Npp16sc *>(PointerRoi()), to_int(Pitch()), reinterpret_cast<Npp16sc *>(pDst.PointerRoi()), to_int(pDst.Pitch()), NppiSizeRoi(), nppStreamCtx),
                   "ROI Src: " << ROI() << "ROI Dst: " << pDst.ROI());
    return pDst;
}

Image16scC1View &Image16scC1View::Add(const Pixel16scC1 &nConstant, Image16scC1View &pDst, int nScaleFactor, const NppStreamContext &nppStreamCtx) const
{
    checkSameSize(ROI(), pDst.ROI());
    nppSafeCallExt(nppiAddC_16sc_C1RSfs_Ctx(reinterpret_cast<const Npp16sc *>(PointerRoi()), to_int(Pitch()), *reinterpret_cast<const Npp16sc *>(&nConstant), reinterpret_cast<Npp16sc *>(pDst.PointerRoi()), to_int(pDst.Pitch()), NppiSizeRoi(), nScaleFactor, nppStreamCtx),
                   "ROI Src: " << ROI() << "ROI Dst: " << pDst.ROI());
    return pDst;
}

Image16scC1View &Image16scC1View::Add(const Pixel16scC1 &nConstant, int nScaleFactor, const NppStreamContext &nppStreamCtx)
{
    nppSafeCallExt(nppiAddC_16sc_C1IRSfs_Ctx(*reinterpret_cast<const Npp16sc *>(&nConstant), reinterpret_cast<Npp16sc *>(PointerRoi()), to_int(Pitch()), NppiSizeRoi(), nScaleFactor, nppStreamCtx),
                   "ROI SrcDst: " << ROI());
    return *this;
}

Image16scC1View &Image16scC1View::Mul(const Pixel16scC1 &nConstant, Image16scC1View &pDst, int nScaleFactor, const NppStreamContext &nppStreamCtx) const
{
    checkSameSize(ROI(), pDst.ROI());
    nppSafeCallExt(nppiMulC_16sc_C1RSfs_Ctx(reinterpret_cast<const Npp16sc *>(PointerRoi()), to_int(Pitch()), *reinterpret_cast<const Npp16sc *>(&nConstant), reinterpret_cast<Npp16sc *>(pDst.PointerRoi()), to_int(pDst.Pitch()), NppiSizeRoi(), nScaleFactor, nppStreamCtx),
                   "ROI Src: " << ROI() << "ROI Dst: " << pDst.ROI());
    return pDst;
}

Image16scC1View &Image16scC1View::Mul(const Pixel16scC1 &nConstant, int nScaleFactor, const NppStreamContext &nppStreamCtx)
{
    nppSafeCallExt(nppiMulC_16sc_C1IRSfs_Ctx(*reinterpret_cast<const Npp16sc *>(&nConstant), reinterpret_cast<Npp16sc *>(PointerRoi()), to_int(Pitch()), NppiSizeRoi(), nScaleFactor, nppStreamCtx),
                   "ROI SrcDst: " << ROI());
    return *this;
}

Image16scC1View &Image16scC1View::Sub(const Pixel16scC1 &nConstant, Image16scC1View &pDst, int nScaleFactor, const NppStreamContext &nppStreamCtx) const
{
    checkSameSize(ROI(), pDst.ROI());
    nppSafeCallExt(nppiSubC_16sc_C1RSfs_Ctx(reinterpret_cast<const Npp16sc *>(PointerRoi()), to_int(Pitch()), *reinterpret_cast<const Npp16sc *>(&nConstant), reinterpret_cast<Npp16sc *>(pDst.PointerRoi()), to_int(pDst.Pitch()), NppiSizeRoi(), nScaleFactor, nppStreamCtx),
                   "ROI Src: " << ROI() << "ROI Dst: " << pDst.ROI());
    return pDst;
}

Image16scC1View &Image16scC1View::Sub(const Pixel16scC1 &nConstant, int nScaleFactor, const NppStreamContext &nppStreamCtx)
{
    nppSafeCallExt(nppiSubC_16sc_C1IRSfs_Ctx(*reinterpret_cast<const Npp16sc *>(&nConstant), reinterpret_cast<Npp16sc *>(PointerRoi()), to_int(Pitch()), NppiSizeRoi(), nScaleFactor, nppStreamCtx),
                   "ROI SrcDst: " << ROI());
    return *this;
}

Image16scC1View &Image16scC1View::Div(const Pixel16scC1 &nConstant, Image16scC1View &pDst, int nScaleFactor, const NppStreamContext &nppStreamCtx) const
{
    checkSameSize(ROI(), pDst.ROI());
    nppSafeCallExt(nppiDivC_16sc_C1RSfs_Ctx(reinterpret_cast<const Npp16sc *>(PointerRoi()), to_int(Pitch()), *reinterpret_cast<const Npp16sc *>(&nConstant), reinterpret_cast<Npp16sc *>(pDst.PointerRoi()), to_int(pDst.Pitch()), NppiSizeRoi(), nScaleFactor, nppStreamCtx),
                   "ROI Src: " << ROI() << "ROI Dst: " << pDst.ROI());
    return pDst;
}

Image16scC1View &Image16scC1View::Div(const Pixel16scC1 &nConstant, int nScaleFactor, const NppStreamContext &nppStreamCtx)
{
    nppSafeCallExt(nppiDivC_16sc_C1IRSfs_Ctx(*reinterpret_cast<const Npp16sc *>(&nConstant), reinterpret_cast<Npp16sc *>(PointerRoi()), to_int(Pitch()), NppiSizeRoi(), nScaleFactor, nppStreamCtx),
                   "ROI SrcDst: " << ROI());
    return *this;
}

Image16scC1View &Image16scC1View::Add(const Image16scC1View &pSrc2, Image16scC1View &pDst, int nScaleFactor, const NppStreamContext &nppStreamCtx) const
{
    checkSameSize(ROI(), pSrc2.ROI());
    checkSameSize(ROI(), pDst.ROI());
    nppSafeCallExt(nppiAdd_16sc_C1RSfs_Ctx(reinterpret_cast<const Npp16sc *>(PointerRoi()), to_int(Pitch()), reinterpret_cast<const Npp16sc *>(pSrc2.PointerRoi()), to_int(pSrc2.Pitch()), reinterpret_cast<Npp16sc *>(pDst.PointerRoi()), to_int(pDst.Pitch()), NppiSizeRoi(), nScaleFactor, nppStreamCtx),
                   "ROI Src1: " << ROI() << " ROI Src2: " << pSrc2.ROI() << "ROI Dst: " << pDst.ROI());
    return pDst;
}

Image16scC1View &Image16scC1View::Add(const Image16scC1View &pSrc, int nScaleFactor, const NppStreamContext &nppStreamCtx)
{
    checkSameSize(ROI(), pSrc.ROI());
    nppSafeCallExt(nppiAdd_16sc_C1IRSfs_Ctx(reinterpret_cast<const Npp16sc *>(pSrc.PointerRoi()), to_int(pSrc.Pitch()), reinterpret_cast<Npp16sc *>(PointerRoi()), to_int(Pitch()), NppiSizeRoi(), nScaleFactor, nppStreamCtx),
                   "ROI Src2: " << pSrc.ROI() << "ROI SrcDst: " << ROI());
    return *this;
}

Image16scC1View &Image16scC1View::Mul(const Image16scC1View &pSrc2, Image16scC1View &pDst, int nScaleFactor, const NppStreamContext &nppStreamCtx) const
{
    checkSameSize(ROI(), pSrc2.ROI());
    checkSameSize(ROI(), pDst.ROI());
    nppSafeCallExt(nppiMul_16sc_C1RSfs_Ctx(reinterpret_cast<const Npp16sc *>(PointerRoi()), to_int(Pitch()), reinterpret_cast<const Npp16sc *>(pSrc2.PointerRoi()), to_int(pSrc2.Pitch()), reinterpret_cast<Npp16sc *>(pDst.PointerRoi()), to_int(pDst.Pitch()), NppiSizeRoi(), nScaleFactor, nppStreamCtx),
                   "ROI Src1: " << ROI() << " ROI Src2: " << pSrc2.ROI() << "ROI Dst: " << pDst.ROI());
    return pDst;
}

Image16scC1View &Image16scC1View::Mul(const Image16scC1View &pSrc, int nScaleFactor, const NppStreamContext &nppStreamCtx)
{
    checkSameSize(ROI(), pSrc.ROI());
    nppSafeCallExt(nppiMul_16sc_C1IRSfs_Ctx(reinterpret_cast<const Npp16sc *>(pSrc.PointerRoi()), to_int(pSrc.Pitch()), reinterpret_cast<Npp16sc *>(PointerRoi()), to_int(Pitch()), NppiSizeRoi(), nScaleFactor, nppStreamCtx),
                   "ROI Src2: " << pSrc.ROI() << "ROI SrcDst: " << ROI());
    return *this;
}

Image16scC1View &Image16scC1View::Sub(const Image16scC1View &pSrc2, Image16scC1View &pDst, int nScaleFactor, const NppStreamContext &nppStreamCtx) const
{
    checkSameSize(ROI(), pSrc2.ROI());
    checkSameSize(ROI(), pDst.ROI());
    nppSafeCallExt(nppiSub_16sc_C1RSfs_Ctx(reinterpret_cast<const Npp16sc *>(PointerRoi()), to_int(Pitch()), reinterpret_cast<const Npp16sc *>(pSrc2.PointerRoi()), to_int(pSrc2.Pitch()), reinterpret_cast<Npp16sc *>(pDst.PointerRoi()), to_int(pDst.Pitch()), NppiSizeRoi(), nScaleFactor, nppStreamCtx),
                   "ROI Src1: " << ROI() << " ROI Src2: " << pSrc2.ROI() << "ROI Dst: " << pDst.ROI());
    return pDst;
}

Image16scC1View &Image16scC1View::Sub(const Image16scC1View &pSrc, int nScaleFactor, const NppStreamContext &nppStreamCtx)
{
    checkSameSize(ROI(), pSrc.ROI());
    nppSafeCallExt(nppiSub_16sc_C1IRSfs_Ctx(reinterpret_cast<const Npp16sc *>(pSrc.PointerRoi()), to_int(pSrc.Pitch()), reinterpret_cast<Npp16sc *>(PointerRoi()), to_int(Pitch()), NppiSizeRoi(), nScaleFactor, nppStreamCtx),
                   "ROI Src2: " << pSrc.ROI() << "ROI SrcDst: " << ROI());
    return *this;
}

Image16scC1View &Image16scC1View::Div(const Image16scC1View &pSrc2, Image16scC1View &pDst, int nScaleFactor, const NppStreamContext &nppStreamCtx) const
{
    checkSameSize(ROI(), pSrc2.ROI());
    checkSameSize(ROI(), pDst.ROI());
    nppSafeCallExt(nppiDiv_16sc_C1RSfs_Ctx(reinterpret_cast<const Npp16sc *>(PointerRoi()), to_int(Pitch()), reinterpret_cast<const Npp16sc *>(pSrc2.PointerRoi()), to_int(pSrc2.Pitch()), reinterpret_cast<Npp16sc *>(pDst.PointerRoi()), to_int(pDst.Pitch()), NppiSizeRoi(), nScaleFactor, nppStreamCtx),
                   "ROI Src1: " << ROI() << " ROI Src2: " << pSrc2.ROI() << "ROI Dst: " << pDst.ROI());
    return pDst;
}

Image16scC1View &Image16scC1View::Div(const Image16scC1View &pSrc, int nScaleFactor, const NppStreamContext &nppStreamCtx)
{
    checkSameSize(ROI(), pSrc.ROI());
    nppSafeCallExt(nppiDiv_16sc_C1IRSfs_Ctx(reinterpret_cast<const Npp16sc *>(pSrc.PointerRoi()), to_int(pSrc.Pitch()), reinterpret_cast<Npp16sc *>(PointerRoi()), to_int(Pitch()), NppiSizeRoi(), nScaleFactor, nppStreamCtx),
                   "ROI Src2: " << pSrc.ROI() << "ROI SrcDst: " << ROI());
    return *this;
}

void Image16scC1View::MaximumError(const Image16scC1View &pSrc2, mpp::cuda::DevVarView<double> &pError, mpp::cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const
{
    checkSameSize(ROI(), pSrc2.ROI());
    nppSafeCallExt(nppiMaximumError_16sc_C1R_Ctx(reinterpret_cast<const Npp16sc *>(PointerRoi()), to_int(Pitch()), reinterpret_cast<const Npp16sc *>(pSrc2.PointerRoi()), to_int(pSrc2.Pitch()), NppiSizeRoi(), pError.Pointer(), pDeviceBuffer.Pointer(), nppStreamCtx),
                   "ROI Src1: " << ROI() << " ROI Src2: " << pSrc2.ROI());
}

size_t Image16scC1View::MaximumErrorGetBufferHostSize(const NppStreamContext &nppStreamCtx) const
{
    size_t retValue = 0;
    nppSafeCall(nppiMaximumErrorGetBufferHostSize_16sc_C1R_Ctx(NppiSizeRoi(), &retValue, nppStreamCtx));
    return retValue;
}

void Image16scC1View::AverageError(const Image16scC1View &pSrc2, mpp::cuda::DevVarView<double> &pError, mpp::cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const
{
    checkSameSize(ROI(), pSrc2.ROI());
    nppSafeCallExt(nppiAverageError_16sc_C1R_Ctx(reinterpret_cast<const Npp16sc *>(PointerRoi()), to_int(Pitch()), reinterpret_cast<const Npp16sc *>(pSrc2.PointerRoi()), to_int(pSrc2.Pitch()), NppiSizeRoi(), pError.Pointer(), pDeviceBuffer.Pointer(), nppStreamCtx),
                   "ROI Src1: " << ROI() << " ROI Src2: " << pSrc2.ROI());
}

size_t Image16scC1View::AverageErrorGetBufferHostSize(const NppStreamContext &nppStreamCtx) const
{
    size_t retValue = 0;
    nppSafeCall(nppiAverageErrorGetBufferHostSize_16sc_C1R_Ctx(NppiSizeRoi(), &retValue, nppStreamCtx));
    return retValue;
}

void Image16scC1View::MaximumRelativeError(const Image16scC1View &pSrc2, mpp::cuda::DevVarView<double> &pError, mpp::cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const
{
    checkSameSize(ROI(), pSrc2.ROI());
    nppSafeCallExt(nppiMaximumRelativeError_16sc_C1R_Ctx(reinterpret_cast<const Npp16sc *>(PointerRoi()), to_int(Pitch()), reinterpret_cast<const Npp16sc *>(pSrc2.PointerRoi()), to_int(pSrc2.Pitch()), NppiSizeRoi(), pError.Pointer(), pDeviceBuffer.Pointer(), nppStreamCtx),
                   "ROI Src1: " << ROI() << " ROI Src2: " << pSrc2.ROI());
}

size_t Image16scC1View::MaximumRelativeErrorGetBufferHostSize(const NppStreamContext &nppStreamCtx) const
{
    size_t retValue = 0;
    nppSafeCall(nppiMaximumRelativeErrorGetBufferHostSize_16sc_C1R_Ctx(NppiSizeRoi(), &retValue, nppStreamCtx));
    return retValue;
}

void Image16scC1View::AverageRelativeError(const Image16scC1View &pSrc2, mpp::cuda::DevVarView<double> &pError, mpp::cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const
{
    checkSameSize(ROI(), pSrc2.ROI());
    nppSafeCallExt(nppiAverageRelativeError_16sc_C1R_Ctx(reinterpret_cast<const Npp16sc *>(PointerRoi()), to_int(Pitch()), reinterpret_cast<const Npp16sc *>(pSrc2.PointerRoi()), to_int(pSrc2.Pitch()), NppiSizeRoi(), pError.Pointer(), pDeviceBuffer.Pointer(), nppStreamCtx),
                   "ROI Src1: " << ROI() << " ROI Src2: " << pSrc2.ROI());
}

size_t Image16scC1View::AverageRelativeErrorGetBufferHostSize(const NppStreamContext &nppStreamCtx) const
{
    size_t retValue = 0;
    nppSafeCall(nppiAverageRelativeErrorGetBufferHostSize_16sc_C1R_Ctx(NppiSizeRoi(), &retValue, nppStreamCtx));
    return retValue;
}

//NOLINTEND(readability-identifier-naming,readability-avoid-const-params-in-decls, bugprone-easily-swappable-parameters, readability-convert-member-functions-to-static)
} // namespace mpp::image::npp
