// Code automatically generated by nppCodeGenerator - do not modify manually
#include "image32fcC2View.h"
#include "imageView.h"
#include <backends/cuda/devVarView.h> //NOLINT
#include <backends/npp/nppException.h>
#include <common/defines.h> //NOLINT
#include <common/exception.h> //NOLINT
#include <common/image/border.h>
#include <common/image/pixelTypes.h>
#include <common/image/roi.h>
#include <common/image/roiException.h>
#include <common/image/size2D.h>
#include <common/image/sizePitched.h>
#include <common/safeCast.h>
#include <cstddef> //NOLINT
#include <nppdefs.h>
#include <nppi_data_exchange_and_initialization.h>
#include <nppi_statistics_functions.h>

namespace opp::image::npp
{
Image32fcC2View::Image32fcC2View(const Size2D &aSize) : ImageView<Pixel32fcC2>(aSize)
{
}

Image32fcC2View::Image32fcC2View(Pixel32fcC2 *aBasePointer, const SizePitched &aSizeAlloc)
    : ImageView<Pixel32fcC2>(aBasePointer, aSizeAlloc)
{
}
Image32fcC2View::Image32fcC2View(Pixel32fcC2 *aBasePointer, const SizePitched &aSizeAlloc, const Roi &aRoi)
    : ImageView<Pixel32fcC2>(aBasePointer, aSizeAlloc, aRoi)
{
}

Image32fcC2View Image32fcC2View::GetView(const Roi &aRoi) const
{
    return {Pointer(), SizePitched(SizeAlloc(), Pitch()), aRoi};
}

Image32fcC2View Image32fcC2View::GetView(const Border &aBorder) const
{
    const Roi newRoi = ROI() + aBorder;
    checkRoiIsInRoi(newRoi, Roi(0, 0, SizeAlloc()));
    return {Pointer(), SizePitched(SizeAlloc(), Pitch()), newRoi};
}

//NOLINTBEGIN(readability-identifier-naming,readability-avoid-const-params-in-decls, bugprone-easily-swappable-parameters, readability-convert-member-functions-to-static)

void Image32fcC2View::Set(const Pixel32fcC2 &aValue, const NppStreamContext &nppStreamCtx)
{
    nppSafeCallExt(nppiSet_32fc_C2R_Ctx(reinterpret_cast<const Npp32fc *>(aValue.data()), reinterpret_cast<Npp32fc *>(PointerRoi()), to_int(Pitch()), NppiSizeRoi(), nppStreamCtx),
                   "ROI SrcDst: " << ROI());
}

void Image32fcC2View::Copy(Image32fcC2View &pDst, const NppStreamContext &nppStreamCtx) const
{
    checkSameSize(ROI(), pDst.ROI());
    nppSafeCallExt(nppiCopy_32fc_C2R_Ctx(reinterpret_cast<const Npp32fc *>(PointerRoi()), to_int(Pitch()), reinterpret_cast<Npp32fc *>(pDst.PointerRoi()), to_int(pDst.Pitch()), NppiSizeRoi(), nppStreamCtx),
                   "ROI Src: " << ROI() << "ROI Dst: " << pDst.ROI());
}

void Image32fcC2View::MaximumError(const Image32fcC2View &pSrc2, cuda::DevVarView<double> &pError, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const
{
    checkSameSize(ROI(), pSrc2.ROI());
    nppSafeCallExt(nppiMaximumError_32fc_C2R_Ctx(reinterpret_cast<const Npp32fc *>(PointerRoi()), to_int(Pitch()), reinterpret_cast<const Npp32fc *>(pSrc2.PointerRoi()), to_int(pSrc2.Pitch()), NppiSizeRoi(), pError.Pointer(), pDeviceBuffer.Pointer(), nppStreamCtx),
                   "ROI Src1: " << ROI() << " ROI Src2: " << pSrc2.ROI());
}

size_t Image32fcC2View::MaximumErrorGetBufferHostSize(const NppStreamContext &nppStreamCtx) const
{
    size_t retValue = 0;
    nppSafeCall(nppiMaximumErrorGetBufferHostSize_32fc_C2R_Ctx(NppiSizeRoi(), &retValue, nppStreamCtx));
    return retValue;
}

void Image32fcC2View::AverageError(const Image32fcC2View &pSrc2, cuda::DevVarView<double> &pError, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const
{
    checkSameSize(ROI(), pSrc2.ROI());
    nppSafeCallExt(nppiAverageError_32fc_C2R_Ctx(reinterpret_cast<const Npp32fc *>(PointerRoi()), to_int(Pitch()), reinterpret_cast<const Npp32fc *>(pSrc2.PointerRoi()), to_int(pSrc2.Pitch()), NppiSizeRoi(), pError.Pointer(), pDeviceBuffer.Pointer(), nppStreamCtx),
                   "ROI Src1: " << ROI() << " ROI Src2: " << pSrc2.ROI());
}

size_t Image32fcC2View::AverageErrorGetBufferHostSize(const NppStreamContext &nppStreamCtx) const
{
    size_t retValue = 0;
    nppSafeCall(nppiAverageErrorGetBufferHostSize_32fc_C2R_Ctx(NppiSizeRoi(), &retValue, nppStreamCtx));
    return retValue;
}

void Image32fcC2View::MaximumRelativeError(const Image32fcC2View &pSrc2, cuda::DevVarView<double> &pError, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const
{
    checkSameSize(ROI(), pSrc2.ROI());
    nppSafeCallExt(nppiMaximumRelativeError_32fc_C2R_Ctx(reinterpret_cast<const Npp32fc *>(PointerRoi()), to_int(Pitch()), reinterpret_cast<const Npp32fc *>(pSrc2.PointerRoi()), to_int(pSrc2.Pitch()), NppiSizeRoi(), pError.Pointer(), pDeviceBuffer.Pointer(), nppStreamCtx),
                   "ROI Src1: " << ROI() << " ROI Src2: " << pSrc2.ROI());
}

size_t Image32fcC2View::MaximumRelativeErrorGetBufferHostSize(const NppStreamContext &nppStreamCtx) const
{
    size_t retValue = 0;
    nppSafeCall(nppiMaximumRelativeErrorGetBufferHostSize_32fc_C2R_Ctx(NppiSizeRoi(), &retValue, nppStreamCtx));
    return retValue;
}

void Image32fcC2View::AverageRelativeError(const Image32fcC2View &pSrc2, cuda::DevVarView<double> &pError, cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const
{
    checkSameSize(ROI(), pSrc2.ROI());
    nppSafeCallExt(nppiAverageRelativeError_32fc_C2R_Ctx(reinterpret_cast<const Npp32fc *>(PointerRoi()), to_int(Pitch()), reinterpret_cast<const Npp32fc *>(pSrc2.PointerRoi()), to_int(pSrc2.Pitch()), NppiSizeRoi(), pError.Pointer(), pDeviceBuffer.Pointer(), nppStreamCtx),
                   "ROI Src1: " << ROI() << " ROI Src2: " << pSrc2.ROI());
}

size_t Image32fcC2View::AverageRelativeErrorGetBufferHostSize(const NppStreamContext &nppStreamCtx) const
{
    size_t retValue = 0;
    nppSafeCall(nppiAverageRelativeErrorGetBufferHostSize_32fc_C2R_Ctx(NppiSizeRoi(), &retValue, nppStreamCtx));
    return retValue;
}



//NOLINTEND(readability-identifier-naming,readability-avoid-const-params-in-decls, bugprone-easily-swappable-parameters, readability-convert-member-functions-to-static)
} // namespace opp::image::npp
