// Code automatically generated by nppCodeGenerator - do not modify manually
#include <common/moduleEnabler.h> //NOLINT(misc-include-cleaner)
#if MPP_ENABLE_NPP_BACKEND
#include <common/image/pixelTypeEnabler.h> //NOLINT(misc-include-cleaner)

#include "image16uC1View.h" //NOLINT
#include "image16uC2View.h" //NOLINT
#include "image16uC3View.h" //NOLINT
#include "imageView.h"  //NOLINT
#include <backends/cuda/devVarView.h> //NOLINT
#include <backends/npp/nppException.h>  //NOLINT
#include <common/defines.h> //NOLINT
#include <common/exception.h> //NOLINT
#include <common/image/affineTransformation.h> //NOLINT
#include <common/image/border.h> //NOLINT
#include <common/image/bound.h> //NOLINT
#include <common/image/matrix.h> //NOLINT
#include <common/image/pixelTypes.h> //NOLINT
#include <common/image/quad.h> //NOLINT
#include <common/image/roi.h> //NOLINT
#include <common/image/roiException.h>  //NOLINT
#include <common/image/size2D.h>  //NOLINT
#include <common/image/sizePitched.h>  //NOLINT
#include <common/safeCast.h>  //NOLINT
#include <cstddef> //NOLINT
#include <nppdefs.h>  //NOLINT
#include <nppi_color_conversion.h> //NOLINT
#include <nppi_data_exchange_and_initialization.h> //NOLINT
#include <nppi_statistics_functions.h> //NOLINT

namespace mpp::image::npp
{
Image16uC2View::Image16uC2View(const Size2D &aSize) : ImageView<Pixel16uC2>(aSize)
{
}

Image16uC2View::Image16uC2View(Pixel16uC2 *aBasePointer, const SizePitched &aSizeAlloc)
    : ImageView<Pixel16uC2>(aBasePointer, aSizeAlloc)
{
}
Image16uC2View::Image16uC2View(Pixel16uC2 *aBasePointer, const SizePitched &aSizeAlloc, const Roi &aRoi)
    : ImageView<Pixel16uC2>(aBasePointer, aSizeAlloc, aRoi)
{
}

Image16uC2View Image16uC2View::GetView(const Roi &aRoi)
{
    return {Pointer(), SizePitched(SizeAlloc(), Pitch()), aRoi};
}

Image16uC2View Image16uC2View::GetView(const Border &aBorder)
{
    const Roi newRoi = ROI() + aBorder;
    checkRoiIsInRoi(newRoi, Roi(0, 0, SizeAlloc()));
    return {Pointer(), SizePitched(SizeAlloc(), Pitch()), newRoi};
}

//NOLINTBEGIN(readability-identifier-naming,readability-avoid-const-params-in-decls, bugprone-easily-swappable-parameters, readability-convert-member-functions-to-static)
#if MPPi_ENABLE_UINT16_TYPE && MPPi_ENABLE_TWO_CHANNEL

Image16uC2View &Image16uC2View::Set(const Pixel16uC2 &aValue, const NppStreamContext &nppStreamCtx)
{
    nppSafeCallExt(nppiSet_16u_C2R_Ctx(aValue.data(), reinterpret_cast<Npp16u *>(PointerRoi()), to_int(Pitch()), NppiSizeRoi(), nppStreamCtx),
                   "ROI SrcDst: " << ROI());
    return *this;
}

Image16uC2View &Image16uC2View::ColorTwist32f(Image16uC2View &pDst, const Npp32f aTwist[3][4], const NppStreamContext &nppStreamCtx) const
{
    checkSameSize(ROI(), pDst.ROI());
    nppSafeCallExt(nppiColorTwist32f_16u_C2R_Ctx(reinterpret_cast<const Npp16u *>(PointerRoi()), to_int(Pitch()), reinterpret_cast<Npp16u *>(pDst.PointerRoi()), to_int(pDst.Pitch()), NppiSizeRoi(), aTwist, nppStreamCtx),
                   "ROI Src: " << ROI() << "ROI Dst: " << pDst.ROI());
    return pDst;
}

Image16uC2View &Image16uC2View::ColorTwist32f(const Npp32f aTwist[3][4], const NppStreamContext &nppStreamCtx)
{
    nppSafeCallExt(nppiColorTwist32f_16u_C2IR_Ctx(reinterpret_cast<Npp16u *>(PointerRoi()), to_int(Pitch()), NppiSizeRoi(), aTwist, nppStreamCtx),
                   "ROI SrcDst: " << ROI());
    return *this;
}

Image16uC3View &Image16uC2View::YUV422ToRGB(Image16uC3View &pDst, const Npp32f aTwist[3][4], const NppStreamContext &nppStreamCtx) const
{
    checkSameSize(ROI(), pDst.ROI());
    nppSafeCallExt(nppiYUV422ToRGB_16u_ColorTwist32f_C2C3R_Ctx(reinterpret_cast<const Npp16u *>(PointerRoi()), to_int(Pitch()), reinterpret_cast<Npp16u *>(pDst.PointerRoi()), to_int(pDst.Pitch()), NppiSizeRoi(), aTwist, nppStreamCtx),
                   "ROI Src: " << ROI() << "ROI Dst: " << pDst.ROI());
    return pDst;
}

Image16uC3View &Image16uC2View::NV12ToRGB(const Image16uC1View &aSrcChannel0, const Image16uC1View &aSrcChannel1, Image16uC3View &pDst, const Npp32f aTwist[3][4], const NppStreamContext &nppStreamCtx)
{
    const Npp16u * srcList[] = { reinterpret_cast<const Npp16u *>(aSrcChannel0.PointerRoi()), reinterpret_cast<const Npp16u *>(aSrcChannel1.PointerRoi()) };
    int pitchSrcList[] = { to_int(aSrcChannel0.Pitch()), to_int(aSrcChannel1.Pitch()) };
    nppSafeCall(nppiNV12ToRGB_16u_ColorTwist32f_P2C3R_Ctx(srcList, pitchSrcList, reinterpret_cast<Npp16u *>(pDst.PointerRoi()), to_int(pDst.Pitch()), aSrcChannel0.NppiSizeRoi(), aTwist, nppStreamCtx));
    return pDst;
}

void Image16uC2View::MaximumError(const Image16uC2View &pSrc2, mpp::cuda::DevVarView<double> &pError, mpp::cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const
{
    checkSameSize(ROI(), pSrc2.ROI());
    nppSafeCallExt(nppiMaximumError_16u_C2R_Ctx(reinterpret_cast<const Npp16u *>(PointerRoi()), to_int(Pitch()), reinterpret_cast<const Npp16u *>(pSrc2.PointerRoi()), to_int(pSrc2.Pitch()), NppiSizeRoi(), pError.Pointer(), pDeviceBuffer.Pointer(), nppStreamCtx),
                   "ROI Src1: " << ROI() << " ROI Src2: " << pSrc2.ROI());
}

size_t Image16uC2View::MaximumErrorGetBufferHostSize(const NppStreamContext &nppStreamCtx) const
{
    size_t retValue = 0;
    nppSafeCall(nppiMaximumErrorGetBufferHostSize_16u_C2R_Ctx(NppiSizeRoi(), &retValue, nppStreamCtx));
    return retValue;
}

void Image16uC2View::AverageError(const Image16uC2View &pSrc2, mpp::cuda::DevVarView<double> &pError, mpp::cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const
{
    checkSameSize(ROI(), pSrc2.ROI());
    nppSafeCallExt(nppiAverageError_16u_C2R_Ctx(reinterpret_cast<const Npp16u *>(PointerRoi()), to_int(Pitch()), reinterpret_cast<const Npp16u *>(pSrc2.PointerRoi()), to_int(pSrc2.Pitch()), NppiSizeRoi(), pError.Pointer(), pDeviceBuffer.Pointer(), nppStreamCtx),
                   "ROI Src1: " << ROI() << " ROI Src2: " << pSrc2.ROI());
}

size_t Image16uC2View::AverageErrorGetBufferHostSize(const NppStreamContext &nppStreamCtx) const
{
    size_t retValue = 0;
    nppSafeCall(nppiAverageErrorGetBufferHostSize_16u_C2R_Ctx(NppiSizeRoi(), &retValue, nppStreamCtx));
    return retValue;
}

void Image16uC2View::MaximumRelativeError(const Image16uC2View &pSrc2, mpp::cuda::DevVarView<double> &pError, mpp::cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const
{
    checkSameSize(ROI(), pSrc2.ROI());
    nppSafeCallExt(nppiMaximumRelativeError_16u_C2R_Ctx(reinterpret_cast<const Npp16u *>(PointerRoi()), to_int(Pitch()), reinterpret_cast<const Npp16u *>(pSrc2.PointerRoi()), to_int(pSrc2.Pitch()), NppiSizeRoi(), pError.Pointer(), pDeviceBuffer.Pointer(), nppStreamCtx),
                   "ROI Src1: " << ROI() << " ROI Src2: " << pSrc2.ROI());
}

size_t Image16uC2View::MaximumRelativeErrorGetBufferHostSize(const NppStreamContext &nppStreamCtx) const
{
    size_t retValue = 0;
    nppSafeCall(nppiMaximumRelativeErrorGetBufferHostSize_16u_C2R_Ctx(NppiSizeRoi(), &retValue, nppStreamCtx));
    return retValue;
}

void Image16uC2View::AverageRelativeError(const Image16uC2View &pSrc2, mpp::cuda::DevVarView<double> &pError, mpp::cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const
{
    checkSameSize(ROI(), pSrc2.ROI());
    nppSafeCallExt(nppiAverageRelativeError_16u_C2R_Ctx(reinterpret_cast<const Npp16u *>(PointerRoi()), to_int(Pitch()), reinterpret_cast<const Npp16u *>(pSrc2.PointerRoi()), to_int(pSrc2.Pitch()), NppiSizeRoi(), pError.Pointer(), pDeviceBuffer.Pointer(), nppStreamCtx),
                   "ROI Src1: " << ROI() << " ROI Src2: " << pSrc2.ROI());
}

size_t Image16uC2View::AverageRelativeErrorGetBufferHostSize(const NppStreamContext &nppStreamCtx) const
{
    size_t retValue = 0;
    nppSafeCall(nppiAverageRelativeErrorGetBufferHostSize_16u_C2R_Ctx(NppiSizeRoi(), &retValue, nppStreamCtx));
    return retValue;
}

#endif // MPPi_ENABLE_UINT16_TYPE && MPPi_ENABLE_TWO_CHANNEL
//NOLINTEND(readability-identifier-naming,readability-avoid-const-params-in-decls, bugprone-easily-swappable-parameters, readability-convert-member-functions-to-static)
} // namespace mpp::image::npp
#endif // MPP_ENABLE_NPP_BACKEND
