// Code automatically generated by nppCodeGenerator - do not modify manually

#pragma once
#include <common/moduleEnabler.h>
#if OPP_ENABLE_NPP_BACKEND
#include <common/image/pixelTypeEnabler.h>

#include "imageView.h"
#include <backends/cuda/devVarView.h>
#include <backends/npp/nppException.h>
#include <common/image/pixelTypes.h>
#include <common/image/roi.h>
#include <common/image/roiException.h>
#include <common/image/size2D.h>
#include <common/image/sizePitched.h>

namespace opp::image::npp
{
// forward declaration:

class Image32fcC4View : public ImageView<Pixel32fcC4>
{
  protected:
    Image32fcC4View() = default;
    explicit Image32fcC4View(const Size2D &aSize);

  public:
    Image32fcC4View(Pixel32fcC4 *aBasePointer, const SizePitched &aSizeAlloc);
    Image32fcC4View(Pixel32fcC4 *aBasePointer, const SizePitched &aSizeAlloc, const Roi &aRoi);
    ~Image32fcC4View() = default;

    Image32fcC4View(const Image32fcC4View &)     = default;
    Image32fcC4View(Image32fcC4View &&) noexcept = default;

    Image32fcC4View &operator=(const Image32fcC4View &)     = default;
    Image32fcC4View &operator=(Image32fcC4View &&) noexcept = default;

    /// <summary>
    /// Returns a new Image32fcC4View with the new ROI
    /// </summary>
    [[nodiscard]] Image32fcC4View GetView(const Roi &aRoi) const;

    /// <summary>
    /// Returns a new ImageView with the current ROI adapted by aBorder
    /// </summary>
    [[nodiscard]] Image32fcC4View GetView(const Border &aBorder = Border()) const;

    //NOLINTBEGIN(readability-identifier-naming,readability-avoid-const-params-in-decls, bugprone-easily-swappable-parameters, readability-convert-member-functions-to-static)
#if OPPi_ENABLE_COMPLEX_FLOAT_TYPE && OPPi_ENABLE_FOUR_CHANNEL

    // NppStatus nppiSet_32fc_C4R_Ctx(const Npp32fc[4] aValue, Npp32fc * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image32fcC4View &Set(const Pixel32fcC4 &aValue, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiSet_32fc_AC4R_Ctx(const Npp32fc[3] aValue, Npp32fc * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image32fcC4View &SetA(const Pixel32fcC3 &aValue, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiCopy_32fc_C4R_Ctx(const Npp32fc * pSrc, int nSrcStep, Npp32fc * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image32fcC4View &Copy(Image32fcC4View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiCopy_32fc_AC4R_Ctx(const Npp32fc * pSrc, int nSrcStep, Npp32fc * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image32fcC4View &CopyA(Image32fcC4View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiAddC_32fc_AC4R_Ctx(const Npp32fc * pSrc1, int nSrc1Step, const Npp32fc[3] aConstants, Npp32fc * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image32fcC4View &AddA(const Pixel32fcC3 &aConstants, Image32fcC4View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiAddC_32fc_AC4IR_Ctx(const Npp32fc[3] aConstants, Npp32fc * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image32fcC4View &AddA(const Pixel32fcC3 &aConstants, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiAddC_32fc_C4R_Ctx(const Npp32fc * pSrc1, int nSrc1Step, const Npp32fc[4] aConstants, Npp32fc * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image32fcC4View &Add(const Pixel32fcC4 &aConstants, Image32fcC4View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiAddC_32fc_C4IR_Ctx(const Npp32fc[4] aConstants, Npp32fc * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image32fcC4View &Add(const Pixel32fcC4 &aConstants, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiMulC_32fc_AC4R_Ctx(const Npp32fc * pSrc1, int nSrc1Step, const Npp32fc[3] aConstants, Npp32fc * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image32fcC4View &MulA(const Pixel32fcC3 &aConstants, Image32fcC4View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiMulC_32fc_AC4IR_Ctx(const Npp32fc[3] aConstants, Npp32fc * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image32fcC4View &MulA(const Pixel32fcC3 &aConstants, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiMulC_32fc_C4R_Ctx(const Npp32fc * pSrc1, int nSrc1Step, const Npp32fc[4] aConstants, Npp32fc * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image32fcC4View &Mul(const Pixel32fcC4 &aConstants, Image32fcC4View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiMulC_32fc_C4IR_Ctx(const Npp32fc[4] aConstants, Npp32fc * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image32fcC4View &Mul(const Pixel32fcC4 &aConstants, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiSubC_32fc_AC4R_Ctx(const Npp32fc * pSrc1, int nSrc1Step, const Npp32fc[3] aConstants, Npp32fc * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image32fcC4View &SubA(const Pixel32fcC3 &aConstants, Image32fcC4View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiSubC_32fc_AC4IR_Ctx(const Npp32fc[3] aConstants, Npp32fc * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image32fcC4View &SubA(const Pixel32fcC3 &aConstants, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiSubC_32fc_C4R_Ctx(const Npp32fc * pSrc1, int nSrc1Step, const Npp32fc[4] aConstants, Npp32fc * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image32fcC4View &Sub(const Pixel32fcC4 &aConstants, Image32fcC4View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiSubC_32fc_C4IR_Ctx(const Npp32fc[4] aConstants, Npp32fc * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image32fcC4View &Sub(const Pixel32fcC4 &aConstants, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiDivC_32fc_AC4R_Ctx(const Npp32fc * pSrc1, int nSrc1Step, const Npp32fc[3] aConstants, Npp32fc * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image32fcC4View &DivA(const Pixel32fcC3 &aConstants, Image32fcC4View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiDivC_32fc_AC4IR_Ctx(const Npp32fc[3] aConstants, Npp32fc * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image32fcC4View &DivA(const Pixel32fcC3 &aConstants, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiDivC_32fc_C4R_Ctx(const Npp32fc * pSrc1, int nSrc1Step, const Npp32fc[4] aConstants, Npp32fc * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image32fcC4View &Div(const Pixel32fcC4 &aConstants, Image32fcC4View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiDivC_32fc_C4IR_Ctx(const Npp32fc[4] aConstants, Npp32fc * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image32fcC4View &Div(const Pixel32fcC4 &aConstants, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiAdd_32fc_AC4R_Ctx(const Npp32fc * pSrc1, int nSrc1Step, const Npp32fc * pSrc2, int nSrc2Step, Npp32fc * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image32fcC4View &AddA(const Image32fcC4View &pSrc2, Image32fcC4View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiAdd_32fc_AC4IR_Ctx(const Npp32fc * pSrc, int nSrcStep, Npp32fc * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image32fcC4View &AddA(const Image32fcC4View &pSrc, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiAdd_32fc_C4R_Ctx(const Npp32fc * pSrc1, int nSrc1Step, const Npp32fc * pSrc2, int nSrc2Step, Npp32fc * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image32fcC4View &Add(const Image32fcC4View &pSrc2, Image32fcC4View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiAdd_32fc_C4IR_Ctx(const Npp32fc * pSrc, int nSrcStep, Npp32fc * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image32fcC4View &Add(const Image32fcC4View &pSrc, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiMul_32fc_AC4R_Ctx(const Npp32fc * pSrc1, int nSrc1Step, const Npp32fc * pSrc2, int nSrc2Step, Npp32fc * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image32fcC4View &MulA(const Image32fcC4View &pSrc2, Image32fcC4View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiMul_32fc_AC4IR_Ctx(const Npp32fc * pSrc, int nSrcStep, Npp32fc * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image32fcC4View &MulA(const Image32fcC4View &pSrc, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiMul_32fc_C4R_Ctx(const Npp32fc * pSrc1, int nSrc1Step, const Npp32fc * pSrc2, int nSrc2Step, Npp32fc * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image32fcC4View &Mul(const Image32fcC4View &pSrc2, Image32fcC4View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiMul_32fc_C4IR_Ctx(const Npp32fc * pSrc, int nSrcStep, Npp32fc * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image32fcC4View &Mul(const Image32fcC4View &pSrc, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiSub_32fc_AC4R_Ctx(const Npp32fc * pSrc1, int nSrc1Step, const Npp32fc * pSrc2, int nSrc2Step, Npp32fc * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image32fcC4View &SubA(const Image32fcC4View &pSrc2, Image32fcC4View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiSub_32fc_AC4IR_Ctx(const Npp32fc * pSrc, int nSrcStep, Npp32fc * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image32fcC4View &SubA(const Image32fcC4View &pSrc, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiSub_32fc_C4R_Ctx(const Npp32fc * pSrc1, int nSrc1Step, const Npp32fc * pSrc2, int nSrc2Step, Npp32fc * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image32fcC4View &Sub(const Image32fcC4View &pSrc2, Image32fcC4View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiSub_32fc_C4IR_Ctx(const Npp32fc * pSrc, int nSrcStep, Npp32fc * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image32fcC4View &Sub(const Image32fcC4View &pSrc, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiDiv_32fc_AC4R_Ctx(const Npp32fc * pSrc1, int nSrc1Step, const Npp32fc * pSrc2, int nSrc2Step, Npp32fc * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image32fcC4View &DivA(const Image32fcC4View &pSrc2, Image32fcC4View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiDiv_32fc_AC4IR_Ctx(const Npp32fc * pSrc, int nSrcStep, Npp32fc * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image32fcC4View &DivA(const Image32fcC4View &pSrc, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiDiv_32fc_C4R_Ctx(const Npp32fc * pSrc1, int nSrc1Step, const Npp32fc * pSrc2, int nSrc2Step, Npp32fc * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image32fcC4View &Div(const Image32fcC4View &pSrc2, Image32fcC4View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiDiv_32fc_C4IR_Ctx(const Npp32fc * pSrc, int nSrcStep, Npp32fc * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image32fcC4View &Div(const Image32fcC4View &pSrc, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiMaximumError_32fc_C4R_Ctx(const Npp32fc * pSrc1, int nSrc1Step, const Npp32fc * pSrc2, int nSrc2Step, NppiSize oSizeROI, Npp64f * pError, Npp8u * pDeviceBuffer, NppStreamContext nppStreamCtx)
    void MaximumError(const Image32fcC4View &pSrc2, opp::cuda::DevVarView<double> &pError, opp::cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiMaximumErrorGetBufferHostSize_32fc_C4R_Ctx(NppiSize oSizeROI, size_t * hpBufferSize, NppStreamContext nppStreamCtx)
    [[nodiscard]] size_t MaximumErrorGetBufferHostSize(const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiAverageError_32fc_C4R_Ctx(const Npp32fc * pSrc1, int nSrc1Step, const Npp32fc * pSrc2, int nSrc2Step, NppiSize oSizeROI, Npp64f * pError, Npp8u * pDeviceBuffer, NppStreamContext nppStreamCtx)
    void AverageError(const Image32fcC4View &pSrc2, opp::cuda::DevVarView<double> &pError, opp::cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiAverageErrorGetBufferHostSize_32fc_C4R_Ctx(NppiSize oSizeROI, size_t * hpBufferSize, NppStreamContext nppStreamCtx)
    [[nodiscard]] size_t AverageErrorGetBufferHostSize(const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiMaximumRelativeError_32fc_C4R_Ctx(const Npp32fc * pSrc1, int nSrc1Step, const Npp32fc * pSrc2, int nSrc2Step, NppiSize oSizeROI, Npp64f * pError, Npp8u * pDeviceBuffer, NppStreamContext nppStreamCtx)
    void MaximumRelativeError(const Image32fcC4View &pSrc2, opp::cuda::DevVarView<double> &pError, opp::cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiMaximumRelativeErrorGetBufferHostSize_32fc_C4R_Ctx(NppiSize oSizeROI, size_t * hpBufferSize, NppStreamContext nppStreamCtx)
    [[nodiscard]] size_t MaximumRelativeErrorGetBufferHostSize(const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiAverageRelativeError_32fc_C4R_Ctx(const Npp32fc * pSrc1, int nSrc1Step, const Npp32fc * pSrc2, int nSrc2Step, NppiSize oSizeROI, Npp64f * pError, Npp8u * pDeviceBuffer, NppStreamContext nppStreamCtx)
    void AverageRelativeError(const Image32fcC4View &pSrc2, opp::cuda::DevVarView<double> &pError, opp::cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiAverageRelativeErrorGetBufferHostSize_32fc_C4R_Ctx(NppiSize oSizeROI, size_t * hpBufferSize, NppStreamContext nppStreamCtx)
    [[nodiscard]] size_t AverageRelativeErrorGetBufferHostSize(const NppStreamContext &nppStreamCtx) const;

#endif // OPPi_ENABLE_COMPLEX_FLOAT_TYPE && OPPi_ENABLE_FOUR_CHANNEL
    //NOLINTEND(readability-identifier-naming,readability-avoid-const-params-in-decls, bugprone-easily-swappable-parameters, readability-convert-member-functions-to-static)
};
} // namespace opp::image::npp
#endif // OPP_ENABLE_NPP_BACKEND
