// Code automatically generated by nppCodeGenerator - do not modify manually

#pragma once
#include <common/moduleEnabler.h>
#if MPP_ENABLE_NPP_BACKEND
#include <common/image/pixelTypeEnabler.h>

#include "../dllexport_npp.h"
#include "imageView.h"
#include <backends/cuda/devVarView.h>
#include <backends/npp/nppException.h>
#include <common/image/pixelTypes.h>
#include <common/image/roi.h>
#include <common/image/roiException.h>
#include <common/image/size2D.h>
#include <common/image/sizePitched.h>

namespace mpp::image::npp
{
// forward declaration:
class MPPEXPORT_NPP Image32fC1View;

class MPPEXPORT_NPP Image32fcC1View : public ImageView<Pixel32fcC1>
{
  protected:
    Image32fcC1View() = default;
    explicit Image32fcC1View(const Size2D &aSize);

  public:
    Image32fcC1View(Pixel32fcC1 *aBasePointer, const SizePitched &aSizeAlloc);
    Image32fcC1View(Pixel32fcC1 *aBasePointer, const SizePitched &aSizeAlloc, const Roi &aRoi);
    ~Image32fcC1View() override = default;

    Image32fcC1View(const Image32fcC1View &)     = default;
    Image32fcC1View(Image32fcC1View &&) noexcept = default;

    Image32fcC1View &operator=(const Image32fcC1View &)     = default;
    Image32fcC1View &operator=(Image32fcC1View &&) noexcept = default;

    /// <summary>
    /// Returns a new Image32fcC1View with the new ROI
    /// </summary>
    [[nodiscard]] Image32fcC1View GetView(const Roi &aRoi);

    /// <summary>
    /// Returns a new ImageView with the current ROI adapted by aBorder
    /// </summary>
    [[nodiscard]] Image32fcC1View GetView(const Border &aBorder = Border());

    //NOLINTBEGIN(readability-identifier-naming,readability-avoid-const-params-in-decls, bugprone-easily-swappable-parameters, readability-convert-member-functions-to-static)
#if MPPi_ENABLE_COMPLEX_FLOAT_TYPE && MPPi_ENABLE_ONE_CHANNEL

    // NppStatus nppiSet_32fc_C1R_Ctx(const Npp32fc oValue, Npp32fc * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image32fcC1View &Set(const Pixel32fcC1 &oValue, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiCopy_32fc_C1R_Ctx(const Npp32fc * pSrc, int nSrcStep, Npp32fc * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image32fcC1View &Copy(Image32fcC1View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiAddC_32fc_C1R_Ctx(const Npp32fc * pSrc1, int nSrc1Step, const Npp32fc nConstant, Npp32fc * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image32fcC1View &Add(const Pixel32fcC1 &nConstant, Image32fcC1View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiAddC_32fc_C1IR_Ctx(const Npp32fc nConstant, Npp32fc * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image32fcC1View &Add(const Pixel32fcC1 &nConstant, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiMulC_32fc_C1R_Ctx(const Npp32fc * pSrc1, int nSrc1Step, const Npp32fc nConstant, Npp32fc * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image32fcC1View &Mul(const Pixel32fcC1 &nConstant, Image32fcC1View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiMulC_32fc_C1IR_Ctx(const Npp32fc nConstant, Npp32fc * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image32fcC1View &Mul(const Pixel32fcC1 &nConstant, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiSubC_32fc_C1R_Ctx(const Npp32fc * pSrc1, int nSrc1Step, const Npp32fc nConstant, Npp32fc * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image32fcC1View &Sub(const Pixel32fcC1 &nConstant, Image32fcC1View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiSubC_32fc_C1IR_Ctx(const Npp32fc nConstant, Npp32fc * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image32fcC1View &Sub(const Pixel32fcC1 &nConstant, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiDivC_32fc_C1R_Ctx(const Npp32fc * pSrc1, int nSrc1Step, const Npp32fc nConstant, Npp32fc * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image32fcC1View &Div(const Pixel32fcC1 &nConstant, Image32fcC1View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiDivC_32fc_C1IR_Ctx(const Npp32fc nConstant, Npp32fc * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image32fcC1View &Div(const Pixel32fcC1 &nConstant, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiAdd_32fc_C1R_Ctx(const Npp32fc * pSrc1, int nSrc1Step, const Npp32fc * pSrc2, int nSrc2Step, Npp32fc * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image32fcC1View &Add(const Image32fcC1View &pSrc2, Image32fcC1View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiAdd_32fc_C1IR_Ctx(const Npp32fc * pSrc, int nSrcStep, Npp32fc * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image32fcC1View &Add(const Image32fcC1View &pSrc, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiMul_32fc_C1R_Ctx(const Npp32fc * pSrc1, int nSrc1Step, const Npp32fc * pSrc2, int nSrc2Step, Npp32fc * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image32fcC1View &Mul(const Image32fcC1View &pSrc2, Image32fcC1View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiMul_32fc_C1IR_Ctx(const Npp32fc * pSrc, int nSrcStep, Npp32fc * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image32fcC1View &Mul(const Image32fcC1View &pSrc, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiSub_32fc_C1R_Ctx(const Npp32fc * pSrc1, int nSrc1Step, const Npp32fc * pSrc2, int nSrc2Step, Npp32fc * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image32fcC1View &Sub(const Image32fcC1View &pSrc2, Image32fcC1View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiSub_32fc_C1IR_Ctx(const Npp32fc * pSrc, int nSrcStep, Npp32fc * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image32fcC1View &Sub(const Image32fcC1View &pSrc, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiDiv_32fc_C1R_Ctx(const Npp32fc * pSrc1, int nSrc1Step, const Npp32fc * pSrc2, int nSrc2Step, Npp32fc * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image32fcC1View &Div(const Image32fcC1View &pSrc2, Image32fcC1View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiDiv_32fc_C1IR_Ctx(const Npp32fc * pSrc, int nSrcStep, Npp32fc * pSrcDst, int nSrcDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image32fcC1View &Div(const Image32fcC1View &pSrc, const NppStreamContext &nppStreamCtx);

    // NppStatus nppiMaximumError_32fc_C1R_Ctx(const Npp32fc * pSrc1, int nSrc1Step, const Npp32fc * pSrc2, int nSrc2Step, NppiSize oSizeROI, Npp64f * pError, Npp8u * pDeviceBuffer, NppStreamContext nppStreamCtx)
    void MaximumError(const Image32fcC1View &pSrc2, mpp::cuda::DevVarView<double> &pError, mpp::cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiMaximumErrorGetBufferHostSize_32fc_C1R_Ctx(NppiSize oSizeROI, size_t * hpBufferSize, NppStreamContext nppStreamCtx)
    [[nodiscard]] size_t MaximumErrorGetBufferHostSize(const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiAverageError_32fc_C1R_Ctx(const Npp32fc * pSrc1, int nSrc1Step, const Npp32fc * pSrc2, int nSrc2Step, NppiSize oSizeROI, Npp64f * pError, Npp8u * pDeviceBuffer, NppStreamContext nppStreamCtx)
    void AverageError(const Image32fcC1View &pSrc2, mpp::cuda::DevVarView<double> &pError, mpp::cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiAverageErrorGetBufferHostSize_32fc_C1R_Ctx(NppiSize oSizeROI, size_t * hpBufferSize, NppStreamContext nppStreamCtx)
    [[nodiscard]] size_t AverageErrorGetBufferHostSize(const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiMaximumRelativeError_32fc_C1R_Ctx(const Npp32fc * pSrc1, int nSrc1Step, const Npp32fc * pSrc2, int nSrc2Step, NppiSize oSizeROI, Npp64f * pError, Npp8u * pDeviceBuffer, NppStreamContext nppStreamCtx)
    void MaximumRelativeError(const Image32fcC1View &pSrc2, mpp::cuda::DevVarView<double> &pError, mpp::cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiMaximumRelativeErrorGetBufferHostSize_32fc_C1R_Ctx(NppiSize oSizeROI, size_t * hpBufferSize, NppStreamContext nppStreamCtx)
    [[nodiscard]] size_t MaximumRelativeErrorGetBufferHostSize(const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiAverageRelativeError_32fc_C1R_Ctx(const Npp32fc * pSrc1, int nSrc1Step, const Npp32fc * pSrc2, int nSrc2Step, NppiSize oSizeROI, Npp64f * pError, Npp8u * pDeviceBuffer, NppStreamContext nppStreamCtx)
    void AverageRelativeError(const Image32fcC1View &pSrc2, mpp::cuda::DevVarView<double> &pError, mpp::cuda::DevVarView<byte> &pDeviceBuffer, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiAverageRelativeErrorGetBufferHostSize_32fc_C1R_Ctx(NppiSize oSizeROI, size_t * hpBufferSize, NppStreamContext nppStreamCtx)
    [[nodiscard]] size_t AverageRelativeErrorGetBufferHostSize(const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiMagnitude_32fc32f_C1R_Ctx(const Npp32fc * pSrc, int nSrcStep, Npp32f * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image32fC1View &Magnitude(Image32fC1View &pDst, const NppStreamContext &nppStreamCtx) const;

    // NppStatus nppiMagnitudeSqr_32fc32f_C1R_Ctx(const Npp32fc * pSrc, int nSrcStep, Npp32f * pDst, int nDstStep, NppiSize oSizeROI, NppStreamContext nppStreamCtx)
    Image32fC1View &MagnitudeSqr(Image32fC1View &pDst, const NppStreamContext &nppStreamCtx) const;

#endif // MPPi_ENABLE_COMPLEX_FLOAT_TYPE && MPPi_ENABLE_ONE_CHANNEL
    //NOLINTEND(readability-identifier-naming,readability-avoid-const-params-in-decls, bugprone-easily-swappable-parameters, readability-convert-member-functions-to-static)
};
} // namespace mpp::image::npp
#endif // MPP_ENABLE_NPP_BACKEND
